### ISSUE TITLE
Win+Q combination does not work

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [valinet/ExplorerPatcher#10]
So I usually run some AutoHotkey scripts on my PC for custom hotkey shortcuts. One of the scripts uses Win key shortcuts that Windows does not use. This is the AHK:

#Persistent
#SingleInstance, Force
#y::Run, mblctr.exe, C:\Windows\system32
#q::Run, ms-availablenetworks:
#j::Run, control.exe /name Microsoft.WindowsUpdate

However when I run this AHK or its compiled EXE version, Win+X also opens ms-availablenetworks: instead of opening the Win+X menu. Definitely some conflict. Is it because of this? https://github.com/valinet/ExplorerPatcher/issues/3

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Ok it seems Win+Q opens search as well as Win+S. And Win key also opens search. So I thought Win+Q was redundant, chose to remap it. I switched to Win+O instead for ms-availablenetworks: . Problem solved. Now Win+X opens that menu as expected. Win+O is only used for changing orientation on tablet PC/detachable rotatable tablets so I have no use for it. Can remap it. :)

**Comment by valinet** [comment]
Yes, it is because of that (#3). The way it works right now is the `Win+X` combination is caught in a hooked `CTray::HandleGlobalHotkey` (from `twinui.pcshell`) but because I cannot get a pointer to the `CLauncherTipContextMenu` instance from there using the COM interface query from there properly, my workaround was to fire a key combination (`Win+Q`) that is then caught in `CImmersiveHotkeyNotification::OnMessage` (from `twinui`) and from there open the menu, which works. That is definitely hacky and should be corrected, but I don't know why invoking the menu directly from the first callback does not work, it just gets me a different pointer every time.

So, yes, it will be fixed eventually, once I figure out how; I know about it.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Well it's the same as #3 so if you want to close the issue, please do :)

**Comment by valinet** [comment]
Yeah, I don't mind, I will close them both for good soon =))) (hopefully)

**Comment by valinet** [comment]
I fixed it in the latest build (22000.168.0.11), `Win+Q` is now free to map to whatever you'd like.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Oh wow thank you so much!!
