### ISSUE TITLE
Explorer.exe caught in restart loop

### ISSUE THREAD

**Issue by PeteGeek80** [valinet/ExplorerPatcher#1089]
Unable to check recent Windows update version. Explorer caught in a restart loop.

**Comment by mtsdawson** [comment]
Control Alt Delete, Task Manager, then Run, Control Panel (might need a few tries).

Then Programs. Uninstall Explorer Patcher. Then reinstall the current build.
________________________________
From: PeteGeek80 ***@***.***>
Sent: Thursday, March 16, 2023 10:06:59 PM
To: valinet/ExplorerPatcher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [valinet/ExplorerPatcher] Explorer.exe caught in restart loop (Issue #1089)


Unable to check recent Windows update version. Explorer caught in a restart loop.

**Comment by PeteGeek80** [comment]
> Control Alt Delete, Task Manager, then Run, Control Panel (might need a few tries). Then Programs. Uninstall Explorer Patcher. Then reinstall the current build.
> […](#)
> ________________________________ From: PeteGeek80 ***@***.***> Sent: Thursday, March 16, 2023 10:06:59 PM To: valinet/ExplorerPatcher ***@***.***> Cc: Subscribed ***@***.***> Subject: [valinet/ExplorerPatcher] Explorer.exe caught in restart loop (Issue #1089) Unable to check recent Windows update version. Explorer caught in a restart loop. — Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvalinet%2FExplorerPatcher%2Fissues%2F1089&data=05%7C01%7C%7C2be2541aa886499a085508db268c4b1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146156212376035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=20ueIE2Iucxf3%2F0zZqFhlJxWauHxz4Y2fTh83fnk0qo%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADBWV7KBI4IMF3SEGTXG5FTW4PBMHANCNFSM6AAAAAAV56THUY&data=05%7C01%7C%7C2be2541aa886499a085508db268c4b1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146156212376035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=claF9mx3v5f9DOupjRiqYR2Dl2Ea8qh7ioLz29Jsn9A%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

That did it, but had to reinstall an old version first.

TY

**Comment by rys322** [comment]
I can’t get control panel to open, any suggestions?

**Comment by meemore** [comment]
this is what you do

press CTRL ALT Del
click on RUN new TASK
type in the word  CONTROL
Click on PROGRAMS and FEATURES
Find explorer patcher and uninstall it
once its done uninstalling
reboot the PC

**Comment by meemore** [comment]
Also,

press CTRL ALT Del
click on Task Manager
look for explorer.exe
right click and click END Task

your simply stuck in a loop

**Comment by zEdS15B3GCwq** [comment]
The above process works well for stopping explorer.exe. Uninstallation is, however, not always successful.

With the recent update of my laptop to 22621.1413, I also was stuck in a restart loop, which I successfully broke out of doing the same. Then I was not able to uninstall explorer patcher, due to "some files still being used, restarting your computer should fix that" or some error like that. Sorry, I didn't write down the exact error message. The main point is, that both `control panel/programs uninstall` and running `ep_setup.exe /uninstall` failed. Restarting or logging out and in again just started the same restart cycle, so that didn't help at all. In the end, I had to `rename explorer.exe` in the windows folder, restarted, logged in, and only then I was able to uninstall.

I think it would be nice to have a failsafe keyboard shortcut, or something similar, to prevent explorer patcher from loading on login. That would make all such restart loops and failed uninstalls easier to handle.

**Comment by zEdS15B3GCwq** [comment]
it would be nice to have a pinned discussion topic about how to fix critical problems such as this issue

**Comment by CthRio** [comment]
This problem may be an incompatibility caused by installing other optimization software. I have encountered similar situations before.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月17日(星期五) 中午12:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [valinet/ExplorerPatcher] Explorer.exe caught in restart loop (Issue #1089)





 
it would be nice to have a pinned discussion topic about how to fix critical problems such as this issue

**Comment by acies** [comment]
1. CTRL+ALT+DEL
2. Run task `cmd` (you might need admin privileges for this)
3. `taskkill /IM explorerer.exe /F`
4. `cd` into the installation folder (e.g. `Program Files/ExplorerPatcher`)
5. `dir` and see if you have `ep_setup.exe` or `.prev`, rename it to `ep_uninstall.exe` and run it

**Comment by Legacy279** [comment]
I don't understand what cd to EP's dir mean
