### ISSUE TITLE
Windows 11 22H2, Build 22621.1413 (March 2023) Update - Compatibility Issues

### ISSUE THREAD

**Issue by DavidBerdik** [valinet/ExplorerPatcher#1093]
The following are a list of issues that I am aware of with ExplorerPatcher after updating to 22621.1413.

- When using the Windows 10 taskbar, the "Task View" button does not work. Clicking on it does not do anything. I am not sure if this issue occurs when using the Windows 11 taskbar.
- Using the `Windows + W` keyboard shortcut to access the widgets does not do anything.
- Using keyboard functionality to adjust volume does not show the volume flyout. The volume adjustment does work properly, but the UI component for it does not show.
- `Alt + Tab` functionality appears to arbitrarily break. I am not sure if this makes a difference, but I use the Windows 10 window switcher style.
- `Windows + Tab` to access the virtual desktop display does not do anything.
- The Windows 11-style calendar flyout is not aligned properly to be above the task bar. Instead, it sits on top of it. This issue also is present with the Windows 11-style Control Center flyout as well as toast notifications.
![image](https://user-images.githubusercontent.com/7663225/225819435-04f8c55b-91ba-4d27-b169-6e2007716958.png)

These are the only issues that I am aware of. If any additional information would be useful for debugging, I am happy to provide it.

My ExplorerPatcher version is 22621.1344.53.1.

**Comment by igiona** [comment]
I had the same issue as well, I uninstalled (rebooted) and re-installed the patcher. After having received a notification "latest symbols have been downloaded" the patcher tarted to work again.
I'm also using the W10 style.

**Comment by perbauer** [comment]
I also uninstalled and re-installed but problem was not gone. Does the uninstall perhaps leave some regkeys, files or folders behind? Files that need to be manually deleted before a re-installation?

**Comment by noobj2** [comment]
I have the same issue after updating to 22621.1413.
un-installing and re-installing explorer patcher didn't fix it either.
Alt + Tab and Windows + Tab don't work and make windows explorer crash.
Right clicking on taskbar also makes windows explorer crash.

**Comment by inphra** [comment]
> I had the same issue as well, I uninstalled (rebooted) and re-installed the patcher. After having received a notification "latest symbols have been downloaded" the patcher tarted to work again. I'm also using the W10 style.

I'm on the latest update with Windows 11 and I too am having the issue where ALT+TAB / ALT+WIN no longer work.  I tried uninstalling and reinstalling, but no joy.    Outside it LOOKING and generally behaving the same as windows 10, this critical functionality does not work.   Are you able to use this function?

**Comment by CthRio** [comment]
In version 22621.1413, Microsoft officially announced the results of the last A/B experiment on optimizing the taskbar feature code, which is essentially aimed at fixing the UI display abnormality caused by the automatic hiding of the taskbar function on tablets. Due to the complete changes in the part of the taskbar UI in the UWP framework adopted by Explorer, all taskbar transparency beautification software, including Explorer Pacher, is now invalid. "I believe that in the future, our software developers will be able to synchronously fix this issue. This is not a problem in itself, it's just that Microsoft has changed the code."

**Comment by CthRio** [comment]
In version 22621.1413, Microsoft officially announced the results of the last A/B experiment on optimizing the taskbar feature code, which is essentially aimed at fixing the UI display abnormality caused by the automatic hiding of the taskbar function on tablets. Due to the complete changes in the part of the taskbar UI in the UWP framework adopted by Explorer, all taskbar transparency beautification software, including Explorer Pacher, is now invalid. "I believe that in the future, our software developers will be able to synchronously fix this issue. This is not a problem in itself, it's just that Microsoft has changed the code."




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月17日(星期五) 下午3:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [valinet/ExplorerPatcher] Windows 11 22H2, Build 22621.1413 (March 2023) Update - Compatibility Issues (Issue #1093)





  
I had the same issue as well, I uninstalled (rebooted) and re-installed the patcher. After having received a notification "latest symbols have been downloaded" the patcher tarted to work again. I'm also using the W10 style.
  
I'm on the latest update with Windows 11 and I too am having the issue where ALT+TAB / ALT+WIN no longer work.  I tried uninstalling and reinstalling, but no joy.    Outside it LOOKING and generally behaving the same as windows 10, this critical functionality does not work.   Are you able to use this function?

**Comment by CthRio** [comment]
In version 22621.1413, Microsoft officially announced the results of the last A/B experiment on optimizing the taskbar feature code, which is essentially aimed at fixing the UI display abnormality caused by the automatic hiding of the taskbar function on tablets. Due to the complete changes in the part of the taskbar UI in the UWP framework adopted by Explorer, all taskbar transparency beautification software, including Explorer Pacher, is now invalid. "I believe that in the future, our software developers will be able to synchronously fix this issue. This is not a problem in itself, it's just that Microsoft has changed the code."




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月17日(星期五) 下午2:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [valinet/ExplorerPatcher] Windows 11 22H2, Build 22621.1413 (March 2023) Update - Compatibility Issues (Issue #1093)





 
I had the same issue as well, I uninstalled (rebooted) and re-installed the patcher. After having received a notification "latest symbols have been downloaded" the patcher tarted to work again.
 I'm also using the W10 style.

**Comment by CthRio** [comment]
In version 22621.1413, Microsoft officially announced the results of the last A/B experiment on optimizing the taskbar feature code, which is essentially aimed at fixing the UI display abnormality caused by the automatic hiding of the taskbar function on tablets. Due to the complete changes in the part of the taskbar UI in the UWP framework adopted by Explorer, all taskbar transparency beautification software, including Explorer Pacher, is now invalid. "I believe that in the future, our software developers will be able to synchronously fix this issue. This is not a problem in itself, it's just that Microsoft has changed the code."




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2023年3月17日(星期五) 中午1:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [valinet/ExplorerPatcher] Windows 11 22H2, Build 22621.1413 (March 2023) Update - Compatibility Issues (Issue #1093)





 
The following are a list of issues that I am aware of with ExplorerPatcher after updating to 22621.1413.
  
When using the Windows 10 taskbar, the "Task View" button does not work. Clicking on it does not do anything. I am not sure if this issue occurs when using the Windows 11 taskbar.
 
Using the Windows + W keyboard shortcut to access the widgets does not do anything.
 
Alt + Tab functionality appears to arbitrarily break. I am not sure if this makes a difference, but I use the Windows 10 window switcher style.
 
Windows + Tab to access the virtual desktop display does not do anything.
 
The Windows 11-style calendar flyout is not aligned properly to be above the task bar. Instead, it sits on top of it. This issue also is present with the Windows 11-style Control Center flyout as well as toast notifications.
 
  
These are the only issues that I am aware of. If any additional information would be useful for debugging, I am happy to provide it.

**Comment by KochFolie** [comment]
Also, the volume indicator doesn't show up, when adjusting the volume with hardware buttons / wheel on my keyboard, using mostly Win10 UI.

**Comment by billzhangtao** [comment]
> 

same same~ changed back to win11 taskbar for the moment ^_^

**Comment by jcb83** [comment]
After the Windows update to 22621.1413, my `explorer.exe` kept crashing whenever I moved a window around (by grabbing its title bar and dragging it with the mouse).

The event viewer showed an "Application Error" in explorer.exe with the exception code `0xc0000409` (`STATUS_STACK_BUFFER_OVERRUN`) in `ntdll.dll` and a "Windows Error Reporting" report with the "Event Name" `BEX64` (which might have something to do with the Data Execution Prevention (DEP) feature of Windows).

After de-installing the ExplorerPatcher I can use Windows normally again. I use mostly Windows 10 styling on the taskbar, if that helps somehow. I have NOT tried re-installing EP, nor did I try to use EP with a Windows 11-style taskbar (I will try both after I am done with work for the day).

**Comment by Gendmyb** [comment]
After the Windows update to 22621.1413,The software downloaded from the Microsoft Store in the Start Menu, including the Microsoft Store itself, cannot be displayed or added manually

**Comment by CthRio** [comment]
might be that https://github.com/valinet/ExplorerPatcher/issues/1095 is what happened...
For a more detailed explanation, you can look at these:
1.https://github.com/valinet/ExplorerPatcher/discussions/1087#discussioncomment-5343845
2.https://github.com/valinet/ExplorerPatcher/discussions/1087#discussioncomment-5344021

**Comment by CivilizationAce** [comment]
Typing no longer works after clicking the start button. It just jumps to the next item starting with the very last key pressed. To me this seems like a worse bug than all the others. It means I can't even find task view (or anything) to run it directly.

**Comment by CivilizationAce** [comment]
Also the task view button does not work.

**Comment by CthRio** [comment]
> Also the task view button does not work.

Try this method and see if it works.

**Comment by CivilizationAce** [comment]
I had to uninstall. Far too much is broken since the latest windows patch. I only wanted my toolbar visible and wide app buttons on the taskbar. Now I just don't trust ExplorerPatcher anymore. The search feature still doesn't work. Maybe the latest Windows patch itself broke that though, so I may reconsider.

**Comment by Iuwantor** [comment]
After Windows update I just got a straight up blackscreen without explorer.exe
Had to do sys restore and uninstall ExplorerPatcher for the Windows update to work properly.

**Comment by Avnsx** [comment]
fix when

**Comment by valinet** [comment]
Latest version [22621.1413.54.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1413.54.1_8b5443d) addresses this issue.
