### ISSUE TITLE
切换到win10开始菜单微软商店下载的应用不显示，也无法添加到开始菜单。

### ISSUE THREAD

**Issue by ze47** [valinet/ExplorerPatcher#1095]
22621.1344.53.1
版本

**Comment by CthRio** [comment]
In version 22621.1413, Microsoft officially announced the results of the last A/B experiment on optimizing the taskbar feature code, which is essentially aimed at fixing the UI display abnormality caused by the automatic hiding of the taskbar function on tablets. Due to the complete changes in the part of the taskbar UI in the UWP framework adopted by Explorer, all taskbar transparency beautification software, including Explorer Pacher, is now invalid. "I believe that in the future, our software developers will be able to synchronously fix this issue. This is not a problem in itself, it's just that Microsoft has changed the code."
在22621.1413版本中，微软正式公布了上次任务栏特性代码优化的A/B实验的结果，其本质上是为了修复平板电脑自动隐藏任务栏功能导致的UI显示异常的问题，由于资源管理器采用的UWP框架中任务栏UI的部分完全发生了变化，所以现在包括ExplorerPacher在内的所有任务栏透明度美化软件都是失效的。相信未来我们的软件开发者能够同步修复该问题，这本身并不是什么问题，只是微软更改代码导致的向后兼容性问题。如果你们实在等不及可以尝试ViVeTool来关闭本次微软在任务栏上优化的内容。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月17日(星期五) 下午3:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [valinet/ExplorerPatcher] 切换到win10开始菜单微软商店下载的应用不显示，也无法添加到开始菜单。 (Issue #1095)





 
22621.1344.53.1
 版本

**Comment by valinet** [comment]
Issues have to be written in English only.
