### ISSUE TITLE
Task View no longer working with most recent update

### ISSUE THREAD

**Issue by brx6995** [valinet/ExplorerPatcher#1098]
The most recent update to explorer patcher has left the task view button unusable in my windows 10 style docker. It wont open task view at all. Even when I use my built in mouse shortcut.

**Comment by brx6995** [comment]
@Leokuma I tried that, it didn't fix my issue.

**Comment by Leokuma** [comment]
@brx6995 Have you tried this solution? https://github.com/valinet/ExplorerPatcher/discussions/1087#discussioncomment-5346671. Don't forget to reboot Windows.

**Comment by firehawkx** [comment]
After this morning update, explorer.exe kept crashing and restarting (flicking) non stop and the computer was pretty much unusable. I was able to enter task manager with "ctrl+shift+esc", then get into computer management to find out explorer.exe was crashing because of windowsudk.shellcommon.dll...

I then went into add/remove programs with a command line... and removed both open-shell and this mod, and explorer.exe immediately started working again. ugly, but working ;)

I doubt this info is useful, i tried checking that other thread, but its a bit too high level for me...
Here is the log from the event viewer of the thousands of crashes i had :

Faulting application name: explorer.exe, version: 10.0.22621.1344, time stamp: 0x7e4082a9
Faulting module name: windowsudk.shellcommon.dll, version: 10.0.22621.1344, time stamp: 0x6538f553
Exception code: 0xc0000005
Fault offset: 0x000000000025bbb0
Faulting process id: 0x0x27AC
Faulting application start time: 0x0x1D9591D184190BF
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\windowsudk.shellcommon.dll
Report Id: 8ed71149-f09c-47db-b290-ee3fefceecba
Faulting package full name: 
Faulting package-relative application ID:

**Comment by valinet** [comment]
Latest version [22621.1413.54.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1413.54.1_8b5443d) addresses this issue.

**Comment by pauljackman2023** [comment]
Hi,
Taskview has stopped working after windows update 10/08/2023, Have tried the workarounds, it starts working again if you put the taskbar in windows 11 mode, however I like my windows 10 with ungrouped and labelled apps.

Edition	Windows 11 Home
Version	22H2
Installed on	‎21/‎09/‎2022
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

**Comment by pyrates999** [comment]
> Hi, Taskview has stopped working after windows update 10/08/2023, Have tried the workarounds, it starts working again if you put the taskbar in windows 11 mode, however I like my windows 10 with ungrouped and labelled apps.
> 
> Edition Windows 11 Home Version 22H2 Installed on ‎21/‎09/‎2022 OS build 22621.2134 Experience Windows Feature Experience Pack 1000.22659.1000.0

Please open up a new issue.
