### ISSUE TITLE
Flickering after new windows update

### ISSUE THREAD

**Issue by IraeVid** [valinet/ExplorerPatcher#1126]
Windows 11 just had a new update and when I open the computer, the screen keeps flickering white. I can't do anything

**Comment by HajoBB** [comment]
Hello, yes I had the same. The "flickering" was caused by the EXPLORER crashing and restarting in a loop.

Press CTRL+ALT+DEL
Open the Task Manager
Use the RUN button to run CMD as Administrator
Execute this in CMD: taskkill /f /im explorer.exe

Now your system is quiet first of all.

Now still in CMD, run this command: appwiz.cpl
It opens Programs and Apps

From here, uninstall the Explorer Patcher

It should automatically start the explorer and taskbar.

After that, I just RE-INSTALLED the Explorer Patcher and it did not cause the loop anymore.

Additionally, a new version of Explorer Patcher was released today.
