### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by senolfndk** [valinet/ExplorerPatcher#1155]
can you add turkish language in app

**Comment by Amrsatrio** [comment]
I've added support for localization in a recent EP prerelease update. If you want EP in Turkish, then you can either help us by translating yourself and making a PR here: https://github.com/valinet/ExplorerPatcher-L10N, or wait until someone else contributes Turkish translations there.

Closing since this is a feature request.

**Comment by senolfndk** [comment]
> Yakın zamanda yayınlanan bir EP yayın öncesi güncellemesinde yerelleştirme desteği ekledim. EP'nin Türkçe olmasını istiyorsanız, https://github.com/valinet/ExplorerPatcher-L10N adresinden kendiniz çevirip PR yaparak bize yardımcı olabilir veya başka birisinin orada Türkçe çevirilerle katkıda bulunmasını bekleyebilirsiniz.
> 
> Bu bir özellik isteği olduğu için kapatıyoruz.

I'm not an expert on this subject
