### ISSUE TITLE
Start menu no longer registers key strokes?

### ISSUE THREAD

**Issue by jdredd87** [valinet/ExplorerPatcher#1188]
Started maybe A week or two ago? Been using ExplorerPatcher not long after it first came out. 

v22621.1413.54.5

Basically bring up start menu, and can't type in anything to find stuff quickly.

Like if I wanted to get to control panel, i'd press ctrl-esc to bring up the start menu and type control.

No key strokes are registering. Just have to mouse scroll to find what I need now.

![460064fdf8845503eb0baa7062bb4b99](https://user-images.githubusercontent.com/16713473/227408341-be7f8a0c-99df-44ba-90af-e408ad270bf0.png)

**Comment by Falcordog** [comment]
> Search missing is a really big issue I think.


Same here...
Often the start menu doesn't launch at all, yet interestingly enough if you right click it and use the search function from there it works just fine.
In any case the Windows Indexing Service is such a PoS that should've been laid to rest right around Win7 SP2.
I've been using [Fluent Search](https://github.com/adirh3/Fluent-Search) with [Everything](https://www.voidtools.com/) as its backend indexer. Very powerful pair coupled together and the depth of functionality that Fluent Search offers puts the Windows Start Menu to shame...
I even get Everything to index my NAS drives - which it does easily and uses a fraction of the resources Windows uses to index local fast SSDs - not including system directories...

**Comment by grongor** [comment]
I have the same issue (same version; v22621.1413.54.5).

**Comment by Falcordog** [comment]
> Same thing occurred after I updated yesterday but it fixed itself after reboot ¯_(ツ)_/¯

This behaviour appears to be directly related to the the search indexer status.
While the indexer is busy... well... actively indexing, the start menu becomes unresponsive, either not registering keystrokes or not launching at all.
Once indexing is complete functionality is restored.
I narrowed down the directories to be indexed to bare minimum in order to avoid this and use search and indexing solutions mentioned in my previous post for doing the heavy lifting.
Should be noted that I'm using A Win11 Insider Build Preview build (25309.1000) so this may not be applicable to other scenarios.

**Comment by coldimmune** [comment]
> 

Hmm, I checked this and even when "Indexing Complete" is showing I can't search in the start menu. I tried rebuilding the index, no change. Restarting "Windows Search" service, same thing

I'm having to WIN+R to launch applications :\

**Comment by Falcordog** [comment]
> I'm having to WIN+R to launch applications 


Do try the [Fluent Search](https://github.com/adirh3/Fluent-Search) with [Everything](https://www.voidtools.com/) solution I mentioned earlier....
You might be pleasantly surprised :)
You can also try giving Fluent Search a quick test run using its own indexer (without installing Everything too).
It can act as a start menu alternative of sorts but much much more...
I personally integrate both because I find Everything's indexing performance to be superior and use its extra features such as effective and low resource SMB indexing on a daily basis.
I experimented with remapping Winkey to launch Fluent Search instead of start menu but that caused too much trouble with other key shortcuts so instead I now use double tap left ctrl key which works like a charm as well as a taskbar icon right next to that of the start menu.

**Comment by jdredd87** [comment]
I uninstalled Explorerpatcher to do some tests.

Noticed, I can't even type in the "Type here to search" here either.

Guessing some windows update might have goofed things up?

![image](https://user-images.githubusercontent.com/16713473/229834754-58e6640d-11cb-4828-bf8b-5bc4d7fc1119.png)

**Comment by Poopooracoocoo** [comment]
Cannot repro
