### ISSUE TITLE
What about localization ?

### ISSUE THREAD

**Issue by Riki7745** [valinet/ExplorerPatcher#1189]
I would like to translate in my own language (French). Could you do something to enable translation ? Thanx.

**Comment by creeper-0910** [comment]
The current EP text can be found in "ExplorerPatcher/settings.reg" or in the program code.
The easiest way is to fork this repository and release the translations yourself.

**Comment by Amrsatrio** [comment]
<img width="491" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/aa81cbed-c2ab-4b6b-8b22-7cef16923f59">

Coming soon next month. (I hope)

**Comment by Amrsatrio** [comment]
I've added support for localization in a recent EP prerelease update. If you want EP in French, then you can either help us by translating yourself and making a PR here: https://github.com/valinet/ExplorerPatcher-L10N, or wait until someone else contributes French translations there.

Closing since this is a feature request.

**Comment by rd1** [comment]
I have a weird translation in French, the English text says "Clear" which in French is "Éclaircies" in the weather context but instead gets translated to "Effacer" which literally means Erase.

Maybe the translator needs context to work right.
