### ISSUE TITLE
How to show time or other quick action icons?

### ISSUE THREAD

**Issue by ErickWei** [valinet/ExplorerPatcher#12]
I found many many settings but no this.
How about to show it by default?
![snipaste_20210902_110619](https://user-images.githubusercontent.com/62826892/131775254-5866014a-166e-4806-9a70-a473a926da0b.png)

**Comment by ErickWei** [comment]
Ok, I found this shell command

shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9}

**Comment by valinet** [comment]
Please read the README file, it is mentioned there already: just open `Run` and then type `%windir%\explorer.exe shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9}\SystemIcons` and in the window that opens, pick the icons that you want to see in the system tray.

**Comment by valinet** [comment]
By default you mean when switching from 11 taskbar to the classic one? Kind of hard to do because the new taskbar always resets those, so that those do not show in the new taskbar, plus, every user may prefer some but not all the icons, so what should be the default then, the whole set? I don’t know, maybe, if there is an easy registry tweak that shows them, I can have the patcher merge that automatically, sure. Do you know where the information about those system icons is stored in the registry?
