### ISSUE TITLE
Incompatibility with 22000.282

### ISSUE THREAD

**Issue by petrechitashvili** [valinet/ExplorerPatcher#129]
I downloaded the [latest `dxgi.dll` (ver. 22000.258.30.4)](https://github.com/valinet/ExplorerPatcher/releases/download/22000.258.30/dxgi.dll), pasted to `C:\Windows`, restarted Windows Explorer, rebooted the computer, nothing seems to have happened.

`%appdata%\ExplorerPatcher` has a single file in it - `twinui.pcshell.pdb`
![image](https://user-images.githubusercontent.com/15320885/137580342-58069367-049e-4f3e-bf48-271647755ee4.png)

My Win11 build is `22000.282`, Edition - Windows 11 Pro

**Comment by marcoh242** [comment]
Same for me. Probably this itisn't working yet with 22000.282

**Comment by BraINstinct0** [comment]
Strange behavior here.

**Comment by BraINstinct0** [comment]
The full 'fix' list is [here](https://blogs.windows.com/windows-insider/2021/10/15/releasing-windows-11-build-22000-282-to-beta-and-release-preview-channels/).

One thing interesting is the second line noted there:
"We fixed an issue for a small number of users that prevents the Start menu from working and prevents you from seeing the updated taskbar design after upgrading to Windows 11 (original release).".

Other lines, though seems to be irrelevant, but includes 'explorer.exe' or 'start menu' are as below:
- We fixed a paged pool memory leak of the registry keys for the Virtual Desktop ID that occurs in explorer.exe.

**Comment by BraINstinct0** [comment]
> Installed on 22000.258 before updating and worked fine. Updated to .282 = all gone. Back to Start11. Looking forward to an update for .282!

Can confirm this is happening on my machine, too.

**Comment by valinet** [comment]
Microsoft hasn't yet made available the symbol files for `twinui.pcshell.dll` from build 22000.282. In an ideal world, we wouldn't need those. But for the moment, symbol files are still used to determine where to hook some stuff (`Win`+`X` and the Start menu). Once this address serves you a file: http://msdl.microsoft.com/download/symbols/twinui.pcshell.pdb/73402D8892AF2DA2639F29A5D2F483911/twinui.pcshell.pdb, it will probably start working.

**Comment by Anix-x** [comment]
Maybe allow to work with functions that do not depend on that database? I mean, what if MS stops releasing those databases, etc?

**Comment by valinet** [comment]
Symbol files are usually made available for any build. They are still available for Windows Vista I believe, if not earlier. This hasn't been a problem until today, right?

Working without some functionality is basically the same thing, people will still start complaining that stuff is not working, and you have to ask them an additional question, to figure out whether it is a bug with that functionality, or simply because it could not be hooked for whatever reason.

Also, suppose not releasing symbols becomes a regular thing, than this sort of patcher also becomes exponentially harder to develop. Looking through the system files is way more difficult without symbols... it would make a lot of this practically impossible... even if you do not end up hooking functions directly, but patching the IAT table, you still need to look on the disassembly to figure how things work, which is very difficult without augmenting that with information from the symbol files.

As I said multiple times now, this is an educational project. I am more interested in researching new stuff, discovering how things work etc rather than spending each and every day implementing mitigations and fixes and workarounds for the millionth niche case out there. It's starting to turn into that and I don't enjoy it at all. The solution here is to generally wait a bit for the files to be available, if we need to be on a build newer than what I tested this on anyways, and also sit down for a bit and devise a feasible plan for improving this situation.

For example, hooking Start could be kind of avoided for the tweak "max number of most used apps". We could just patch the instructions by pattern, as it is a unique `B8 06 00 00 00 C3` (`mov eax, 6; ret`) and likely to stay that way. For the other "show app list when opening", I don't have an immediate idea: there I hook the `VisibilityChanged` callback of Start and trigger the `ShowAllApps` function. For Explorer, reimplementing the code that builds the `Win`+`X` menu is one thing, and then reimplementing the code that skins the pop-up menus another thing. And then making the code use the our menu provider instead of the original one. That gets rid of needing symbols there as well. Another idea would be to load some older version of `twinui.pcshell.dll`, one for which we know the offsets in advance, and use the functionality from there, this avoids having to spend time rewriting something that's already basically in there. But then comes the problem, how do you distribute that file to users, as we are not allowed to do that... there are multiple avenues, an entire discussion to have etc. Much more complicated than it seems on the surface. Also, I explained above how StartAllBack manages to still work. They went with the option to reimplement whatever they needed and couldn't be hooked more "safely" let's say (IAT hooks are not dependent on symbols, like regular hooks, to actually do something useful)... I was hoping that I could have the talk on these forums as well, but it seems to draw no interest from people knowledgeable in these areas... I don't know a definite, "best solution" answer for every question out there; some things are implemented a certain way because that's how i thought at that time would be best, maybe did not have the knowledge that I have now, maybe did not have the time or maybe the energy to invest in a better but more complicated/complex solution etc. Also, I guess probably all developers are on Linux or macOS, I mean, people are kind of tired of wasting their days in Microsoft's land, just to get a centered taskbar and a hardcoded menu.

**Comment by valinet** [comment]
Yeah, I won't spend any more time in implementing workarounds for symbols missing, not being available etc. Better is to do something more constructive, like get rid of the need for them.

The immediate solution for any 'need' is to fork the project, take out the functionality you don't want, and compile for your particular use case. I don't want to spend the energy to upstream the changes that allows this to work without the functionality that depends on the symbols. I'd rather fix the original nuisance in the first place, and get rid of the need for symbols. Is there an emergency, is compatibility with 282 required in 3 hours otherwise the Earth goes flat? I suppose no. Then I'd rather work on a proper solution. The code is always available, one can compile whatever version they want with whatever subset of functionality they want. The upstream does not have to support every niche case. For that, just fork the project and maintain your own version... simple.

Again, I am making a call for having a conversation on the technical side, on how to fix this properly...

**Comment by BraINstinct0** [comment]
The server seems tobe documented [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/microsoft-public-symbols). Gotta hit their mailbox if they're aware of the missing symbol files?

**Comment by valinet** [comment]
Try that, why not? It's the first time this happened from my experience.

**Comment by BraINstinct0** [comment]
No reply yet, will update if anything notable happens

**Comment by tesivo** [comment]
> After installing the tool, moving the taskbar to the left, updating windows, the tool doesn't work anymore. How can I uninstall it since it is not possible to move the taskbar back to the bottom while the tool is not working? Renaming it to dxgio.dll didn't work.

I solved it by uninstalling update "KB5006746" and reverting back to the previous version. 
At this point you can choose to stop the updates (for a week or via this tool [wushowhide.diagcab](https://download.microsoft.com/download/f/2/2/f22d5fdb-59cd-4275-8c95-1be17bf70b21/wushowhide.diagcab) ) or restore ExplorerPatcher to its default settings, remove it and update windows 11.

**Comment by BraINstinct0** [comment]
No reply from MS yet.
For me, two(or three) possibilities come to mind.
1) MS just forgot to upload it - it'll be handled if enough complaint is received.
2) MS will not upload it. However, we'll get to see what it'd be like when the next update is rolled out.
3) Someone desperate(?) enough forks, patches, and builds ExplorerPatcher(as valinet mentioned).

**Comment by valinet** [comment]
Do Win+X or Start injection work?

**Comment by deep0d0** [comment]
Is there a way to open ExplorerPatcher GUI manually, like through filepath?
I have Startallback installed, but disabled completely. But it is still
hooked in the Properties Button.

Trying to verify that ExplorerPatcher is working and installed. Could be
wrong potentially

**Comment by valinet** [comment]
rundll32.exe C:\Windows\dxgi.dll,ZZGUI

Valentin-Gabriel Radu

**Comment by deep0d0** [comment]
Also message that symbols are downloading does keep showing up, but I assume it has nothing to download so it would not work.

**Comment by thuyhoangnet** [comment]
I only need the "never Combine" function on the taskbar and it's ok.
Thank you so much for this meaningful project!

**Comment by mrplow** [comment]
I just got hit by this as well. All love to the devs. Thanks for the great responses.

I noticed that the Win keyboard button on the keyboard still opens Open-Shell Start menu, that works for me for now :)

**Comment by valinet** [comment]
@ALL Can you test this version, please? If it works, I will add it to releases. Thanks.
[dxgi.zip](https://github.com/valinet/ExplorerPatcher/files/7393737/dxgi.zip)

**Comment by ExorcistF1** [comment]
seems works normal, and microsoft added twinui.pcshell.dll file
