### ISSUE TITLE
Windows search corrupted after installing new update

### ISSUE THREAD

**Issue by iJahangard** [valinet/ExplorerPatcher#1336]
I updated EP today ,after that i wasn't able to open windows search in any method, not win key then typing, not win+S hotkey

I uninstalled ep ,but the problem wouldn't solved

**Comment by JiggsNephron** [comment]
I have the same issue. Start Menu search doesn't work any more.

**Comment by wgy855** [comment]
Same here. The problem happenned after windows 11 updating to 22H2。The problem was solved after I taking following actions. First, uninstall ExplorerPatcher and restart computer, a windows setting windows pops up, do whatever you like (I choose "remind me later"), you can find that the start menu turns back to Windows 11 original style and the search function is working properly. Then reinstall ExplorerPatcher, problem solved.

**Comment by JiggsNephron** [comment]
Uninstalling didnt fix it for me.

**Comment by JiggsNephron** [comment]
Restarting after uninstall did the trick! Can't believe I didn't try that. Thanks.

**Comment by kyle0k** [comment]
This fixed the issue for me too. Big thanks!

**Comment by iJahangard** [comment]
> Restarting after uninstall did the trick! Can't believe I didn't try that. Thanks.

I restartes me PC but it got worked after i did it more than 5 times
