### ISSUE TITLE
Explorer patcher crashing on clicking the taskbar

### ISSUE THREAD

**Issue by Faulty-Windows** [valinet/ExplorerPatcher#1387]
For whatever reason, i'm on the same build as the latest build, so I wanted to install explorerpatcher, but when I Installed it, the Windows 11 taskbar came up. I thought i had to change through configuration, but when i tried to right click, it crashed explorerpatcher. This happened until it told me that something WAS wrong and you needed to open a new issue. Apparently, I don't know if it's caused by my antivirus (Mcafee or Windows Defender) but it was working all fine on the 22621.1413 build. I don't know what's happening with this.

**Comment by Willgefortz** [comment]
Same here. After update KB5025305

**Comment by realGigachad** [comment]
Got the same issue, reset to default settings, uninstalled and then reinstalled it, that seems to have worked for me.

**Comment by Faulty-Windows** [comment]
> Got the same issue, reset to default settings, uninstalled, rebooted, and then reinstalled, that seems to have worked for me.
> 
> edit: I also had TaskbarX installed which I uninstalled via the TaskbarX Configurator and then ran it again after installing explorer patcher again

doesn't seem to help

**Comment by matrixsh1t** [comment]
does not help me too

**Comment by amokkatgithub** [comment]
For me Explorer was crashing when r-clicking the taskbar, not Patcher. In my case "Taskbar style" Patcher setting was "Windows 10". I changed it to Windows 11, restarted explorer, then changed back to "Windows 11", restarted again, and issue is gone.

**Comment by Faulty-Windows** [comment]
> Resetting the explorer patcher to default settings and then setting it up again helps. Thank you!

how to do that?

**Comment by Faulty-Windows** [comment]
i can't access the start menu, nor the right click menu

**Comment by amokkatgithub** [comment]
> i can't access the start menu, nor the right click menu

run
`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

**Comment by matrixsh1t** [comment]
> > Resetting the explorer patcher to default settings and then setting it up again helps. Thank you!
> 
> how to do that?

my steps were like follows:
As windows suggested update, I uninstalled the patcher. Installed the windows update and then installed the patcher. it did not work and reset all the time. so i reinstalled it several times. windows button could not be clicked, but right click on any other place could get the menu for patcher properties. So reset to default settings and restarted the explorer. it worked, then i tunned the patcher again.

**Comment by sioumiku** [comment]
I have the same problem, My solution is turn off "System tray -> Skin taskbar and tray pop-up menus".
But I still have a problem that has not been solved. If I am typing with Chinese input method, the windows file explorer crashes. If anyone knows how to fix it, please tell me.
Verson: 22621.1555.

**Comment by packetdog** [comment]
> For me Explorer was crashing when r-clicking the taskbar, not Patcher. In my case "Taskbar style" Patcher setting was "Windows 10". I changed it to Windows 11, restarted explorer, then changed back to "Windows 11", restarted again, and issue is gone.

I had this issue too. I was trying to right-click to eject a USB drive after the latest 'feature update' for Win 11 22H2, and it would crash explorer. Following your steps right within Explorer Patcher corrected this issue for me. I think at the end you intended to write "changed back to "Windows 10"" but I got it, it worked. Thanks for the steps!

**Comment by c0ldk453** [comment]
I'm guessing that this is an issue most are having when they change their taskbar style back to Windows 11 since the Windows 10 mode shows labels next to the icons, and it clutters the taskbar.  Ideally, I'd love to see an option that turns off those labels in the future, but thankfully I have a solid workaround for you guys!

For now, just go to the "Advanced" section and disable "Do not change the taskbar context menu" if your taskbar is set to be Windows 11 style in ExplorerPatcher properties - this appears to be the reason the software is consistently crashing when the context menu for the taskbar is brought up.  Windows 11 doesn't seem to like adding new entries to its context menu for its taskbar.

To reach the ExplorerPatcher properties menu in the future instead of through the taskbar context menu, go to C:\ProgramData\Microsoft\Windows\Start Menu\Programs\ExplorerPatcher and open "Properties (ExplorerPatcher)" to get to ExplorerPatcher properties.  You can make a shortcut to the ExplorerPatcher Properties from there that you can link to your taskbar if you so choose.  

You can also use Classic Shell's Classic Start Menu (if you use that) to get there easier - go to Start>Programs>ExplorerPatcher>Properties (ExplorerPatcher), and you can pin that properties menu to your Classic Shell Start Menu if you so choose, or you can set a run command for middle-clicking (or whatever control you decide) the Start button to open this program in Classic Shell settings>Controls.

This is a temporary workaround, but should work for most folks.  I love using the combo of Classic Shell and ExplorerPatcher for Windows 11 to get back to a more Windows 7/8 feel.

**Comment by pyrates999** [comment]
Classic shell is no longer maintained.  It's been replaced with Open Shell.
