### ISSUE TITLE
System failure

### ISSUE THREAD

**Issue by Whitemanns** [valinet/ExplorerPatcher#1479]
After running the program Explorer Patcher my desktop began to flash what i found out later that launching the program caused windows explorer to crash. When explorer started back up so did the program looping this problem. It took me 15 mins to remove the  Explorer Patcher program with PowerShell. I have no programs running that change my desktop at all.

I do not know if this was a isolated problem.

**Comment by pyrates999** [comment]
What version of windows are you running?  You can find out by running "winver".  Windows with preview updates installed or insider builds are not supported because microsoft does not provide symbols to download for these versions.  Uninstall it if you do are running one of the above.

Continue if you are running a release version of windows with no preview updates installed.

Try the following:

1. Uninstall it: https://github.com/valinet/ExplorerPatcher/wiki#uninstalling
2. Reboot
3. Then install it again.
4. Wait until you get the notification that symbols have been downloaded
5. Open up explorer patcher properties application
6. Click on Restart File Explorer

If that doesn't work:

1. Open up explorer patcher properties application
2. go to About
3. Click on Export Settings and upload it to here.
4. Click on Restore default settings
5. Reboot
6. Wait until you get the notification that symbols have been downloaded
7. Open up explorer patcher properties application
8. Click on Restart File Explorer

**Comment by Whitemanns** [comment]
program caused windows explorer to crash. So getting into the explorer patcher properties application was impossible.
 
 Windows ver. (22H2) (OS Build 22621.1702)

**Comment by pyrates999** [comment]
The explorer patcher properties application is a separate application.

**Comment by Whitemanns** [comment]
This is a fresh install of windows 11 64-bit on a brand-new 980 Evo M.2

**Comment by Whitemanns** [comment]
Everything is up to date. I use Samsung magician to keep the M.2 up to date.
Video card is a 6700 XT newest driver is 4/27/2023.
CPU AMD Ryzen 5800x Chipset Driver 3.10.08.506.
Motherboard Gigabyte x570 Aorus Elite (Rev 1.0) Bios Ver F38b Mar 23, 2023.

**Comment by pyrates999** [comment]
You're running a beta bios.  Any bios version that ends with a letter is beta.  I would try downgrading to F37 here: https://www.gigabyte.com/Motherboard/X570-AORUS-ELITE-rev-10/support

**Comment by Whitemanns** [comment]
MY CPU will not work with the said F37 Bios update it just loads the bios over and over.

**Comment by Wengomaster** [comment]
After windows update (To Win11 22621.1702) I had a very similar issue resulting in a pop-up after windows start. Pop-up told me that explorer crashed 3 times and that I should look for updates or unistall explorer patcher.
After  uninstalling one of the latest Windows updates (KB502637) and rebooting, Explorer-Patcher now works again.
Maybe the problem is related to KB502637?

**Comment by Wengomaster** [comment]
PS:
I have a similar setup:
B550 Aorus Elite V2 FB 
Ryzen 5600
6700 XT still with the windows stock driver.

**Comment by pyrates999** [comment]
Do you mean KB5026372?  That is a service stack update: https://support.microsoft.com/en-gb/topic/may-9-2023-kb5026372-os-build-22621-1702-ce93c18e-e819-458f-abcf-dc7154ce7e40

Please also post the language of your version of windows if it is not the US english version.

**Comment by bathindahelper** [comment]
https://github.com/valinet/ExplorerPatcher/issues/1434https://github.com/valinet/ExplorerPatcher/issues/1434

**Comment by Wengomaster** [comment]
Langauage is German. Yes, I mean KB5026372.
![grafik](https://github.com/valinet/ExplorerPatcher/assets/33395046/2e23279e-6565-482b-b7a0-533528bf52c9)
 Unfortunately it keeps on beeing auto-installed  on my system, although it is also known for many other troubles an MS is working on a fix:
 https://www.windowslatest.com/2023/05/13/windows-11-kb5026372-is-causing-a-wave-of-issues-including-vpn-problems/
