### ISSUE TITLE
Explorer Crashes when toggle hidden files 

### ISSUE THREAD

**Issue by mkvGuy** [valinet/ExplorerPatcher#151]
Faulting application name: explorer.exe, version: 10.0.22000.120, time stamp: 0xe846e749
Faulting module name: dxgi.dll, version: 22000.258.30.4, time stamp: 0x616a3fef
Exception code: 0xc0000005
Fault offset: 0x0000000000009e07
Faulting process id: 0x3458
Faulting application start time: 0x01d7c439a085384b
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\dxgi.dll
Report Id: db007a18-8b7d-45dd-908d-f535dba34027
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mkvGuy** [comment]
everytime.

**Comment by valinet** [comment]
Cannot reproduce on my test version. I will upload it soon. Hopefully it is resolved. otherwise, check for conflicting modules, extensions, use a debugger to trace the cause. AND PLEASE DO NOT OPEN AN ISSUE EVERYDAY. I AM UNDER NO OBLIGATION TO FIX IT ANYWAY. THE PRODUCT IS PROVIDED "AS IS".

Thanks.

**Comment by valinet** [comment]
No worries. Closed threads means the subject is largely discussed and decided on, but the conversation can continue nevertheless.
