### ISSUE TITLE
Win+X "Powershell (Administrator)" is not administrator

### ISSUE THREAD

**Issue by AgFlore** [valinet/ExplorerPatcher#1510]
EP Version: 22621.1555.55.1
OS Build: 22621.1778
Win10-style-taskbar enabled

In the Win+X menu, `Windows Powershell(I)` and `Windows Powershell Administrator (A)` now summons Windows Terminal (instead of the blue ugly powershell window).

`Windows Powershell Administrator (A)` summons an UNELEVATED WinTerminal, which is confusing.

`Terminal (I)` and `Terminal (A)` works fine, summons the winTerminal unelevated and elevated respectively.

![Win_X_menu_layout](https://github.com/valinet/ExplorerPatcher/assets/30150165/dd25e900-cb12-4951-9e44-eb19497d4812)

**Comment by pyrates999** [comment]
You have a preview update installed:

https://support.microsoft.com/en-us/topic/may-24-2023-kb5026446-os-build-22621-1778-preview-3c547100-7a73-4ae6-bb7d-ebd02e87dc04

Please uninstall all preview updates if you want to use explorer patcher due to symbols not being available for preview updates and insider builds:

https://github.com/valinet/ExplorerPatcher/wiki/Symbols
