### ISSUE TITLE
StartAllBack interoperability issue: Widgets button opens Cortana

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [valinet/ExplorerPatcher#158]
With StartAllBack 2.9.95 and ExplorerPatcher 22000.258.30.6 both enabled, the button added by StartAllBack for widgets on the taskbar breaks when EP is also loaded. It turns into a button for Cortana. Even the tooltip for it says "Talk to Cortana" but the icon is for the Widgets. As soon as the latest dxgi.dll is renamed, the Widgets button added by StartAllBack starts opening Widgets again.

For now I have reverted to EP 22000.258.26.3 which was the last version where Widgets button added by StartAllBack worked properly.

**Comment by valinet** [comment]
Yeah, so I looked a bit on how both apps behave together on the latest build. It's kind of expected. Both applications install similar hooks in Explorer. Due to the nature of these hooks, one overwrites what the other does. In conclusion, these are not quite compatible. I won't maintain compatibility with StartAllBack because it takes too much time. I'd recommend using that, and maybe write to its developer about the stuff that you want from ExplorerPatcher that is missing in StartAllBack. He can easily implement them, if wanted, as this application is open source, consulting and ripping off the code is pretty easy.

Thanks.
