### ISSUE TITLE
Windows 11 command bar breaks when startallback is enabled

### ISSUE THREAD

**Issue by ShiroUwUs7** [valinet/ExplorerPatcher#159]
Windows 11 command bar breaks when startallback is enabled with options disabled on both explorer patcher and defaulting on startallback. 

Video of issue.
[https://streamable.com/x5b623](https://streamable.com/x5b623)

Images:  (don't mind the watermarks.)
ExplorerPatcher settings.
![ep7](https://user-images.githubusercontent.com/53096166/137994612-b5715fc4-e455-4951-8b88-83708b2cb534.jpg)
![ep6](https://user-images.githubusercontent.com/53096166/137994614-e937110b-64d7-4f6f-adca-2f5d5745c34d.jpg)
![ep5](https://user-images.githubusercontent.com/53096166/137994615-41bed0c3-b0b3-43ae-9530-94772771e488.jpg)
![ep4](https://user-images.githubusercontent.com/53096166/137994618-5561bc0f-4462-49d8-8189-c4ca943d0749.jpg)
![ep3](https://user-images.githubusercontent.com/53096166/137994619-e1ccfdc6-6091-4660-8c0e-2ca66aec56ed.jpg)
![ep2](https://user-images.githubusercontent.com/53096166/137994620-b3e551c4-e82e-426c-9c63-d7aa978965d1.jpg)
![ep1](https://user-images.githubusercontent.com/53096166/137994622-405d97ec-f25f-4e2e-bab7-ad825ce1ce29.jpg)

startallback settings. 
![5](https://user-images.githubusercontent.com/53096166/137994623-dfa98a88-f396-4e09-8766-0a0da2e081e5.jpg)
![4](https://user-images.githubusercontent.com/53096166/137994624-8d94fd03-e228-4136-9de6-8249f1712d32.jpg)
![3](https://user-images.githubusercontent.com/53096166/137994625-e77b223f-42ac-4b48-bcb2-13fd8c7a907b.jpg)
![2](https://user-images.githubusercontent.com/53096166/137994628-fae970b2-093a-4cdc-8cc5-a20c9778b2b6.jpg)
![1](https://user-images.githubusercontent.com/53096166/137994629-12747355-c5d2-4f81-b89c-fc42dfe7a101.jpg)

**Comment by valinet** [comment]
It's kind of expected. Both applications install similar hooks in Explorer. Due to the nature of these hooks, one overwrites what the other does. In conclusion, these are not quite compatible. I won't maintain compatibility with StartAllBack because it takes too much time. I'd recommend using that, and maybe write to its developer about the stuff that you want from ExplorerPatcher that is missing in StartAllBack. He can easily implement them, if wanted, as this application is open source, consulting and ripping off the code is pretty easy.

Thanks.
