### ISSUE TITLE
win10 start menu doesnt pop up, but it gives me this error

### ISSUE THREAD

**Issue by fr0stlol** [valinet/ExplorerPatcher#1618]
![2023-07-07 17 00 36](https://github.com/valinet/ExplorerPatcher/assets/138889743/f31c7a0a-6b8d-46d9-9ff7-8d5bc7a0898f)
it gives me this error

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by fr0stlol** [comment]
![2023-07-08 10 36 45](https://github.com/valinet/ExplorerPatcher/assets/138889743/98834fab-981e-4670-8a7c-a2f7df980369)
its written in russian but the version is 23H2 and build is 25393.1
![2023-07-08 11 51 09](https://github.com/valinet/ExplorerPatcher/assets/138889743/7235eb1f-299d-4079-a28f-409f5632edad)
i uninstalled explorer patcher bc it wasnt working but i was using latest version

**Comment by pyrates999** [comment]
That's an insider build: https://www.elevenforum.com/t/windows-11-insider-canary-build-25393-1-23h2-june-14.15635/

Don't run insider builds or install preview updates if you want to use explorer patcher because Microsoft does not provider download symbols for them, which explorer patcher needs to function: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Amrsatrio** [comment]
Your build is an Insider Canary build, which is not supported by EP. We would support Dev builds, but not as far as Canary which is yours. Sorry about that. Closing this issue.
