### ISSUE TITLE
(bug) Opening/Closing animations of SM and Serious bug with Win10 WiFi Flyout.

### ISSUE THREAD

**Issue by Vipin2003** [valinet/ExplorerPatcher#1619]
1. There is a bug with the Start Menu opening and closing animation. It doesn't match with the Win10 animation. Instead of that, it just puts the SM on screen without animation. It is also there for Win11 SM too.

https://github.com/valinet/ExplorerPatcher/assets/93650504/dadba1de-a214-497c-b4ce-c174adacd7ed

2. There is a bug with closing animation of every flyout of Win10. It doesn't behave properly like they are in Win10. There is a issue with closing animation with these.

3. **This is serious**. Whenever we open and close WiFi flyout repeatedly, the WiFi flyout got broken and we can't use that flyout. It just shows buttons. To fix that, we have to restart the pc.

**Animations in StartAllBack :**

https://github.com/valinet/ExplorerPatcher/assets/93650504/ebc36bd1-80fd-46eb-bb85-12d734744129

**Animations in EP :**

https://github.com/valinet/ExplorerPatcher/assets/93650504/f2b35bd2-aa93-4db2-9a48-da21d1b4c768

I think that these aminations are ruining the experience of EP. @valinet Please try to fix these before the UWP apps issue. We guys can wait for the UWP fix but pls fix these bugs. especially the Wifi flyout bug.

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by Vipin2003** [comment]
> Please post windows version and build. Please post explorer patcher version.

It is on every build of stable... No specific version.

**Comment by Fabri247Gato10X** [comment]
I have same problem...

**Comment by pyrates999** [comment]
This should be closed due to the author refusing to answer support related questions.

**Comment by Amrsatrio** [comment]
@Vipin2003 I tried to fix the animations so that the Wifi and Battery flyouts are instant. But it will bring back the issue where the Wifi list in the Win11 control center would bug out. Does SAB manage to fix that too?

**Comment by Vipin2003** [comment]
> @Vipin2003 I tried to fix the animations so that the Wifi and Battery flyouts are instant. But it will bring back the issue where the Wifi list in the Win11 control center would bug out. Does SAB manage to fix that too?

Yup... SAB managed it. In SAB, animations are smooth as Win10 have.

**Comment by Amrsatrio** [comment]
I mean, try opening the old wifi flyout and then try opening the wifi menu in the new control center. Does it bug out wish SAB?

**Comment by Vipin2003** [comment]
> I mean, try opening the old wifi flyout and then try opening the wifi menu in the new control center. Does it bug out wish SAB? Of course try this on 22621 builds.

Ya it is bugged out. But it is known to the developer and he is trying to fix this issue. It works bugged until you restart explorer.

https://github.com/valinet/ExplorerPatcher/assets/93650504/47bcbb0f-fbd3-4239-a65c-ee28a49453f6

**Comment by Vipin2003** [comment]
Don't know why smoothness is not shown in video properly.. but you can have an idea about that

**Comment by Amrsatrio** [comment]
@valinet What do you think? Should we trade responsiveness and stability for this?

**Comment by valinet** [comment]
I never understood the need to spam the flyouts, honestly. How often does one realistically go there? Anyway...

> I think that these aminations are ruining the experience of EP.

So every feature this program has is totally cancelled out and nuked just because some fricking 2 animations I don't even understand what the real problem with them is. Again, some comment worth my 2 cents, the attitude... I personally think that a bug that messes up with the layout of !00% of users' menu is far worse than a bug where an animation is slightly glitchy, but the thing works for 99% of the people.

What are the actual problems here? What's there to fix? 

@Amrsatrio What are out options here?

**Comment by Amrsatrio** [comment]
Yeah, I know. It's just people who are so nostalgically attached to Windows 10. They will complain about everything that doesn't match with Windows 10.

So the broken WiFi buttons brought me into this issue. Vipin himself or another people told that deleting dxgi.dll in C:\Windows\SystemApps\StartMenuExperienceHost_blablabla fixes the buttons. So I commented out the GetProductInfo hook in order to fix the buttons because I use it a lot to refresh the WiFi list instead of reopening the flyout (hence the spam).

But then, when you click the control center button when the flyout is open, and then opening the WiFi menu, it'll crash. When the hook is active, doing so will open action center instead which is unexpected from the UX point of view.

So I started isolating the issue, first by commenting out your trick that involves killing SEH. I saw the speed improvements, which makes the flyouts have the same responsiveness as Windows 10 and StartAllBack (as demonstrated in one of the vids above). And that also makes spamming the flyout buttons work without issues. That makes the flyout never get stuck anymore which is annoying when I'm trying to connect to my college's crappy WiFi with captive portal and switch between my phone's mobile hotspot, daily.

When I have more time, my next plans with EP is to find out where the recently-discussed StartMenu.dll is loaded and try to find a solution for this control center WiFi list crashing or making your trick be skipped on the battery flyout of 22621+ which works just fine without side effects.

**Comment by pyrates999** [comment]
I'm testing this on windows 10 and it is also happening there.  It happened after I double clicked on the network icon the system tray 3-4 times.

windows build: 19045.3448
ep version release: 22621.2361.58.1

Once it happens, it no longer shows any wifi access points.  Restarting explorer.exe from the EP properties application fixes it.

**Comment by Amrsatrio** [comment]
Yeah the "trick" shouldn't be applied on Win10 because it just works as it is.

**Comment by pyrates999** [comment]
when it's enabled, what do you mean by your image?

**Comment by Amrsatrio** [comment]
The networks' strength and name do not appear.

**Comment by pyrates999** [comment]
Yes, this also happens in windows 10.  Please try this without EP installed and reboot to see if it is still happening.

**Comment by Amrsatrio** [comment]
I was showing a Windows 11 screenshot. The WiFi flyout works just fine on Windows 10, there's no need to touch Windows 10 at all.

**Comment by Vipin2003** [comment]
I've mase this post in July. It is not mandetory. If it is mandetory, then I will not exclude it from the newly made "Bugs and Suggestion" issue. Ignore this.

But I got a issue with this (don't know Should I add this in that post or not), that after clicking on Wifi flyout for 3-4 times, The wifi flyout got disappeared. It is the issue only in EP. As I've checked it in SAB too. It works fine in SAB.

**Comment by Amrsatrio** [comment]
https://github.com/valinet/ExplorerPatcher/assets/20662640/e6348973-a78c-4cc3-9aea-a124c9c3f8bd

Just need to make this work on builds other than 22621.1992, and then it's ready.

**Comment by Vipin2003** [comment]
> 2023-10-16.185206.mp4 
> Just need to make this work on builds other than 22621.1992, and then it's ready. The fix for dismissing the legacy control center should be near as well.

Finally !!! Salute to ur hard work.. Hoping that it will support higher builds soon.

**Comment by Amrsatrio** [comment]
@Vipin2003 Are you fine with compiling EP yourself? My solution is not ready yet to be release-quality, not even prerelease.

**Comment by Vipin2003** [comment]
> @Vipin2003 Done! It works now on all Windows 11 builds except Canary of course. By the way, are you fine with compiling EP yourself?

Not rn as I'm already busy with my clg projects stuffs.

**Comment by Vipin2003** [comment]
> @Vipin2003 Done! It works now on all Windows 11 builds except Canary of course. By the way, are you fine with compiling EP yourself?

Can you also manage the fixture of opening/closing animations of flyouts also. IDK how SAB managed it but it is very smooth with SAB.

**Comment by Amrsatrio** [comment]
Bro is forcing me to dig deeper into ShellExperienceHost.exe so that the > button beside the WiFi icon in the control center redirects to the old flyout 💀

**Comment by Vipin2003** [comment]
> Bro is forcing me to dig deeper into ShellExperienceHost.exe so that the > button beside the WiFi icon in the control center redirects to the old flyout 💀
> 
> I ain't shipping broken features, sorry.

Alright... I'm just asking. Closing as completed.

**Comment by Amrsatrio** [comment]
Fixed the flyout issue in the latest prerelease. I won't fix that > button.
