### ISSUE TITLE
explorer.exe crasht

### ISSUE THREAD

**Issue by OliverBorgmann** [valinet/ExplorerPatcher#1653]
When I right-click on the taskbar and want to see the context menu, explorer.exe crashes and restarts
Windows Version 22621.2066
Explorer Patcher  newest Pre-Release

**Comment by pyrates999** [comment]
Insider builds and preview updates are not supported due to debug symbols not being available to download, and explorer patcher requires them to function.

So check if symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

You can check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  If it shows it can't download symbols, your version of windows is not supported.

**Comment by OliverBorgmann** [comment]
After i installed the newest Update of EP and Windows (22621.2070) i still have the same Error. The console give me an Errorcode 
Symbols loading fine
I attached the console Log
[ep fault.txt](https://github.com/valinet/ExplorerPatcher/files/12178536/ep.fault.txt)

**Comment by pyrates999** [comment]
Preview updates are not supported and not tested with explorer patcher.  So don't install preview updates if you want to use explorer patcher.
