### ISSUE TITLE
System notifications overlap with the taskbar

### ISSUE THREAD

**Issue by jed84** [valinet/ExplorerPatcher#1708]
Issue: System notifications overlap with the taskbar

ExplorerPatcher v.22621.1992.56.1
Win 11 v.22621.2070

![obraz](https://github.com/valinet/ExplorerPatcher/assets/47121522/893dcbc6-a7de-4e32-81f0-3edf9c2dc96f)

**Comment by Vipin2003** [comment]
It is a known issue for all Insiders...@valinet is checking.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.
