### ISSUE TITLE
Windows 10 start menu not working

### ISSUE THREAD

**Issue by DreamWalker25** [valinet/ExplorerPatcher#1722]
When i change the option to set the start menu to Windows 10 style, nothing happens, it stays the same deafault win 11 style. also the option to disable the recommended section doesn't work too, as also Open start in All apps by default

**Comment by BraINstinct0** [comment]
Windows version and did you restart explorer as mentioned?

**Comment by mpoirier101** [comment]
Windows 10 Start Menu not working anymore... :-(
Running Win11 version: 10.0.22621.2070

**Comment by DreamWalker25** [comment]
> Windows version ~and did you restart explorer as mentioned?~<-- Not needed, just checked

Windows 11 22H2 22621.1992

**Comment by Vipin2003** [comment]
> > Windows version ~and did you restart explorer as mentioned?~<-- Not needed, just checked
> 
> Windows 11 22H2 22621.1992

But it is working for me...

**Comment by xxxxj-up** [comment]
me too

>

**Comment by xxxxj-up** [comment]
I can't use it either

**Comment by xxxxj-up** [comment]
I can't use it either
windows 11 22H2 22621.1702

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by felixfon** [comment]
I updated it to 22621.1555.55.1 and it works now.
Win11 version: 10.0.22621.1992

**Comment by felixfon** [comment]
I updated it to 22621.1992.56.1 and it works now.
Win11 version: 10.0.22621.1992

**Comment by mpoirier101** [comment]
Uninstalled "Preview" update and everything working again !!!

<img width="301" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/21262107/bbc881a4-9f15-42eb-a42d-fb4cb4b41472">

Thank you to @pyrates999 !!!

**Comment by pyrates999** [comment]
You're welcome :)

**Comment by laneAfterRain** [comment]
Win 10 start menu not working too, I came to a new computer to revert old styles, I have tried previous versions, but failed.So is there any solutions?
computer version: win 11 22h2 
os: 22621.4
waiting ^^^^

**Comment by pyrates999** [comment]
Most likely symbols are not downloaded yet: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
