### ISSUE TITLE
Windows11 taskbar crashing when right-click on taskbar

### ISSUE THREAD

**Issue by Innts** [valinet/ExplorerPatcher#1724]
I have been using ExplorerPatcher for a while, and recently, I found that I cannot use the shortcuts Win+N and Win+Tab when switching to the Windows 10-style taskbar.
After updating to ExplorerPatcher 22621.1992.56.1, the taskbar switched to the Windows 11 style, and now, whenever I right-click on the taskbar to access the File Explorer, it crashes, and I am unable to switch back to the Windows 10-style taskbar.

My Win11 version 22621.2070

**Comment by Vipin2003** [comment]
To fix this, follow the steps :
1. Uninstall the preview update first.
2. Uninstall EP after this and remove all reg. keys.
3. After restoring to previous update, make a restart after EP unistallation
4. Install EP on previous bild i.e. 1992
5. after symbols download notification, restart again.
6. Install preview update and restart
7. after restart, don't start anything and wait for symbols download msg for 2070 version.
8. after msg, restart ur device. and it will work fine without any issue.

But there is a issue in all preview updates, that action center (aka notifications) is overlapping win10 taskbar. So, keep in mind. Thanks

**Comment by Leccho** [comment]
File explorer crashes when right clicking the taskbar, this seems to be a problem with ExplorerPatcher. The above suggestion did not work for me.

ExplorerPatcher Version 22621.1992.56.1
Window 11 Version 22621.2070

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by Poopooracoocoo** [comment]
KB5028254 and 22621.2070 was a preview update

**Comment by djcholapin** [comment]
Same issue here. I have two accounts in my laptop : One that works perfectly, and one where the right clic is blocked (And I can't unpin transparent icons from the taskbar). I'm not too keen on uninstalling it because it will uninstall for the whole computer, not just the session, and I spent a great amount of time making the other menu look good. Any way to access file explorer another way maybe ? Or has anyone found a fix ?
