### ISSUE TITLE
Right-click on start bar causes explorer crash/restart after latest symbols update

### ISSUE THREAD

**Issue by andrew-ofg** [valinet/ExplorerPatcher#1738]
I received a notification that symbols had been updated after my last round of Windows Update, and that I should restart file explorer. I right-clicked the start bar in an attempt to open ExplorerPatcher Properties, and explorer instantly crashed and restarted. It's currently not possible for me to use any right-click functionality on the start bar due to this. I can still right-click application icons.

ExplorerPatcher 22621.1992.56.1
Windows 11 22H2
explorer.exe 10.0.22621.2070
Experience Pack 1000.22659.1000.0

**Comment by Leccho** [comment]
#1724

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by andrew-ofg** [comment]
> That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Ah, this makes sense. I had totally forgotten that I opted-in to that. Only now has it caused an issue.

**Comment by pyrates999** [comment]
Could be.  Or they could be only testing on releases.  I don't install preview updates due to them not being fully tested by microsoft.

**Comment by Poopooracoocoo** [comment]
KB5028254 and 22621.2070 was a preview update
