### ISSUE TITLE
when right click on taskbar after install, explorer restarts

### ISSUE THREAD

**Issue by Zerus46** [valinet/ExplorerPatcher#1744]
this happens to me everytime, even after ive shutdown and restarted my computer. Is there a fix?

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by Zerus46** [comment]
Windows Version: 22H2
Build: 22621.2070
Explorer patcher version: 22621.1992.56.1

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by Zerus46** [comment]
Everybody who has this issue aswell, do what the person above says. it worked for me.

**Comment by Poopooracoocoo** [comment]
KB5028254 and 22621.2070 was a preview update
