### ISSUE TITLE
Crash after win 11 update 22H2 (22621.2070)

### ISSUE THREAD

**Issue by ThomasoLorenzo** [valinet/ExplorerPatcher#1746]
![grafik](https://github.com/valinet/ExplorerPatcher/assets/121611349/d2a48b1f-64dd-4cb9-8a09-ca4dbb89b656)

**Comment by Christilut** [comment]
Same problem here, right after the update

**Comment by devedse** [comment]
Same problem here

**Comment by jelle-eastground** [comment]
Same here

**Comment by HigeIris** [comment]
Same problem.
Win11 seems completely changes explorer parameters.
The visual is rounded and a lot of things are missing.

I unsintall the update **KB5028254** and everything is back to normal. I hope ExplorerPatcher will find all changes and fix Windows shitty view for baby user.
To uninstall this update, go to "windows → settings → Windows Update → Update history → Uninstall updates" and select the "KB5028254". It takes few minutes

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by kravens** [comment]
Same issue for me today.

**Comment by BenjaminWKI** [comment]
You do not need to uninstall the Windows 11 Update. The fix detailed here works: https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6580555
