### ISSUE TITLE
No blinking orange icon when recieving a notification, for example in discord. (Using the windows 10 taskbar on windows 11)

### ISSUE THREAD

**Issue by t4kikun** [valinet/ExplorerPatcher#1755]
No orange notification when getting a message in discord or steam for example

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by Amrsatrio** [comment]
No issues on 22621.2134. Have you made sure that the "Taskbar behaviors" > "Show flashing on taskbar apps" setting in the Win11 Settings app is enabled?

Because that build was released 6 days after you created this issue, I will be closing this.

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/c24eaf19-7ca6-4a2e-9f76-db3f4b15a848)
