### ISSUE TITLE
Taskbar is being overlapped by the open windows on the desktop

### ISSUE THREAD

**Issue by RVieitas** [valinet/ExplorerPatcher#1759]
I am writing to ask for your help in resolving a problem I have been experiencing after installing the KB5028254 update (Windows 11 Version 22H2 x64-based systems).
Even though I have updated the ExplorerPatcher to the latest version (22621.1992.56.1), the taskbar is being overlapped by open windows on the desktop. The background color of the taskbar has also changed to the same color as the desktop, and there is no way to change it to a different color.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by Vipin2003** [comment]
This is a known issue which persist in every insider builds.

**Comment by RVieitas** [comment]
Unfortunately, after installing the KB5029263 update, the overlap issue (mentioned above) has returned...
Would there be a solution for this error?

**Comment by kotenok2000** [comment]
It happens on windows 22621.2283 and 22621.1992.56.3
Taskbar icon size is set to small.

**Comment by Poopooracoocoo** [comment]
@RVieitas Got a screenshot? Do you use any other customisation software?

**Comment by RVieitas** [comment]
> @RVieitas Got a screenshot? Do you use any other customisation software?

Hi, Poopooracoocoo.
Yes, I've got one. I'll send the image (below).
And I use the "Classic Start Menu" (http://www.classicshell.net/).

Before the overlapping:
![image](https://github.com/valinet/ExplorerPatcher/assets/141237658/569ac2b7-7924-4d10-a9b7-2dbf61918137)

After the overlapping:
![image](https://github.com/valinet/ExplorerPatcher/assets/141237658/093dd26f-2b41-4e3c-bb21-32c5f7d05491)

**Comment by kotenok2000** [comment]
Does Windows 10 control interface work for you?
It doesn't work for me.
Maybe it is because i have set "UAC Run all administrators in Admin Approval Mode" in secpol.msc so everything runs as administrator?
![image](https://github.com/valinet/ExplorerPatcher/assets/8822292/1bcc3d86-636a-4300-8e6d-1cefc40c67e5)

**Comment by RVieitas** [comment]
> Does Windows 10 control interface work for you?
> It doesn't work for me.

Sorry, kotenok2000, but I really don't know.  :(
I guess I don't have this option because my Windows is home edition.

**Comment by Poopooracoocoo** [comment]
@kotenok2000 You should make a new issue for your issue.

**Comment by Poopooracoocoo** [comment]
@RVieitas You should be using Open Shell instead of Classic Shell. Classic Shell is no longer maintained.

**Comment by kotenok2000** [comment]
It is open shell 4.4.191
![image](https://github.com/valinet/ExplorerPatcher/assets/8822292/68afcca5-f5f6-4c9a-89d8-2333cb49f5c2)

**Comment by kotenok2000** [comment]
> @kotenok2000 You should make a new issue for your issue.

It would probably be closed as duplicate.

**Comment by Poopooracoocoo** [comment]
> > @kotenok2000 You should make a new issue for your issue.
> 
> It would probably be closed as duplicate.

I'm talking about the one where the Windows 10 File Explorer control interface wouldn't work.

**Comment by kotenok2000** [comment]
I am talking about this issue
https://github.com/valinet/ExplorerPatcher/issues/1216
