### ISSUE TITLE
Taskbar is transparent, not possible to switch it off.

### ISSUE THREAD

**Issue by tomogo** [valinet/ExplorerPatcher#1760]
After last Windows 11 update the Task bar is transparent even the Windows option for this is switched to "off".

Windows 11 OS Build 10.0.22621.2070
EP 22621.1992.56.1

CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics
GPU drivers: 31.0.12026.8002

![image](https://github.com/valinet/ExplorerPatcher/assets/7256114/e772b469-a5e5-4770-88a4-bb8adf975eff)

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by tomogo** [comment]
Many thanks, works fine.

**Comment by tomogo** [comment]
Hi,
I'm so sorry but the issue is back after last Windows 11 upgrade.
The "Get the latest updates as soon as available" is unticked.

Windows 11 Pro
Build: 22621.2134

**Comment by pyrates999** [comment]
If you have open shell installed, uninstall it.  That is no longer maintained.

**Comment by tomogo** [comment]
> If you have classic shell installed, uninstall it. That is no longer maintained.
> 
> edit: I meant classic shell, not open shell. open shell is still maintained.

Good work! Thanks!
