### ISSUE TITLE
Repeted exploer and this pc crashes

### ISSUE THREAD

**Issue by MarkMM616** [valinet/ExplorerPatcher#1773]
Yesterday I hade repeated explorer crashes related to explore patch which were so bad i had to factory reset to gain access again to my pc as i was unable to do anything with how fast the crashes were and after the reset  im getting an explore crash when i open this pc every now and then.

**Comment by rosstrimboli** [comment]
Experiencing the same issue. It started appearing after Cumulative Update Windows 11 22H2 (KB5028254) on the 2/8/2023 for me.

**Comment by Majklas** [comment]
this morning, some update or intel driver update caused after login blinking screen, couldn't do anything. remembered that i have this app, cmd and uninstalled it -> it worked.
Also, before that update i've done restore and it worked too. Sadly, once, then it kept on flashing again :/
can we get updates on this app? it's really handy to have taskbar to the left of screen :)

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by rosstrimboli** [comment]
I uninstalled the update and now ExplorerPatcher is working again. I didn't pick up that it was a preview, so I will keep an eye out the next time.
