### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ghost6446** [valinet/ExplorerPatcher#1775]
Program said that is crash 10 time and need an update "WIN 22H2" "22621.2070"

**Comment by giampi75** [comment]
Same problem and same build for me

**Comment by kekzmobile** [comment]
same here, same build

**Comment by Girofox** [comment]
Just wait until a preview update turns into a regular update after maybe one week.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by qaz1qazlol2** [comment]
Strangely,some of my computers don't crash after installing the update,but some computers crashes after installing the update.

**Comment by pyrates999** [comment]
Check to see that symbols were downloaded and restart file explorer after they are: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
