### ISSUE TITLE
Windows+a and windows+b shortcuts stopped working

### ISSUE THREAD

**Issue by bramd** [valinet/ExplorerPatcher#1794]
With Windows 10 task bar style. On Windows 11 build 22621 the win+a and win+b hotkeys stopped working. Win+t still works, but win+n opens a new note in OneNote instead of the Windows notifications.

**Comment by pyrates999** [comment]
Please post windows version and build.
Please post explorer patcher version.

**Comment by bramd** [comment]
Windows 11, Version 22H2 (OS Build 22621.2070)

Explorer Patcher version 22621.1992.56.1

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by bramd** [comment]
Ah, I see, thank you.

That checkbox is kind of misleading, I thought it would just give me updates earlier in a staged rollout, not that I would get previews. If I would like to have previews, I would have become an unpaid beta tester and joined the Insider Program.
