### ISSUE TITLE
Windows 22621.2213

### ISSUE THREAD

**Issue by rm781** [valinet/ExplorerPatcher#1841]
Explorer not working with windows latest update (Windows 22621.2213)

**Comment by pyrates999** [comment]
That is a preview update: https://blogs.windows.com/windows-insider/2023/08/10/releasing-windows-11-build-22621-2213-to-the-release-preview-channel/

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by rm781** [comment]
Thanks

**Comment by kriskeillor** [comment]
I have this issue as well.

Explorer crashes 3x every time I restart then reverts to the non-patched version.

Completely unable to disable preview updates despite configuring group settings. Pretty sure that's on purpose and M$ won't budge. Can only delay them for up to five weeks before they force install.

Uninstalled a couple updates and Explorer Patcher is back.

Thanks for the help!

**Comment by pyrates999** [comment]
If you have the setting "Get the latest updates as soon as available" disabled, preview updates will still be shown.  But they will be shown as download and install instead of automatically installing.  It's then up to you to ignore them.

**Comment by kriskeillor** [comment]
I had the setting disabled and they still installed. Several people in [this thread](https://answers.microsoft.com/en-us/windows/forum/all/how-to-prevent-update-previews-from-installing/1cfbe11b-012a-44f0-a633-7c5742658f9d?page=1) have encountered the same problem.

**Comment by pyrates999** [comment]
Not sure why that setting is not working for you then.

**Comment by kriskeillor** [comment]
MicroSoft ¯\\_(ツ)_/¯
