### ISSUE TITLE
Start menu dont work with W11 build 22621.2213

### ISSUE THREAD

**Issue by tanaduda** [valinet/ExplorerPatcher#1876]
Latest Patcher 22621.1992.56.1

![image](https://github.com/valinet/ExplorerPatcher/assets/54275290/951000d3-fa42-4715-b35b-7e14d47a1d8c)

**Comment by pyrates999** [comment]
That is an insider build: https://blogs.windows.com/windows-insider/2023/08/10/releasing-windows-11-build-22621-2213-to-the-release-preview-channel/

Set Explorer patcher to not download symbols since insider builds have them included: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

You may need to wait for this to get fixed or added as part of a regular update before it may get fixed though.

Is there any technical reason why you are running an insider build?

**Comment by tanaduda** [comment]
I ve download only, not see that is an insider build…sorry!!
I ll get another iso. 

Thanks for faster response!!

**Comment by pyrates999** [comment]
There's an official way of getting the windows iso

windows 10: https://www.microsoft.com/en-gb/software-download/windows10
windows 11: https://www.microsoft.com/en-gb/software-download/windows11

**Comment by tanaduda** [comment]
i ve got an updated iso, its was the problem...but i ll solve it.
Thanks again
