### ISSUE TITLE
Dragging the title bar of any window is sluggish and choppy

### ISSUE THREAD

**Issue by Drixer** [valinet/ExplorerPatcher#1918]
I've had this issue since the 22H1 Windows 11 update that introduced all the bugs, but I updated to 22621.1992.56.3 hoping that would resolve the issue yet it has not.

**Comment by Girofox** [comment]
This may not be related to EP at all but i had the same exact problem since Windows 11 22H1. For me it was fixed when setting mouse polling rate below 250 Hz and after disabling

- `Title bar window shake`
- `Show snap layouts when I drag a window to the top of my screen` 

under `Windows Settings` -> `System ` -> `Multitasking`. 

![Screenshot 2023-08-24 085103](https://github.com/valinet/ExplorerPatcher/assets/43116061/420e2ca6-5863-4622-95a4-a255dbf25180)

You can even disable all animations under settings as last resort if that won't help but for me this is too extreme without any animations at all.

**Comment by Poopooracoocoo** [comment]
@Drixer are you sure that you are this without EP?

**Comment by Drixer** [comment]
> This may not be related to EP at all but i had the same exact problem since Windows 11 22H1. For me it was fixed when setting mouse polling rate below 250 Hz and after disabling
> 
> * `Title bar window shake`
> * `Show snap layouts when I drag a window to the top of my screen`
> 
> under `Windows Settings` -> `System ` -> `Multitasking`.
> 
> ![Screenshot 2023-08-24 085103](https://user-images.githubusercontent.com/43116061/262889897-420e2ca6-5863-4622-95a4-a255dbf25180.png)
> 
> You can even disable all animations under settings as last resort if that won't help but for me this is too extreme without any animations at all.

Thanks Girofox! This has resolved it for me. I thought it was EP since it started happening after I installed it.



> @Drixer are you sure that you see this without EP? It's also worth noting that EP is not compatible with preview updates. Windows 11 23H2 has not yet been released fully.

I didn't have the issue without EP, but I meant 22H1 not 23H2 (has been changed in comment). Changing the setting Girofox mentioned did fit it though.
