### ISSUE TITLE
Ignore this nvm

### ISSUE THREAD

**Issue by DrBrad22** [valinet/ExplorerPatcher#1945]
Hello. I finally updated my version of Explorerpatcher and was pleasantly surprised to hear the start menu issue was finally fixed, unfortunately though, even after updating, the start menu still refuses to pin tiles unless you drag and drop applications, this also means unpinning doesn't work either, forcing me to unpin an entire group for just one thing.

**Comment by Poopooracoocoo** [comment]
> despite the newest update claiming to fix it

Sorry, which commit says that?

**Comment by Gorrrg** [comment]
Where does it say it was patched, the info page states the opposite.

> Before filling a bug report about the Windows 10 Start menu, please read this document which outlines currently known issues and quirks and workarounds.
[PSA: Windows 10 Start menu issues and quirks](https://github.com/valinet/ExplorerPatcher/discussions/1679)

The page merely describes some workarounds. No need to get mad about something that wasn't claimed as fixed in the first place.
