### ISSUE TITLE
Problem with Touchpad Gestures, Alt Tab Switcher 

### ISSUE THREAD

**Issue by ROBOZAPZ13** [valinet/ExplorerPatcher#1956]
Installing ExplorerPatcher causes some problems with touchpad gestures and Alt-Tab switcher. When using Explorer Patcher, the 3 and 4 finger gestures to switch desktops and use the alt-tab switcher do not function. Additionally, trying to use the 3 finger gesture to switch apps (alt-tab switcher) disables alt-tab switcher and stops it from working. To re enable, I need to restart file explorer. 
![image](https://github.com/valinet/ExplorerPatcher/assets/76108047/8ec9dcc7-fb31-46ac-8bbe-0ab6d26d77da)
![image](https://github.com/valinet/ExplorerPatcher/assets/76108047/58ecbe16-9bf1-4231-8c81-3942a65a36b0)

Along with that, certain other features such as the volume bar not showing up when adjusting values with the function keys also happen. 
![image](https://github.com/valinet/ExplorerPatcher/assets/76108047/115f6d8c-fd9f-4e1c-b52e-901d0e8589a8)

Version: 22621.1992.56.3 
Host OS: Windows 11 Home 22H2 Build 22621.2215
Device: Laptop

**Comment by dmalyshevmarinexchange** [comment]
I think, my issue is related to this one: after installing the latest Windows Update today, Alt+Tab and Win+Tab stopped working.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.
