### ISSUE TITLE
Desktop change button

### ISSUE THREAD

**Issue by kimjboland** [valinet/ExplorerPatcher#1962]
I was really happy with this feature, then discovered there is no desktop change button as on the standard taskbar. Is it possible to include this?

**Comment by kimjboland** [comment]
on standard win 11 it is the white square with black square. It seems to be there on the latest version, but I am not sure I have launched the app as the right click does not work. (I have tried the command on cmd box)

**Comment by Poopooracoocoo** [comment]
<img width="486" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/51363864/89012099-b027-4f38-b0e4-40bd8169baff">

You can find "Properties (ExplorerPatcher)" in the Start Menu or in Windows Search. By default, ExplorerPatcher uses the Windows 10 taskbar. You can enable the Task View button on it using ExplorerPatcher's properties. 
https://github.com/valinet/ExplorerPatcher/wiki/All-features#show-task-view-button

Due to a Windows cumulative update various issues are present. Task View will not open. You can use the Windows 11 taskbar with Windhawk mods. And the taskbar context menu won't work  You can enable "Do not change the taskbar context menu (e.g. do not display the "Properties" item)". https://github.com/valinet/ExplorerPatcher/wiki/About-advanced-settings#hide-the-program-settings-item-properties-from-the-taskbar-context-menu. These are just workarounds but I hope they help
