### ISSUE TITLE
the taskbar icons now are Force to be centered

### ISSUE THREAD

**Issue by Khaledtheking** [valinet/ExplorerPatcher#1987]
, just need them to go to left please like always!!
i tried all the options it won't go to the left unless the taskbar is full, but when it is not full it goes in center again

**Comment by Poopooracoocoo** [comment]
If you're referring to the Windows 11 taskbar, it should be in the Windows settings

**Comment by Khaledtheking** [comment]
no it is not working from  Windows settings, when i select left, it goes to center

**Comment by Khaledtheking** [comment]
it is windows 10 taskbar

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Khaledtheking** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/143958902/131b0c77-87d8-4606-9414-f9e3d068d89d)
![image](https://github.com/valinet/ExplorerPatcher/assets/143958902/4f42aa74-9d57-4260-97e5-0d038a53e08a)

**Comment by Khaledtheking** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/143958902/9d68e0ab-e8de-4832-9b9b-479b572a276a)

**Comment by Khaledtheking** [comment]
i really appreciate ur response

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.
