### ISSUE TITLE
"The specified procedure could not be found" error on Windows 10 Build 14393.5582

### ISSUE THREAD

**Issue by legacy1477** [valinet/ExplorerPatcher#2015]
![image](https://github.com/valinet/ExplorerPatcher/assets/118707318/c9cac340-5195-4714-b630-b92e7c2253b6)
![image](https://github.com/valinet/ExplorerPatcher/assets/118707318/23e7d7e1-ce2e-4e09-b021-7d19499d4516)

**Comment by ARestrepo228** [comment]
Explorer Patcher doesn't Work Properlym With Older Windows 10 Builds Before 20H1

**Comment by pyrates999** [comment]
I would never install EP on windows server.

**Comment by pyrates999** [comment]
I also don't like windows 11 and have stuck with windows 10 since windows 7 is no longer getting updates.  I use the following:

1. open shell to get the windows 7 like start menu back
2. 7+ taskbar tweaker to adjust the show desktop button width on the right side making it thicker
3. windhawk for changing the menu shown when you right click to be like windows 7
4. NiceTaskBar to add some transparency to the bottom taskbar to make it like windows 7's taskbar was
5. and now EP.

**Comment by Amrsatrio** [comment]
We do not support Win10 builds as old as this. Even initially we were only supporting Win11 but we made it support the newer Win10 versions, as old as 17763.

Sorry.
