### ISSUE TITLE
Only some Windows-key events after latest Windows update

### ISSUE THREAD

**Issue by Sawtaytoes** [valinet/ExplorerPatcher#2044]
My version is `22621.2215`:
![image](https://github.com/valinet/ExplorerPatcher/assets/3948069/63cee2de-14df-4532-8445-b2049f271ba6)

1. Explorer works fine, but the start menu won't come up.
1. Clicking the Start Menu icon doesn't open the Start Menu either.
1. `[WIN][SHIFT][S]` doesn't work to open the Snipping Tool, but it works if I open it manually.
1. `[WIN][TAB]` doesn't work.
1. `[WIN][R]` works fine.

I have the latest August 28th, 2023 game-ready version of the NVIDIA drivers if that helps.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

**Comment by Sawtaytoes** [comment]
As of the latest update today, the Start Menu is opening:
![image](https://github.com/valinet/ExplorerPatcher/assets/3948069/f56dce37-0b69-4806-a583-a02f34205003)

22621.1992.56.3
