### ISSUE TITLE
Bugs After KB5030219 Update

### ISSUE THREAD

**Issue by CrossyAtom46** [valinet/ExplorerPatcher#2101]
Hi guys i recently updated to this windows version to see what's not working on EP.
If i set taskbar to windows 10:
1. Win + Tab not working.
2. Alt + Tab not working
3. Task View Button on Taskbar works.
If i set taskbar to windows 11:
1. Right Click not working on taskbar

I think that's all.

![image](https://github.com/valinet/ExplorerPatcher/assets/82151617/21191ac6-531b-4e96-b836-507f69487421)

**Comment by rayep** [comment]
@CrossyAtom46 Same here after installing KB5029926, KB5030217.

When I try to "Alt+Tab", Windows explorer crashes and restarts. Hence, tried to restore the default EP settings and then all started to work as expected. Restoring to default settings made some changes to Registry it seems and now, Alt+Tab is working without triggering the Windows Explorer crash.

EP > About > Restore default settings.

**Comment by granterogers** [comment]
EP does not start at all (taskbar flickers and returns to Win11 default after launch) after KB5030219 update for me

**Comment by pyrates999** [comment]
win+tab and alt+tab not working:

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

for when explorer is crashing:

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2051

Please close this one.

Possible fixes:

1. In ExplorerPatcher Properties, go to Advanced and untick **Do not change the taskbar context menu** - there should be an X beside it
2. In ExplorerPatcher Properties, go to File Explorer and untick **Disable the windows 11 context menu**
3. In ExplorerPatcher Properties, go to Taskbar and set **Taskbar style** to **Windows 11**

**Comment by LUDUS3** [comment]
Hi all,
after installing 
x64 (KB5030219) and x64 (KB5031217)

EP does not start at all (taskbar flickers and returns to Win11 default after launch)  :'((

**Comment by CrossyAtom46** [comment]
> win+tab and alt+tab not working:
> 
> duplicate of: #1687
> 
> Please close this one.
> 
> Work around: set to use windows 11 taskbar instead of windows 10 taskbar.
> 
> for when explorer is crashing:
> 
> duplicate of: #2051
> 
> Please close this one.
> 
> Possible fixes:
> 
> 1. In ExplorerPatcher Properties, go to Advanced and untick **Do not change the taskbar context menu** - there should be an X beside it
> 2. In ExplorerPatcher Properties, go to File Explorer and untick **Disable the windows 11 context menu**
> 3. In ExplorerPatcher Properties, go to Taskbar and set **Taskbar style** to **Windows 11**

Okay im closing and i already know the fixes. i thought it's just happened on recent update.

**Comment by granterogers** [comment]
> Made this bat file.
> 
> reg delete "HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell" /f timeout 5 taskkill /im explorer.exe /f timout 3 start explorer.exe exit
> 
> Wait for the Symbols downloaded notification to show up. Then you are good to go.

thanks for trying, but sadly still did not fix for me
