### ISSUE TITLE
No "Settings", "Documents", "Downloads", etc. buttons on Start10 on 22621.2283

### ISSUE THREAD

**Issue by genlosha** [valinet/ExplorerPatcher#2108]
I had them working properly, but after a full clean reinstall of Windows, these buttons won't show up in the start menu anymore. I have already turned them on in the Windows Personalization settings, but it didn't help.
Any possible way to get them back?

Windows version: Windows 11 Pro, 22H2, OS build: 22621.2283
ExplorerPatcher version: 22621.1992.56.3

**Comment by Amrsatrio** [comment]
Can confirm on 22621.2283.

**Comment by pyrates999** [comment]
That was discussed here: https://github.com/valinet/ExplorerPatcher/discussions/1974

**Comment by genlosha** [comment]
> That was discussed here: #1974

The fix mentioned in this discussion works.

**Comment by Vipin2003** [comment]
> Can confirm on 22621.2283. It appears to be introduced in this version since this works just fine on 1992 and 2134.

Good to see that someone is working on fixing all the running issues with EP. I've a suggestion which will enhance EP settings page. Like adding options like Show labels on taskbar, Never combined, etc which are officially released, should also be in EP settings too.
2. Is it possible to bypass or redirect the R-click options in Win11 taskbar too..like "Adjust Date&Time" to classic instead of Settings. And other options also like "Power and Sleep" etc.
3. Fixing the function of closing Start and Search after clicking on blank area on taskbar in Win10 taskbar. It was there in 1992 build but removed in today's latest build.
4. As you know that, now, "Shrink address bar height" won't work in WINSDK lastest explorer as MS redesigned it. Is there any chance to shrink that new address bar too. It will be great if it is possible.
5. There is a Terminal option in Win-X menu in Win10 taskbar, which Is not very useful I think, As whenever we click on it (if Terminal is not installed) it crashes the explorer. I know that Win-X depends on twinshell dll and symbols, but check for this.

**FIRST PRIORITY IS TO FIX THE KNOWN BUGS AS 23H2 IS AROUND THERE. SO, WE DON'T NEED ANY ISSUE IN EP WITH 23H2. THESE ARE MY THOUGHTS AND SUGGESTIONS>**

**Comment by Amrsatrio** [comment]
1. I'll let Valinet deal with the GUI stuff.
2. I'll let Valinet deal with that and it's certainly possible.
3. My main PC is on 22621.1992 and the start and search menu both don't disappear when I click the empty area of the Win10 taskbar.
4. It works just fine even on dev (23545.1000)
5. It works just fine even on dev (23545.1000). Yes, I am not joking.
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/07ca2650-9722-452c-8687-ca51e90441ef)

(Why are we going offtopic in this issue?!)

**Comment by Vipin2003** [comment]
> 1. I'll let Valinet deal with the GUI stuff.
> 2. I'll let Valinet deal with that and it's certainly possible.
> 3. My main PC is on 22621.1992 and the start and search menu both don't disappear when I click the empty area of the Win10 taskbar.
> 4. It works just fine even on dev (23545.1000)
> 5. It works just fine even on dev (23545.1000). Yes, I am not joking.
>    ![image](https://user-images.githubusercontent.com/20662640/270112008-4e8d8282-a9a9-4943-b775-7e42be5beb48.png)
> 
> (Why are we going offtopic in this issue?!)

I forgot to create a new topic related to these.
Regarding point 3, it should be there as many users like me uses that. And also SAB also provide this. I think that it can be introduced in future builds.
And regarding 4 and 5, can you share a SS of these with/without shrink options.

**Comment by Amrsatrio** [comment]
With:
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/dc3b189b-7880-4228-b9f6-09d619a30c31)

Without:
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/df8f094a-a42a-4082-b9ee-7a50f9cd181c)

**Comment by Vipin2003** [comment]
> With: ![image](https://user-images.githubusercontent.com/20662640/270112323-dc3b189b-7880-4228-b9f6-09d619a30c31.png)
> 
> Without: ![image](https://user-images.githubusercontent.com/20662640/270112405-df8f094a-a42a-4082-b9ee-7a50f9cd181c.png)

You are on old explorer. I'm using latest stable preview version 22621.2283. The new File Explorer in on the stable now with the preview. Check once. It won't work now with new Explorer.
![image](https://github.com/valinet/ExplorerPatcher/assets/93650504/78805f05-3b5c-460c-85f3-9bb17397573d)

It remains same in both the situations. i.e. enabling/disabling the option. And, for the Win-X menu, check this:
![image](https://github.com/valinet/ExplorerPatcher/assets/93650504/7003a846-9d0c-4a84-b120-c14c32c150ec)
As you can see that there is a Terminal option in the Win-X menu with the Powershell. Check once

**Comment by Blackdrazon** [comment]
> > That was discussed here: #1974
> 
> The fix mentioned in this discussion works.

Unfortunately, the fix only works in the sense that it can restore the default options for the menu, aka User Icon, Documents, Pictures, and Settings. No other folders can be included, and you can't exclude any of those, either. But better than nothing!

**Comment by Amrsatrio** [comment]
Fixed in the latest prerelease. Tested on 22621.2361.

**Comment by Vipin2003** [comment]
Happy to see fixture of old bugs.
Anyone of you got any way to implement the "Shrink Address bar" with New revamped explorer. Bcoz the new revamped address bar is too big. Hope valinet and you find any way.

**Comment by pyrates999** [comment]
> Happy to see fixture of old bugs. Anyone of you got any way to implement the "Shrink Address bar" with New revamped explorer. Bcoz the new revamped address bar is too big. Hope valinet and you find any way.

Crashes and features not working are priority I think right now, not enhancements.
