### ISSUE TITLE
Latest release does not install

### ISSUE THREAD

**Issue by a-allard** [valinet/ExplorerPatcher#2180]
Hello I just tried to update to the latest release and I get the following error:

![image](https://github.com/valinet/ExplorerPatcher/assets/30708323/aa97a680-e40e-4ad4-86d6-924e8c2b8bee)

I tried updating from wtihin explorerpatcher and from a fresh download from github.  Both result in the same dialog.

System:

Edition	Windows 11 Pro
Version	22H2
Installed on	‎6/‎29/‎2023
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

**Comment by Ezelmannen** [comment]
Exactly the same issue here.

If I download the ep_setup.exe and try to run that I get (translated from Swedish as best I can):
"Can not start the application since it's page by page-configuration has errors. Read the eventlog or use the commandtool sxtrace.exe for more information"
The eventlog gives this (translated from Swedish as best I can):
"Was not able to create an activation context for C:\users[redacted]\Downloads\ep_setup.exe There is an error in the manifest- or prinicpal-file C:\users\[redacted]Downloads\ep_setup.exe on row 0. Faulty XML-syntax."

**Comment by Amrsatrio** [comment]
Have you tried turning off Defender's Real-Time Protection?

**Comment by a-allard** [comment]
@Amrsatrio 

Windows defender is off.  Makes no difference.

**Comment by a-allard** [comment]
After a windows update and a complete shutdown and reboot the update successfully installed.

As a bonus start tab is finally working again.

@Ezelmannen if after a reboot your issue goes away mind closing this out?

**Comment by Ezelmannen** [comment]
Yes. Mine also worked to install now, after a few reboots. (Don't know if any Windows Updates has been done to the machine though. But perhaps that is what solved it).
I am content with you closing the case now. :-)
