### ISSUE TITLE
Notify that it is not supported in preview builds of Windows.

### ISSUE THREAD

**Issue by creeper-0910** [valinet/ExplorerPatcher#2195]
Since there appear to be many bug reports in the preview build of Windows, it might be a good idea to show a warning when installed on a preview build of Windows.

**Comment by Amrsatrio** [comment]
I have been trying to make EP supported on Release Preview and Dev builds so that we can make better preparations for upcoming Windows updates. Also, most of the new issues are related to usage of 7+ Taskbar Tweaker (https://github.com/valinet/ExplorerPatcher/discussions/2182, https://github.com/valinet/ExplorerPatcher/discussions/2194) and not having a good Internet connection when installing EP (https://github.com/valinet/ExplorerPatcher/discussions/2194, https://github.com/valinet/ExplorerPatcher/discussions/2196, and [this message in Discord](https://discord.com/channels/1155912047897350204/1155912052687241228/1156501595777933382)).

However, since I'm not planning to make this supported on Insider Preview Canary. I'll leave this suggestion to Valinet.

EP の開発者が将来の Windows アップデートによりよい準備ができるように、私は EP を Release Preview と Dev のビルドでサポートするように試しています。また、ほとんどの最近の問題は、7+ Taskbar Tweaker を使用していることや、EPのインストール中にインターネット接続が良くないことに関するようです。

ただし、Insider Preview Canary でサポートする予定はありませんので、この提案をValinetさんに任せます。

日本語が片言で申し訳ありません。🙏

**Comment by creeper-0910** [comment]
日本語での説明、本当にありがとうございます！🙏
Thank you so much for the explanation in Japanese!🙏

**Comment by Amrsatrio** [comment]
Feel free to close this issue. If there are problems that are not in the release build but present in the preview build(s), reports would be appreciated.
この問題を閉じるのは自由です。リリースビルドにないが、プレビュービルドにある問題があれば、ご報告お願いします。

**Comment by creeper-0910** [comment]
Okay,thanks!
了解しました、ありがとうございます！
