### ISSUE TITLE
File Explorer is crashing on right click (Win10 ribbon/Win7 command bar with Win11 context menu)

### ISSUE THREAD

**Issue by jed84** [valinet/ExplorerPatcher#2198]
**Issue:**
Given I have [Windows 11 context menu enabled
And I have [Win10 ribbon] or [Win7 command bar] enbaled in EP,
When I right click anywhere in the File Explorer,
Then the File Explorer is crashing.

**Notes:**
The crash does not happen if Win11 command bar is enabled.

Windows 11 22H2 (22621.2361) 
EP 22621.2361.58.1

**Comment by jed84** [comment]
I uninstalled and reinstalled EP 22621.2361.58.1 and as for now it seems to resolve the problem.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/september-26-2023-kb5030310-os-build-22621-2361-preview-363ac1ae-6ea8-41b3-b3cc-22a2a5682faf

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.
