### ISSUE TITLE
explorerpatcher reset the new "never combine taskbar buttons" setting

### ISSUE THREAD

**Issue by gabri25ele** [valinet/ExplorerPatcher#2207]
Windows 22621.2361 with the return of **never combine taskbar buttons**
Explorerpatcher 22621.2361.58.1 at every restart of Windows it changes the new taskbar setting "never combine taskbar buttons" (I set to never, it returns (next time restart PC) to always.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/september-26-2023-kb5030310-os-build-22621-2361-preview-363ac1ae-6ea8-41b3-b3cc-22a2a5682faf

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.

**Comment by gabri25ele** [comment]
> Uninstall it if you want to use explorer patcher and don't install preview updates 

I Want preview updates!

**Comment by Amrsatrio** [comment]
@pyrates999 Symbols are available for this build. It's the build everyone will get in the coming weeks.

Back to the issue. I saw somewhere in EP's code that it forces the Win11 taskbar to always combine due to issues with it on earlier builds. But now with never combine I guess that has to be changed.

@valinet Sorry for tagging, but since you know your configuration code (GUI and stuff) well, can you make it so that the taskbar combine setting follows Win10 behavior on 22621.2361+? In other words synced with the system instead of using EP's custom registry key.

**Comment by tallman69** [comment]
For what it is worth, according to this article, Microsoft's Never Combine feature does not work as well as what we have with the Never Combine feature in EP.
https://www.bleepingcomputer.com/news/microsoft/windows-11s-new-never-combine-icons-feature-is-almost-usable/

**Comment by gabri25ele** [comment]
I use Windows 11 taskbar in Explorer Patcher, just to know.

**Comment by pyrates999** [comment]
> > Uninstall it if you want to use explorer patcher and don't install preview updates
> 
> I Want preview updates!

There's no reason to install preview updates if you're not a developer.  Security updates are not included in preview updates.  So there's no technical reason for installing them.

**Comment by valinet** [comment]
> For what it is worth, according to this article, Microsoft's new Never Combine feature does not work as well as what we have with the Never Combine feature in EP.
> https://www.bleepingcomputer.com/news/microsoft/windows-11s-new-never-combine-icons-feature-is-almost-usable/

The article is idiotic, pardon my language, but never combine shows labels even in Windows 10, and most people wanting never combine expect that. Anyway, if I am to complain, I’d complain about the new never combine having variable button widths - a malicious app can mess your entire taskbar by calling SetWindowText with different length titles, and it also can lead to misclicks and lost time. Even a malicious web site can now mess your entire taskbar, that’s nuts, it’s jarring to see no one at Microsoft thought about this, or maybe they did but again chose ”looks nice” over proper implementation.

**Comment by valinet** [comment]
@Amrsatrio The situation regarding this bug is rather shitty. Let me explain:

The reason for the original redirection of `TaskbarGlomLevel` and `MMTaskbaGlomLevel` is because the new Windows 11 taskbar has been prepared since launch for never combine. If the users set `TaskbarGlomLevel` to 2 (i.e. never combine), the icons were still combined, but when you hovered on the icons, the previews were shown as if the taskbar was never combined (i.e. no window titles, since you could see that on the taskbar label that was not there yet). So if EP was to save the setting in `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced`, and the user set 'never combine' and then switch back to the Windows 11 taskbar (or even uninstalled EP), it would break the taskbar... Again, all due to shitty Microsoft code if you ask me, all this situation was generated.

Now, the idea with EP was to also enable the never combine feature by default, as that was the feature initially sought by most EP users. So I consider the default glom level to be 2 throughout the EP code on Windows 11. Now that the taskbar supports never combine but not as a default, this creates a problem, since the new taskbar also uses the setting now.

The reason why "never combine" settings are reset on the Windows 11 taskbar is because EP deletes emenants of `TaskbarGlomLevel`, to prevent the bug I described above. Neutering these 2 lines should be enough to sop this behavior:

```
                RegDeleteKeyValueW(HKEY_CURRENT_USER, L"Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", L"TaskbarGlomLevel");
                RegDeleteKeyValueW(HKEY_CURRENT_USER, L"Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", L"MMTaskbarGlomLevel");
```

I can make a commit for that asap to at least fix this annoyance. A full fix would be to write some more `if` checks and decide how to handle all of this on newer Windows 11 builds that have this never combine feature. Right now, the Properties window doesn't show glom settings when the new taskbar is enabled, that has to be fixed as well...

**Comment by valinet** [comment]
I mean, 2 years for them to code this and it's still buggy, it's a mystery to me how this passed QA in this state:

![Recording 2023-10-03 163859](https://github.com/valinet/ExplorerPatcher/assets/6503598/6cabe500-447b-4f67-98be-86c4042880d4)

Some friend at work bought a new laptop, it has Windows 11 preinstalled, it lags and everything takes 1 sec+ to load fresh out of the box. The level is unacceptable imo...

**Comment by valinet** [comment]
I have pushed an update that mitigates this issue by having Ep not reset the setting. A more polished fix should be discussed and developed momentarily. Thanks for the heads-up!
