### ISSUE TITLE
On Moment 4 builds, disabling recommended apps section in the Windows 11 start menu doesn't work anymore

### ISSUE THREAD

**Issue by hecode** [valinet/ExplorerPatcher#2212]
The Start menu win 11 style is still showing recommended apps since a few versions ago. 
checking the disable recommended apps should remove that.

**Comment by hecode** [comment]
also app switcher doesn't change but not as important

**Comment by hecode** [comment]
workaround for start menu is using show all apps then going back.

**Comment by Amrsatrio** [comment]
Yes, this started happening since 22621/22631.2361.

**Comment by pyrates999** [comment]
Please limit your bug reports to one bug.  If you see multiple bugs, search to see if it's already been reported and if not, then report it.

**Comment by Vipin2003** [comment]
Is this issue currently running ?? I dont face this issue.

**Comment by hecode** [comment]
It is still occurring for me,  yes

**Comment by Muska-Ami** [comment]
The same problem when open the All Apps menu and back to start menu

**Comment by sruPL** [comment]
Build 22631 (after Windows update) - the issue appeared on my system as well (W11). I tried to restart Patcher and check for updates, nothing worked.

**Comment by pyrates999** [comment]
Your windows build number is incomplete.

Please post windows version and build.  You can find this by running winver.

**Comment by sruPL** [comment]
Version 23H2 (OS Build: 22631.2506)

**Comment by hecode** [comment]
it was happening in multiple OS versions. currently it's 22631.2428

**Comment by pyrates999** [comment]
> Version 23H2 (OS Build: 22631.2506)

That is a preview update: https://support.microsoft.com/en-us/topic/october-31-2023-kb5031455-os-builds-22621-2506-and-22631-2506-preview-6513c5ec-c5a2-4aaf-97f5-44c13d29e0d4

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by Amrsatrio** [comment]
This works on 22621.2715 so closing this for now.

**Comment by hecode** [comment]
> This works on 22621.2715 so closing this for now.

I have updated to 22631.2715 and the issue is still occurring. any way to get that working version?

**Comment by hecode** [comment]
Still isn't working on 22621.2861.62.1
