### ISSUE TITLE
Right click doesn't work when EP is active

### ISSUE THREAD

**Issue by Elmarco1** [valinet/ExplorerPatcher#2214]
I'm on windows 11 with the latest EP release but yet got the right click not working on the desktop. Screen disappear and comebackk as if i had never try to use the right click. 

I made a test and when i delete EP, right click works properly.

What should I do to resolve that problem? 

I don't have much knowledge about computer so, if possible, make your answer understandable for a newbie! :) 

Thank you for your help. 

Have all a good day! :)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Elmarco1** [comment]
Hi pyratess999,

I'm on Windows 11, version 22H2, operating system 22621.2361

Explore patcher settings are by default.

Thank you.

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/september-26-2023-kb5030310-os-build-22621-2361-preview-363ac1ae-6ea8-41b3-b3cc-22a2a5682faf

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.

**Comment by Elmarco1** [comment]
I've done everything you asked. Operating system is now 22621.2283.

Restarted my pc. Problem still there.

Deleted EP. Restarded pc. Reloaded EP and restarted pc. Problem still there.

**Comment by Amrsatrio** [comment]
When EP is not installed, does this happen when you click the show more options item in the new context menu? Sounds like a poorly written app messed up your right click.

**Comment by Elmarco1** [comment]
No. Everything works perfectly. 

Anyway, while I was trying to resolve that problem, I've noticed that now I have the option to not combine tabs on the taskbar so I don't need EP anymore. 

Thank you.
