### ISSUE TITLE
I cannot show all tray icons on Windows 10 style taskbar

### ISSUE THREAD

**Issue by goshante** [valinet/ExplorerPatcher#2217]
I hate this ^ icon that groups all icons I want to see, I always disabled it in windows 10 and I could see every status icon I want.
But here, in windows 11 i don't have such option. And also check every icon to show in win11 taskbar settings doesn't affect windows 10 taskbar from ExplorerPatcher.
I want to see every icon in my tray, not this annoying ^ icon.

After upgrading from 10 to 11 it preserved taskbar settings from win10 and ExplorerPatcher's win10 taskbar showed me it just as I want.
But aftert clean installation I cannot make it as it was before.

Please, add this option to settings. And while there is no such option tell me how to make this (i  think there should be some option in  registry)

**Comment by Amrsatrio** [comment]
This works fine on 22631.2361. Otherwise something is wrong in your Windows install which is out of our scope.

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/ca5a513a-6328-4216-990e-57fff43f45e9)
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/11bd7f61-785f-4ac3-9906-cc72ff81ee5d)
