### ISSUE TITLE
Explorer Patcher Causing Counter Strike 2 to Blue Screen of Death (BSoD)

### ISSUE THREAD

**Issue by AFGreeneye** [valinet/ExplorerPatcher#2267]
Hello! I wanted to let you know that the Explorer Patch program is causing my Counter Strike 2 to crash, resulting in a Blue Screen of Death (BSoD). I attempted to record the error code once, but it no longer displays the error code. So, I had to uninstall the program, and now my problem is solved.

Edit: I am using windows 11

**Comment by Amrsatrio** [comment]
Have you tried again without registering EP as shell extension?

**Comment by AFGreeneye** [comment]
> Have you tried again without registering EP as shell extension?

How can I do that?

**Comment by pyrates999** [comment]
Open EP properties application.  Go to File Explorer and untick register as a shell extension.  Then reboot.

**Comment by AFGreeneye** [comment]
"Register as a shell extension" is unticked by default!

**Comment by pyrates999** [comment]
Since this hasn't been asked yet.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by Amrsatrio** [comment]
Whoops didn't mean to close this. But I tried to make a prerelease that doesn't let `funchook` run outside Explorer. Please let me know how it goes.

**Comment by AFGreeneye** [comment]
Alright, everyone, it appears that my issue was related to one of the following: DirectX12 in the new Nvidia driver, the AMD chipset driver, the old CS2 patch, or the enabled CSM setting in the motherboard. However, I'm happy to report that the problem has now been resolved

**Comment by pyrates999** [comment]
read this: https://www.theverge.com/2023/10/14/23916966/cs2-counter-strike-2-anti-lag-plus-ban-amd-gpu-radeon-rx-7000

**Comment by Catalyst44** [comment]
Having now got my PC working fully I have some simple advice to anyone running ExplorerPatcher in Windows 11.  Uninstall ExplorerPatcher BEFORE attempting to update Windows with the latest update.  My attempt to update Windows with EP installed caused a lot of BSOD's as I mentioned before, BUT it also corrupted my system so that even after I uninstalled EP Windows refused to update - reporting files missing etc.  I tried everything to get it to update but the damage was done.  I then restored a two-month old backup, uninstalled EP and then did all the Windows updates and it all now works fine.

**Comment by Amrsatrio** [comment]
EP does not modify system files. At all. That is the goal of EP. I don't know how you got a BSOD "regardless of what you were doing" while on PCs I use daily for 1.5 years with EP installed and Windows updates installed monthly, I've never got EP-related BSODs at all. The black screens after update are the worst I've got, which I've fixed in the latest EP versions.
