### ISSUE TITLE
Windows 10 taskbar is not working, it's still windows 11.

### ISSUE THREAD

**Issue by DaRealFieldZoo** [valinet/ExplorerPatcher#2365]

**Comment by Amrsatrio** [comment]
What's your build number? Is it one of the Dev builds?

**Comment by DaRealFieldZoo** [comment]
the build number is 22621.1555.55.1
windows 11 10.0.22621.2506

**Comment by Amrsatrio** [comment]
Please update your Windows to the latest one (22621.2428 or 22621.2506), and then reinstall EP after updating. It should be all right because I'm using 22621.2428 and the Windows 10 taskbar works as it should.

If you can't download via Windows Update, you can try downloading manually from Microsoft Update Catalog: https://www.catalog.update.microsoft.com/Search.aspx?q=KB5031455
