### ISSUE TITLE
Taskbar on top overlaps full screen windows

### ISSUE THREAD

**Issue by qriouslad** [valinet/ExplorerPatcher#237]
When I move the taskbar to the top of the screen, and then try to maximize a window, e.g. browser window, the taskbar overlaps the top part of the browser windows.

**Comment by valinet** [comment]
Please check if any other programs are messing something up. I just tested this and it works just fine on my side. Thanks.

![image](https://user-images.githubusercontent.com/6503598/139564786-0fe54c1c-a180-4bc2-934b-f40332883e31.png)

**Comment by qriouslad** [comment]
@valinet you are correct. I had MaxTo active, which may have caused it. All good now. Thanks for the prompt response and hope you can grab a cup of beverage from the small donation I've just made. Keep up the great work.

**Comment by valinet** [comment]
Thank you. Also, no worries, as a rule, always disable other stuff when debugging something because even though it may not seem so, even the 2 most opposite software can interact in the weirdest ways, and with things EP does, it is a good chance it may interact with stuff done by other tweaking utilities.

Personally, I also do not use any other tweak than EP on my development machine, so the tests I do are usually conclusive, in that if it works on mine, it most likely should work for other users as well, provided something else does not interfere there.

Anyway, I am glad that you got it solved.
