### ISSUE TITLE
how to change UI language ?

### ISSUE THREAD

**Issue by bighamx** [valinet/ExplorerPatcher#2458]
My windows 10 language setting is Chinese, but after installing this app, the setting dialog interface is in English. I can't find the option to change the language, how can I change the language? thanks

**Comment by bighamx** [comment]
![image](https://github.com/valinet/ExplorerPatcher/assets/10262931/2bf5a2aa-9bb2-4de3-b7aa-39663b86f11a)

**Comment by oyal** [comment]
Same issue.

**Comment by ElapseRecall** [comment]
> My windows 10 language setting is Chinese, but after installing this app, the setting dialog interface is in English. I can't find the option to change the language, how can I change the language? thanks

这边有说明
https://github.com/zetaloop/ExplorerPatcher

**Comment by Amrsatrio** [comment]
Download the latest prerelease. It has official Chinese translations.

**Comment by Amrsatrio** [comment]
Yes, planned in a future release.

**Comment by EataPizza** [comment]
Recently, the settings in the Explorer Patcher has changed to Chinese. Do you know to set it to English? Because English is more easy to understand.

"Recently, the settings in Explorer Patcher have changed to Chinese. Could you please guide me on how to set it back to English? I find English easier to understand."
