### ISSUE TITLE
ExplorerPatcher shell extension breaks Powershell console under 22000.282

### ISSUE THREAD

**Issue by prengle** [valinet/ExplorerPatcher#256]
I already noticed a few closed issues regarding the experimental shell extension functionality, so here's another one :D (I recreated this using ExplorerPatcher 22000.282.32 and Win11 22000.282 in a VMware virtual machine, but I've had this issue occur across multiple versions of both ExplorerPatcher and Win11)

Steps to reproduce:

1. Install ExplorerPatcher normally by dropping dxgi.dll into C:\Windows
2. Register ExplorerPatcher.amd64.dll in C:\Program Files\ExplorerPatcher using regsvr32
3. Kill/restart explorer.exe
4. Run powershell.exe 

I also recorded a video demonstrating the issue: https://files.catbox.moe/nova0k.mp4

Powershell running through cmd, Windows Terminal (which doesn't play nice with the classic theme, surprise, surprise) and even the Powershell ISE all still work fine, it's just the Powershell console itself which refuses to open. Installing Powershell 7 on top of whatever version comes preinstalled (5? 5.1?) doesn't make a difference. I'm not certain if installing ExplorerPatcher using both the dxgi.dll method and the shell extension method is redundant or not, either.

(Also, to put it bluntly, this is still an absolute fucking godsend of a project - I wish the classic theme mitigations were backported to 10 LTSC's Explorer or something since I don't trust M$ to not rip out the old taskbar entirely in future 11 builds, but as it stands this might singlehandedly make 11 usable and that's astounding)

**Comment by valinet** [comment]
Fixed in the latest version. Although, let me ask, why do you need this? As I said in a couple of places, this mode of operation is still experimental, not necessary for 99% of use cases, and recommended only for specific use cases, so please do not use this other than for testing (and hopefully contributing back some patches, as I am not really interested in working too much on this on my own, at least at the moment, since I do not use it at all) or some specific use case you should know about ahead of time.

Thanks for the report, it was nevertheless a quirk in the code.

**Comment by prengle** [comment]
just to clarify - i'm attempting to get the classic theme working, i read this in a release post:

> "The application can now be registered as a shell extension. This will enable the Explorer related functionality to work in Open/Save file dialogs as well. This is especially useful for users wanting proper support of the classic theme in Windows 11"

and assumed that i needed to install explorerpatcher as a shell extension to get working open/save dialogs at all with the classic theme. i just checked to see if it works without registering the .dll and it's [fine as far as i can tell](https://files.catbox.moe/y2glin.png). not sure if enabling the win8/10 ribbon in the explorerpatcher properties window and then hiding it with oldnewexplorer caused any unintentional side effects, but hopefully this is a nonissue now.

**Comment by valinet** [comment]
Okay, to clarify on my part: first of all, more info about what the shell extension brings, which represents 95% classic theme related things is described in the classic theme thread in Discussions here: https://github.com/valinet/ExplorerPatcher/discussions/101. It's not centralized, we talked a lot in various comments. 

Second of all, a shell extension is required just in order to inject all processes and mainly patch the context menu to remove the owner drawing which does not work with classic theme because they measure the stuff with functions from `uxtheme` which don't work if you close the theme handle. Besides that, it also attempts to make windows that ignore the address bar hide setting not ignore that, adds the 3D style to some Explorer views etc... technicalities, you can read more about those in the thread. But nothing major, the main work is still done by `dxgi.dll` which needs dropping in `C:\Windows` and that's enough.

The wording on the release post could be better, I admit. I will remove the mention altogether, it confuses some people. Running as shell extension is something extra and it's not required at all to get the core experience going. It's still more work in progress than the rest and may have various bugs. Also, for the moment, it still requires you to drop the DLL in `C:\Windows` even if using as shell extension.

So yeah, hope that sets things more clear, I will also update the README at some point with this information.

Thanks

**Comment by Anixx** [comment]
> it's [fine as far as i can tell](https://files.catbox.moe/y2glin.png).

Without shell extension the context menus in file dialogs do not work in classic theme.

**Comment by valinet** [comment]
> 
> 
> > it's [fine as far as i can tell](https://files.catbox.moe/y2glin.png).
> 
> Without the shell extension the context menus in file dialogs do not work in classic theme.

Of course. It's logic that you can't to a lot of changes to other processes without injecting them, and without EP set up as shell extension EP does not inject other processes (except `StartMenuExperienceHost.exe`)... As I said, contributions are more than welcome.
