### ISSUE TITLE
Just launched UWP windows are missing from the Windows 10 window switcher

### ISSUE THREAD

**Issue by CrendKing** [valinet/ExplorerPatcher#266]
The switcher has a weird bug. Say I have two classic windows opened initially. After I open the "Settings" (which is UWP), the first time I press Alt+Tab, I won't see Settings. However, since the second time and onward, I see Settings appears and switchable.

This applies to all UWP windows, e.g. Microsoft Store as well.

**Comment by valinet** [comment]
It's not a weird bug. Layouts are precomputed (so that it appears quick no matter the load on the CPU when needed). They are not computed continously, but only when certain events occur, like window changes, window resizing finishing etc. If I don't get some sort of notification when a window is created, a new layout is not computed again.

Considering this, the reason why UWP apps do not trigger a `HSHELL_WINDOWCREATED` or a `HSHELL_RUDEAPPACTIVATED` when you open it, for example, is way way way beyond my understanding. Oh, no, I think I have a vague presumption why: because this OS sucks, especially anything that was introuduced post Windows 7. One requires at least 1 million workarounds for the most basic things. As a live example, check the function that determines which windows should be displayed.

I will see what I can do.

**Comment by CrendKing** [comment]
> because this OS sucks, especially anything that was introuduced post Windows 7

I was reading your code about `ShouldAddWindowToTray` and noticed those undocumented "band" functions, which IIRC are introduced after Windows 8.

So yes, I would not call the OS suck from end user's perspective, because all these new features are shiny and useful (at least to some of them, or else Microsoft won't keep them coming). But from developer's perspective, I hate all these undocumented and inconsistent behaviors. It's like Microsoft wants to keep all the new things to themselves.

This issue is just nitpicking. I wouldn't mind if you decide to not change at all. Just an FYI. Close if you want.

**Comment by valinet** [comment]
> 
> 
> > because this OS sucks, especially anything that was introuduced post Windows 7
> 
> I was reading your code about `ShouldAddWindowToTray` and noticed those undocumented "band" functions, which IIRC are introduced after Windows 8.
> 
> So yes, I would not call the OS suck from end user's perspective, because all these new features are shiny and useful (at least to some of them, or else Microsoft won't keep them coming). But from developer's perspective, I hate all these undocumented and inconsistent behaviors. It's like Microsoft wants to keep all the new things to themselves.
> 
> This issue is just nitpicking. I wouldn't mind if you decide to not change at all. Just an FYI. Close if you want.

No, the OS sucks. That's the right word. It's not fair to any of the actors involved, not the developers and not the user.

Most of the stuff is undocumented since Windows 8. MSDN is useless mostly; IDA/Ghidra are your only friends if you want to actually do something. UWP doesn't suck per se, I never said that, this stupid behavior sucks. 

The job of an OS is to provide a fair playground for user space to express itself into. With Windows, that's not the case. Microsoft's user land is always more privileged (see how only some apps that must be signed with Microsoft's certificate are allowed to bypass UAC, how the theme file has to be called `aero` to enable certain code paths in DWM, how `CreateWindowInBand` receieves `error 5 - Access is denied` when run in any other process other than a Microsoft signed one). This hardcodes are not the right thing to solve this.

I understand that any process randomly creating windows in the above lock UX band can be dangerous, as it may lead to those kind of viruses that just nag the user by showing a full screen window in that band, so the user is unable to do anything on the computer. I get that. But this way of protecting that is stupid to say the least. It shows the shittiest mindset about computer security one could think of. You don't obtain security though obscurity, for God sake, when is everyone going to understand that...? 

What's the current solution? Require apps to be signed with a Microsoft certificate in order to access certain APIs? Why that? I will talk about that in the next paragraph. Now, let's see, so I need to be signed by Microsoft. Okay, I will just inject a Microsoft process then and create windows there. Injection is too inconvenient or they decide to (somehow?) deny it for their processes? Sure, no problem, do it like ModernFlyouts does it for example: they found out that `ApplicationFrameHost.exe` from build 17763 or something like that used some function from `dxgi.dll`, which is not on the `KnownDLLs` list, so they just launch that with a custom `dxgi.dll` which implements all their program in there. So they can create the volume control window in a superior band, which is required for such a band. Same technique used by EP basically. People always find workarounds, and if it is not a real protection anyway, why annoy everyone with these shits...?

How to solve it properly? A capabilities system, duh. You know how apps ask the user on Android if they can "draw over other apps"? Something like that here. The user accepts, then the app can create windows in other bands. Or just fucking let the API just be usable, like, apps can create top level window even now, if one wants to do a nagging app even today, they can do with the public API just easily. There's no real reason to restrict that function, only to just create an unfair playground where first party apps are blessed with access to "special" APIs by the OS. THE OS SHOULD NEVER DO THAT. The user should always have the choice of which apps to use on an OS, the OS has to provide a fair playground for those to express themselves in, and third party app developers should have access to the same set of APIs in user space as first party apps do. Why has one to state all of this in 2021...?

They do this shit even in kernel space. They restrict you to run whatever code you want, on YOUR machine, as an user, in kernel space, unless you put your entire machine at risk via test mode, but they have no hesitation enabling such functionality for the Chinese communists that have all the means to demand such functionality, which we all know what they use it for, not even something ethic probably. I, on the other hand, I can't officially run a totally ethic own developed keyboard filter driver on my XPS laptop unless I put all my system at risk via test mode. Or again, [hack their kernel to enable what they already licensed to the Chinese commies, but not me](https://github.com/valinet/ssde). Because, you know, we care about principles only in flashy conferences on national television. Same as everyone's an ecologist, but you can barely get yourself inside a supermarket navigating though the sea of cars parked right at the entrance by those big electric car supporters out there.

My 2 cents about this situation, I am generally disgusted by the mentality of this OS vendor, simple as that... Compared to 1990, they just have a bigger army of paid journalists and much better line in bullshit convincing fools that "Microsoft <3 open source". As Stallman [said](https://www.gnu.org/philosophy/open-source-misses-the-point.html), whoever uses the word "open source" anyway probably hasn't understand much about the whole idea anyway...

**Comment by valinet** [comment]
Anyway, I apparently get notified, BUT: when creating new UWP windows, they are initially cloaked, even though they are visible on the screen just fine... So, why do it cleanly, as I said, another workaround needed, ofc... Where in the documentation do they say that UWP apps are initially cloaked until they show actual content...? Why? So when they show the splash screen they are presumably not displayed where? In the Alt+Tab list? Then it means the system gets notified when they are eventually ready. How? Again, undocumented... because why not...

**Comment by valinet** [comment]
See how Raymond Chen says [here](https://devblogs.microsoft.com/oldnewthing/20200302-00/?p=103507) that "The shell has a concept called cloaking, in which a window is given all the trappings of visibility, without actually being presented to the user". UWP apps are shown since they are launched, they just show a splash screen. That's still something presented to the user to me, so it should be consider non cloaked. But no, it just reports itself as being cloaked...

**Comment by CrendKing** [comment]
Hmmm, I think you should post this on Hacker News and guaranteed to farm some karmas 😃

Joke aside, what you said here is not Microsoft alone. Apple is no stranger to restrict user from doing things. "They restrict you to run whatever code you want, on YOUR machine, as an user"? Sounds familiar. I just want to change the font of my Android phone. Why do I have to first unlock bootloader, and flash a new image to root? And don't forget about browsers. They are supposed to be user's "agent", but they more act like user's custodian. It's 2021. Every big player is doing like this, or they soon no longer be big player.

Back to Microsoft, the recent [.net hot reload controversy](https://dusted.codes/can-we-trust-microsoft-with-open-source) tells me that there is some turf war going on inside the company. No doubt folks from the classic, offline product departments are feeling uncomfortable towards their online product colleagues. This might very well include the Windows department. Sure, "Windows as a service", but this service generates revenue way less directly than 1 millions calls to Azure storage. If I'm the head of the department, it might be my best interest to withhold secrets as leverage against other departments, rather than release them to public for good.

**Comment by CrendKing** [comment]
> UWP apps are initially cloaked until they show actual content

Do you get notification when they go uncloak?

**Comment by valinet** [comment]
> 
> 
> Hmmm, I think you should post this on Hacker News and guaranteed to farm some karmas 😃
> 
> Joke aside, what you said here is not Microsoft alone. Apple is no stranger to restrict user from doing things. "They restrict you to run whatever code you want, on YOUR machine, as an user"? Sounds familiar. I just want to change the font of my Android phone. Why do I have to first unlock bootloader, and flash a new image to root? And don't forget about browsers. They are supposed to be user's "agent", but they more act like user's custodian. It's 2021. Every big player is doing like this, or they soon no longer be big player.
> 
> Back to Microsoft, the recent [.net hot reload controversy](https://dusted.codes/can-we-trust-microsoft-with-open-source) tells me that there is some turf war going on inside the company. No doubt folks from the classic, offline product departments are feeling uncomfortable towards their online product colleagues. This might very well include the Windows department. Sure, "Windows as a service", but this service generates revenue way less directly than 1 millions calls to Azure storage. If I'm the head of the department, it might be my best interest to withhold secrets as leverage against other departments, rather than release them to public for good.

Yeah, I agree with you, but it misses the point. Just because others do shit doesn't justify one behave shitty as well. Apple doing shitty stuff doesn't justify Microsoft. And I never gave any other party as an example, just a specific thing done right in Android. Not saying everything is perfect there, or anywhere else, at Apple or wherever. As I very much know it is not. But, again, it doesn't excuse Microsoft. Want me to rant about Android as well? No problem, I am not of those people that see them as idols just because they brand themselves as open source when in fact the end product has the same closed mentality as iOS just fine.

> 
> 
> > UWP apps are initially cloaked until they show actual content
> 
> Do you get notification when they go uncloak?

Is there such a thing?

**Comment by CrendKing** [comment]
I was just replying "I concur" in a more elaborated way 😄 

> Is there such a thing?

I don't know. I asked because for example classic windows has WM_ messages to notify internal state changes. If UWP doesn't use WM_, shouldn't there be some equivalent mechanism to notify "My content is ready, and about to go uncloak. Send out this notification to listeners"?

**Comment by valinet** [comment]
> 
> 
> I was just replying "I concur" in a more elaborated way 😄

Okay then, I concur too. 😄

> 
> > Is there such a thing?
> 
> I don't know. I asked because for example classic windows has WM_ messages to notify internal state changes. If UWP doesn't use WM_ or extend them, shouldn't there be some equivalent mechanism to notify "My content is ready, and about to go uncloak. Send out this notification to listeners"?

Yeah, but like, I don't hook other windows... It definitely used window messages somewhere deep, but I do not hook UWP apps and subclass their wndprocs. I just subscribe to messages useful for shell applications using `RegisterWindowMessageW(L"SHELLHOOK")` and that sends some messages interesting to applications implementing shells, like `HSHELL_WINDOWCREATED`, on my window procedure. Besides that, I also use `SetWinEventHook` with `EVENT_SYSTEM_MOVESIZEEND` to get notified when windows finish resizing, as that should trigger a layout recalculation as well (so the thumbnail is sized correctly, according to the new window size).

And I get a `HSHELL_WINDOWCREATED` or `HSHELL_RUDEAPPACTIVATED` when the UWP window is shown on screen, it is just that at that point it is cloaked, or that's what the API reports, the window is visible just fine, so in reality not cloaked, but the API just likes to lie, because why not... It seems to me it is "cloaked" until the splash screen is gone and actual content is shown.

**Comment by valinet** [comment]
I could take out the check altogether there and just recalculate anyway, I guess... I don't remember why I added it in there anyway... probably just so, idk, not trigger useless layout calculations when a window is created on another desktop, for example, so it clearly doesn't affect the layout on the current monitor... I don't remember exactly, maybe it just seemed logical, I hope it doesn't introduce other weird issues... It shouldn't. And windows opening or activating on other desktops is very rare, doesn't add much overhead if any. So yeah, I take that check out, it seems to work fine without.

Here: [dxgi.zip](https://github.com/valinet/ExplorerPatcher/files/7471639/dxgi.zip)

**Comment by CrendKing** [comment]
I see no change.

**Comment by valinet** [comment]
Idk, it works just fine over here.

**Comment by valinet** [comment]
It's racy anyway, the way it seems to me. Maybe the cloak attribute changes slower on your machine. Basically, by removing that check, I just delay it a few instructions until I calculate the layout, where I also take into account the cloak, as I can't just do without it, otherwise wrong windows would show there.

**Comment by CrendKing** [comment]
Seems consistent to me. I could wait for 10 seconds after opening the Settings, it won't show it.

![Screenshot](https://user-images.githubusercontent.com/975235/140242783-2955934f-1574-4847-9f69-d0b32ec95463.jpg)

![Version](https://user-images.githubusercontent.com/975235/140242716-80eb8080-b2b4-4310-a113-74cb7d1c3d2e.jpg)

**Comment by valinet** [comment]
I believe you, read my previous comment. Doesn't matter how long you wait, what mattered is how fast/slow it got to the second check for the cloak attribute. I already said that.

**Comment by CrendKing** [comment]
Sure. I guess you can probably keep this change, so some users could benefit from it, and call it done?

**Comment by valinet** [comment]
Nah, it's just racy and stupid. I like stuff to be correct, generally. I simply don't know how to do it properly, I am still thinking how to, without delaying the check, waiting a bit, you know, other kinds of stupid stuff. I am 99% sure it is "cloaked" until the splash screen disappears, which can take varying amounts of time.

> 
> Then I just need to figure out why the attribute changes happen slowly on my machine. Surely it's not because my Ryzen 3700X is too slow...

Don't spend too much time on it. Things just happen. And I was mistaken. Not really mistaken, it makes sense. I have an i7-9750H which has slower IPC. Probably, by the time it gets to the second check, Settings finished loading and becomes uncloaked and the checks sees that and it includes it in the layout. On yours, the IPC being higher, maybe it gets to the second check *faster*, maybe even Settings take some more time to load, who knows (SSD speeds, whatever...) and at the second check it is still cloaked.

Anyway, don't bother with that. it's perfectly normal. That's a race condition, the definition of it. This has to be solved properly somehow, not like this. As I said, I am trying to figure out a way how...

**Comment by CrendKing** [comment]
> > 
> 
> Don't spend too much time on it. Things just happen. And I was mistaken. Not really mistaken, it makes sense. I have an i7-9750H which has slower IPC. Probably, by the time it gets to the second check, Settings finished loading and becomes uncloaked and the second check sees that and it includes it in the layout. On yours, the IPC being higher, maybe it gets to the second check _faster_, maybe even Settings take some more time to load, who knows (SSD speeds, whatever...) and at the second check it is still cloaked.
> 
> Anyway, don't bother with that. It's perfectly normal. That's a race condition, the definition of it. This has to be solved properly somehow, not like this. As I said, I am trying to figure out a way how...

Don't worry. It's my mocking way of expressing hands up and give up. Like I said before, this is just a nitpicking. I don't get bothered.

**Comment by valinet** [comment]
You know, now that I have seen it, it cannot be unseen =))) it just sits on my mind. And there should be a quick, dirty and maybe hacky way to fix it at least, idk...

**Comment by valinet** [comment]
I have found out `EVENT_OBJECT_UNCLOAKED`. I can subscribe to that and issue a relayout when that happens. Seems to work just fine now. A proper solution, indeed. I think I can close this now, the new version (.5) will be uploaded soon.
