### ISSUE TITLE
Disable Control Center icon

### ISSUE THREAD

**Issue by IsraelNS902** [valinet/ExplorerPatcher#27]
The control center from Windows 11 appears as a gear icon beside the time on the taskbar, is it possible to disable or hide it?

**Comment by BraINstinct0** [comment]
At least it isn't covered by System Tray icon settings, so it'll need more investigation.

**Comment by valinet** [comment]
Yeah, there is, let me explain:

The Control Center button logic is located in `explorer.exe`. It seems to inherit from `CTrayButton` (its constructor calls `CTrayButton`'s constructor). All `CTrayButton`s have a method called `CTrayButton::v_IsEnabled` that presumably returns whether this actual button is enabled in the shell. This also affects whether it gets displayed wherever it lives, in the case of the control center button, the notification tray (`Shell_TrayWnd`).
Also, the actual HWND that hosts the button's class uses a generic `WndProc` (`CImpWndProc::s_WndProc`) that does some initialization things (done when receiving `WM_CREATE`) and other than that just calls the specific WndProc (in the case of `CTrayButton`, it calls `CTrayButton::v_WndProc`). During the initialization, in `WM_CREATE`, it calls `SetWindowLongPtr` on the window HWND, location 0 and sets it to a pointer to the instance of the window class this window belongs to (in our case, the pointer would be to an object of type `ControlCenterButton`).
So, if we get an HWND to the control center button, we can call `GetWindowLongPtrW(hWnd, 0)` on that HWND and get a pointer to the actual control center button's class. Afterwards, if we look on the `CTrayButton::v_IsEnabled` method, we see that the assembly merely reads something like `return *((BYTE *)_this + 120)`. So, it means that the flag whether this button is enabled or not is stored there. Indeed, that is set to 1 in the constructor as well, so it kind of makes sense (by default, the button is enabled).
So, there is a need to only somehow get an HWND to that window, from which we get a pointer to the underlying implementation class, from which we get a pointer to a flag that stores whether this feature is enabled, and we modify that hopefully by the time it is queried in the places responsible for drawing the button.
The safest way to do this is to look on the initialization function of `CTrayButton` (`CTrayButton::Initialize`) as that is the soonest place we can hook into after the window is created. Instead of the approach used until now, sometimes a better way to hook into functions is to instead hook in standard Win32 APIs but only in a specific DLL by patching the import function table ([IAT patching](https://blog.neteril.org/blog/2016/12/23/diverting-functions-windows-iat-patching/)). This allows for a more targeted injection, among other advantages, like reducing the number of required symbols to download etc. One could hook `CreateWindowExW` or [`SetChildWindowNoActivate`](https://stackoverflow.com/questions/45924018/no-activate-child-windows) (which is called for Control Center button, indeed), for example, and override the flag in there manually.
Of course, what I described above works for any `CTrayButton` that does not employ other mechanism for determining whether the feature is enabled (for example, the notification center icon sends a message to the `Shell_TrayWnd` to determine this, so this approach won't work for that).
The dev version of StartIsBack uses a similar approach to achieve the same effect. Very clever, indeed! I highly recommend checking that out as well.

So, yeah, it is doable relatively easily. I will probably add it to a new release once I finish some cleanup I am currently doing on the current code base. But it is doable in a straightforward way.

**Comment by valinet** [comment]
Option added in latest release
