### ISSUE TITLE
Disabling Windows 11 context menu removes (None) under Group By on Sort menu for Downloads folder etc. in Explorer

### ISSUE THREAD

**Issue by PGomersall** [valinet/ExplorerPatcher#271]
On the 3 systems I am testing Explorer Patcher on if I disable the Windows 11 context menus I loose access to this feature.
Re-enabling the Windows 11 context menus provides access again. If you turn off grouping while W11 context is working and the disable the setting sticks at least.
I am not sure if this is "bug" in Explorer Patcher or a "feature change" related to disabling the W11 context menus.

**Comment by valinet** [comment]
This feature is so straightforward coded, that I don't know how it can affect anything. Disabling the new context menu happens by having COM be unable to identify the DLL where the new one is implemented (this is done by adding one single registry entry - as described in this [Reddit thread](https://www.reddit.com/r/Windows11/comments/pu5aa3/howto_disable_new_context_menu_explorer_command/)), so Explorer falls back to using the classic one. The classic one is already used in windows originating from Control Panel etc.

I'd suggest you do some testing, check your configuration etc. Disable everything and see if you get the options then. Also, check to see if you get them directly when navigating to `C:\` from Control Panel.

Also, "Group By" - "None" is available when the folder is already grouped, otherwise it doesn't show.

I have also checked it in my Downloads folder, it appears just fine:

![image](https://user-images.githubusercontent.com/6503598/140426218-2fd05edc-6a9a-47a8-a162-92cec55a4e47.png)

I strongly believe this can hardly be a bug in ExplorerPatcher, due to the way this feature is implemented anyway.

**Comment by kykc** [comment]
Can't confirm, *(none)* option is there for me when Windows 11 context menu is disabled. Option is absent only if grouping is actually disabled, which is expected behavior I guess.

<img width="1059" alt="group" src="https://user-images.githubusercontent.com/879032/140426189-f5bf7b18-7e8d-46d3-a24f-4691ea96c4a3.png">
