### ISSUE TITLE
Windows 10 taskbar doesn't autohide

### ISSUE THREAD

**Issue by Chaython** [valinet/ExplorerPatcher#2738]
The auto hide has a single? Or a few vertical pixels, it's not fully hidden when hiding.
This is an issue as I use an OLED, and am worried about burn in.
The windows 11TB does fully auto-hide.

**Comment by Amrsatrio** [comment]
This is a Windows issue and is also present on Windows 10. The Windows 11 taskbar is actually hidden in the same way too, with 1 pixel still visible, but because there's a vertical margin on the content it looks like it's fully hidden.

I have a plan to make a solution for this as I use OLED as well and I'm worried of my OLED's long term health.
