### ISSUE TITLE
Restore taskbar context menu

### ISSUE THREAD

**Issue by SunnyLeu** [valinet/ExplorerPatcher#2793]
Can I disable this menu
![image](https://github.com/valinet/ExplorerPatcher/assets/51817348/60f29133-fff4-4e81-a2d1-9578ed52ce8c)
and restore Windows 11 taskbar original context menu?

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by SunnyLeu** [comment]
windows version and build:
![image](https://github.com/valinet/ExplorerPatcher/assets/51817348/4a4ce1b3-8808-4f2d-a18f-4d994c76c6f4)

explorer patcher version:
22621.2861.62.2

settings I changed in explorer patcher properties application:
![image](https://github.com/valinet/ExplorerPatcher/assets/51817348/c044974f-df4a-4585-923f-ad61f22bd916)
![image](https://github.com/valinet/ExplorerPatcher/assets/51817348/e2727e50-257e-445e-bd28-0775d9b25c56)
![image](https://github.com/valinet/ExplorerPatcher/assets/51817348/533edae1-0b4f-4ef9-9871-6013cfc5718c)
![image](https://github.com/valinet/ExplorerPatcher/assets/51817348/42cd59ce-f68c-423e-a9ff-c93af8188744)
![image](https://github.com/valinet/ExplorerPatcher/assets/51817348/225f5e83-112d-4dcd-8b10-ac002406bc8e)
![image](https://github.com/valinet/ExplorerPatcher/assets/51817348/03f5d855-a9e6-4081-b0a1-d5012ffd7a28)

any other software I have installed that modifies the UI of windows:
no

**Comment by pyrates999** [comment]
You installed a preview update: https://support.microsoft.com/en-au/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

Now for restoring the menu shown, do you mean for it to be in your language instead of english?

**Comment by SunnyLeu** [comment]
> You installed a preview update: https://support.microsoft.com/en-au/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.
> 
> You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.
> 
> Now for restoring the menu shown, do you mean for it to be in your language instead of english?

I think you misunderstand me, the image I post is from https://github.com/valinet/ExplorerPatcher/wiki/All-features#windows-11 ,and the question is how can I DON'T show that menu but show the original Winsows 11 taskbar menu.

**Comment by pyrates999** [comment]
No, I'm just giving you additional information.

And I think this is the option you want to enable: https://github.com/valinet/ExplorerPatcher/wiki/About-advanced-settings#hide-the-program-settings-item-properties-from-the-taskbar-context-menu

But then you won't have a quick way to change the settings in EP because there will be no **Properties** in the menu when you right click on the taskbar.

**Comment by SunnyLeu** [comment]
> No, I'm just giving you additional information.
> 
> And I think this is the option you want to enable: https://github.com/valinet/ExplorerPatcher/wiki/About-advanced-settings#hide-the-program-settings-item-properties-from-the-taskbar-context-menu
> 
> But then you won't have a quick way to change the settings in EP because there will be no **Properties** in the menu when you right click on the taskbar.

Thanks a lot, it's what I want, and I had create a shortcut on desktop that starts EP's setting, so don't worry.
