### ISSUE TITLE
Unable to delete history in the modern search box in File Explorer in build 22463 or 22468

### ISSUE THREAD

**Issue by duk6046** [valinet/ExplorerPatcher#28]
I can not click or delete the search history, it looks normal but not working. (build 22468.1 and 22463.1)

**Comment by valinet** [comment]
Yeah, it is probably because of `dxgi.dll` beside `SearchHost.exe`. Delete it from `C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy` and report back if what you tried to do works.

I anyway could barely understand what you said, of course bothering to write more than 1 line would have costed enormous amounts of money, I understand. /s What "search history"? A lot of people around here expect someone to help but offer nothing but the most minimalist minimal description of the problem they can... as I said, this should be a community, but everyone demands something and does not even bother to help with a workable description, let alone actual coding.

I am really debating whether to take this private, it starts pissing me off a lot. Do you really think your report is that helpful? Want me to help you, help me out a bit more as well. What would you understand if someone came out of the blue and told you that? Do I really have to put up some form requesting to follow a certain template, because you and a few others can't be bothered to provide info in a meaningful way, a way that shows it took you more than 30 seconds to write about it, rather than throw it there and call it a day. I perfectly understand if English is not your first language, but then attach a photo showing what you are talking about. I don't demand essays, but c'mon...

Yeah, so, try what I said in the first paragraph and we shall go from there. Thanks.

**Comment by duk6046** [comment]
Thanks. i try it, but still not working. and sorry to bad English

**Comment by Gaurav-Original-ClassicShellTester** [comment]
> Thanks. i try it, but still not working. and sorry to bad English

Can you at least provide a screenshot? Just saying "not working" gives no idea about what exactly isn't working, what your settings are for the Explorer search box. Have you enabled the old behavior or kept the new one?

**Comment by duk6046** [comment]
This is the search history. and i click that, there is no happen
![Inked화면 캡처 2021-09-30 211446](https://user-images.githubusercontent.com/32978164/135453921-0dd3dfc8-dafd-457e-923d-5503bf1b81fc.jpg)

**Comment by valinet** [comment]
> 
> 
> This is the search history. and i click that, there is no happen ![Inked화면 캡처 2021-09-30 211446](https://user-images.githubusercontent.com/32978164/135453921-0dd3dfc8-dafd-457e-923d-5503bf1b81fc.jpg)

Okay, thanks. Yeah, idk, this software has nothing to do with that. Again, basic advice, have you tried deleting the entry without ExplorerPatcher loaded? If it does not work, it is a bug in Windows, not much this software can do about it. I have tried on 22000.194, it works, although it is clunky af, sometimes click go though, as is the case with that feature. You can also right click an entry and choose to delete it from there, does it work that way? Try some basic troubleshooting...

**Comment by duk6046** [comment]
oh sorry it looks MS and other tweak issue. it was work on 22000.194. thank you for comment

**Comment by Gaurav-Original-ClassicShellTester** [comment]
It looks like even when the new search box is enabled, clicking on it with the mouse does nothing (with ExplorerPatcher disabled completely). It works for me only with keyboard arrow keys and Enter. Yet another thing Microsoft broke and if they care they may fix it at some point or never fix it.

**Comment by valinet** [comment]
Yeah, makes sense, the first thing to suspect when something breaks is Microsoft, than any third party tool. It just is the way it is nowadays.
