### ISSUE TITLE
22621.3007.63.2 Windows 10 Taskbar hang/blackscreen on initial startup/boot

### ISSUE THREAD

**Issue by austinjklim** [valinet/ExplorerPatcher#2862]
Winver 23H2 22361.3155, installed 3007.63.2 EP.

On boot, explorer would hang for a few seconds (5-15s), then everything would work.
Only replicable when using win 10 taskbar, using win11 taskbar does not have this issue, despite everything else is the same.

newly clean install for Win11. With only tweaks from WinUtil. as per attached. But changing the taskbar to Win11 does not present this issue, restarted 3 times to check findings are true.

https://github.com/valinet/ExplorerPatcher/assets/16682922/d9364e8b-0ae3-4428-abe6-07e852e3e1ae

Images:

![1](https://github.com/valinet/ExplorerPatcher/assets/16682922/dbaeba1b-3f75-4d11-8bc2-651ef77f0ebb)
![2](https://github.com/valinet/ExplorerPatcher/assets/16682922/17362272-902c-406a-8e59-66bf2d179285)
![3](https://github.com/valinet/ExplorerPatcher/assets/16682922/7d3395ca-6bb2-4b8f-8300-a38f3aaaf140)
![4](https://github.com/valinet/ExplorerPatcher/assets/16682922/b2b66aba-a816-4c88-a12e-30a54c4c4496)
![5](https://github.com/valinet/ExplorerPatcher/assets/16682922/bd724d8f-aecc-4c3c-bffd-fb5d9f44280d)
![6](https://github.com/valinet/ExplorerPatcher/assets/16682922/893e9396-bd4a-4200-b867-4ed8e93fdec7)
![7](https://github.com/valinet/ExplorerPatcher/assets/16682922/7ea5a6c4-8631-43d1-86e6-43b9bc526d2e)
![8](https://github.com/valinet/ExplorerPatcher/assets/16682922/db0ea2c1-4660-4ecd-b8ce-9b31c4f67e68)
![9](https://github.com/valinet/ExplorerPatcher/assets/16682922/b748411e-6b18-44c5-b69e-5c535a27a96d)
![10](https://github.com/valinet/ExplorerPatcher/assets/16682922/d623c6c4-5123-4682-8d48-75b46d941834)

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
If you restart your PC, does that happen again? If it doesn't then it was related to a safeguard I have just added which would disable EP when the system is in OOBE.

**Comment by austinjklim** [comment]
Yes. With every restart it has that issue. But if i choose win11 taskbar and restart instead it would not have that issue.

Im not knowledgeable on oobe, but after installing all my programs and such it still has this issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Amrsatrio** [comment]
Looks like it has something to do with the patcher that you used.

**Comment by Volidon** [comment]
I'm getting this too after every restart and I do not use any other patcher. Winver 23H2 22361.3155 and tried on 22621.3007.63.2 and 22621.3007.63.4

**Comment by GPSMapper** [comment]
Eperiencing exactly the same issue, not sure when exactly it has started, likely after most recent W11 update.
Running the same version of EP and latest W11 as per previous reply.
The only 'Tweaker' I am using on top of EP is the WinAero (was 1.40, now updated to latest 1.62.1, same behavior with EP)

**Comment by GPSMapper** [comment]
OK, I think I have identified the "root cause" and and a workaround to fix it.

@austinjklim 
If you are experiencing the described issue, try the following:
- after starting the PC and waiting for black screen to disappear - MANUALLY restart 'File Explorer' using the EP Properties option.
- after this you would probbaly see a black scren shortly and after that a 'standard' Windows setup screen should appear, asking you to confirm some of the system option. In my case it was whether do I want to enable my Windows account to sync across all my devices.
- make your choice and confirm, you will return back to desktop
- try restarting File Excplorer again, Windows settings winzar should no longer appear
- after that, you should no longer see the 

After Windows Feature updates, Miscosoft is often starting the wizard to confirm some of the settings. It seems that after last update the wizard prompts were surpressed by EP (resulting in a black screen)  and the fact it was not confirmed, was causing this issue on every startup.

**Comment by Amrsatrio** [comment]
> Microsoft wizard screen

It's called Second Chance Out-of-Box Experience or SCOOBE in short. I have fixed EP crashing when it is displayed by the system, in the latest 64.1 pre-release.

Please let me know if you're still experiencing this.
