### ISSUE TITLE
[Feature Suggestion] GUI for non tech-saavy users

### ISSUE THREAD

**Issue by BraINstinct0** [valinet/ExplorerPatcher#29]
IIRC Starting on Oct. 5, win11 will roll out to the public. I'm already seeing some ppl complaining about some `features` (mostly the startmenu, but also taskbar and explorer) introduced in Win11.
The problem is, not many non-IT ppl feel comfortable using even Run(Win+R) or regedit.
A solution to this IMO is to provide a simple GUI for settings:
- [ ] Show a (possibly exhaustive) list of edits
- [ ] Show whether those changes are applied (via checking if registry key is created/edited, etc.)
- [ ] Check for updates - _applying_ update feature isn't essential, though.

I don't have time to write one, but a quick WinForms+PS script might be just enough for the job.

**Comment by valinet** [comment]
So, I wanted to type a lengthy reply (I have actually written it on my phone but haven't pushed "Comment" 16 hours ago) on why I won't implement it and how I am open to someone else implementing this, yet in the meantime, I decided it may be a fun exercise (it was kind of fun) and got to doing it. Thus, the application now has a GUI. Open it by right clicking Start and choosing "Properties". It allows setting the most common options, the same ones described in the README.

It is implemented in pure C, without ATL or anything else, everything is computed manually so to say. The UI logic is described by comments in a .reg file which I use to store the defaults in and to restore them, by merging it into the registry when the user requests so. It works more than fine for what the application requires. It also features a Mica background applied all over the window, just to look nice in Windows 11.

Regarding checking for updates, I'd leave that out for now. I don't know, since the application does not have an installer, why would it have an updater. Plus, I don't think it needs one necessarily. Users update it when it eventually brakes because the Windows build changed too much. Other than that, it is set and forget, I think. Plus, I hate a million daemons checking for updates. That has the potential to introduce tons of bugs, lots to implement, not much in return. Think about the fact that we are in `explorer.exe`, any thing we mess with in a bad manner has the potential of crashing the entire shell. Anyway, I included a link to Github, so users can quickly see what's up with the project and whether any new updates became available in the meantime.

But yeah, I don't have much time for this either. Let's say today was an exception. The application is kind of feature complete now, at least for the moment. I cannot work on this endlessly, I also have other things to take care of.

<img src="https://user-images.githubusercontent.com/6503598/135698816-b97b7305-f425-4320-b5e6-69843677e510.png"  width=70% height=70%>

**Comment by BraINstinct0** [comment]
Totally agreed, thanks for taking the time for a GUI - now I can recommend this to non-tech background Win11 newcomers!

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Great work really! And also the enhancement to select the Desktop item upon right click just like Windows does - thank you!! Your app is a lifesaver for Windows 11.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
One small problem is that the UI is getting cut off at the top on my 16:9 laptop display:

![image](https://user-images.githubusercontent.com/46422834/135708531-ecb9c0e5-aab7-4a05-9c8c-257b56ba67a0.png)

**Comment by valinet** [comment]
> 
> One small problem is that the UI is getting cut off at the top on my 16:9 laptop display:
> 


Yeah, I thought so, I work at 3840x2160, haven't tested that in practice, though. I will lower the padding between UI elements, that's the quickest fix. Maybe it will use columns in the future, it would not be THAT hard to implement... I wish someone would maintain this part of the project, I hate UIs.
