### ISSUE TITLE
Is it possible to make news widgets like in Windows 10 instead of the weather?

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#2929]
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/2435

<div type='discussions-op-text'>

<sup>Originally posted by **Bledrock** November 13, 2023</sup>
Is this feature still in the Windows 11 regedit?

Instead of this:
![241907104-ff1ee90c-7737-40dc-b869-cc472c467210](https://github.com/valinet/ExplorerPatcher/assets/111048284/e730017c-612c-4910-9094-b6688987c6b5)

And this:
![241907359-2d073130-6841-43fb-a0b2-c601165f6aca](https://github.com/valinet/ExplorerPatcher/assets/111048284/ed646441-7f95-4583-9ba5-e66fbec14db6)

Replace with this menu:
![241907934-676a96e8-f69a-4bab-94ad-d2fe83e2b51e](https://github.com/valinet/ExplorerPatcher/assets/111048284/1384b2f9-640a-4e3f-b752-b8a09c426cb4)
</div>

**Comment by Amrsatrio** [comment]
Shut up. Go install Windows 10 instead of tirelessly begging for features that are impossible or not viable to add because of huge differences under the hood. I will NOT try to implement them no matter how many times you ping me or post issues or raise awareness or whatever you think is best for you. Understood? Get a life.

**Comment by FastMaster678** [comment]
I think they were asking for a "yes" or "no" answer, not a "get a life"...
