### ISSUE TITLE
Not updating properly (I think....)

### ISSUE THREAD

**Issue by TotemicWeevil** [valinet/ExplorerPatcher#2934]
![307541335-219043c7-e73c-4a5e-aa18-b1eca427a5b1](https://github.com/valinet/ExplorerPatcher/assets/130712740/c60c9be9-7885-406f-a1a4-dd7b7e95639e)

Am I correct in thinking that there's an issue with my installed version?
I've read posts where people say they're on 63.x whilst I'm on 62.2. The only reason I'm posting this is because today (2nd March) I reformatted my HD and reinstalled win 11. After changing my browser to Firefox, I came here and downloaded the setup file.
Installing it gave me 62.2 and not 63.x as I expected.

What (if anything) am I doing wrong or is the error somewhere else?

**Comment by tallman69** [comment]
You are not doing anything wrong.  Some users of newer versions of EP have been having issues with Microsoft Defender falsely flagging EP as malware and blocking it, so the developers of EP have made version 22621.2861.62.2 the latest release because Defender does not flag it.  Since I have a third-party antivirus on my computer and do not use Defender, I have been able run the newer versions of EP without it being flagged as malicious.

**Comment by pyrates999** [comment]
They are running a pre-release.  That's why the version number appears to be newer.  This is the latest release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2861.62.2_9b68cc0
