### ISSUE TITLE
Injecting Start is unreliable: `LoadLibraryW` returns `ERROR_ACCESS_DENIED` in random circumstances

### ISSUE THREAD

**Issue by CrendKing** [valinet/ExplorerPatcher#299]
As title. Let me know if you can't repro.

**Comment by valinet** [comment]
And like, now I noticed, I bumped up the version with a few changes, maybe upgrade to the latest as well, see if it helps…?

**Comment by CrendKing** [comment]
As of 22000.282.33.0, it's still not working for me. But if I revert to [22000.282.32.6](https://github.com/valinet/ExplorerPatcher/releases/tag/22000.282.32.6_81cbd47), it works.

**Comment by valinet** [comment]
I just tested with the automatically built version as well (the one available in releases), I cannot reproduce. I hit the Start button or the `Win` key, it opens to All apps by default. I use that option as well, everyday. Yeah, I cannot reproduce.

3ac5921 bumped the version to `32.7`. Most of the changes since then have been made to the window switcher. Check out a version locally, revert commits one by one, compile and try to see what breaks it; when it stops breaking, go up one commit and selectively take out stuff to get back manually to the commit before, until you isolate the culprit.

The only thing that may differ is the Windows build, I am on 22000.282.

**Comment by valinet** [comment]
I tested in a VM. It's not about versions. This fucking OS denies remote injections from time to time, based on criteria only known by it. `32.6` is probably whitelisted by the OS somehow, and it allows it to inject `StartMenuExperienceHost.exe`, while newer versions seem not to be. Again, undocumented, obscure and totally secret mechanisms only Microsoft knows about. 

Also, enable the console and check there, it prints some stuff beginning with `[StartMenu]` when things regarding it happen. If you see this, then yeah, fucking OS messes again with me, as usual:

```
[StartMenu] Process found.
[StartMenu] Allocated path memory.
[StartMenu] Wrote path: C:\Windows\dxgi.dll.
[StartMenu] Injected DLL.
[StartMenu] Library loaded: 0x0.
[StartMenu] Remote module enumeration succeeded.
[StartMenu] Remote module not found.
```

Not to mention testing is a pain in the ass, as I don't know what the fuck triggers it to prefer one file over the other...

**Comment by CrendKing** [comment]
I rebooted cleanly, see the problem exists.

Enabled the console and rebooted, trying to see the initial message you asked.

Problem no longer existed and `[StartMenu] Library loaded: 0x93b0000.`.

Disabled console and rebooted. Problem no longer existed.

I feel you bro.

**Comment by valinet** [comment]
Yeah, it's fucking stupid, some shitty internal mechanism is denying its loading based on some obscure criteria only on certain occasions... I have spent all day playing with it today, modified the code a bit to inject using a shell code so I can get more information. 

The remote thread is created just fine at all times, I can run code there no problem, and that was probably the case on your first attempt as well. What fails is the call to `LoadLibraryW` which loads `C:\Windows\dxgi.dll` in `StartMenuExperienceHost.exe`. That some times returns `ERROR_ACCESS_DENIED`. Why? I simply don't know... some shitty security concerns which only kick in some times, apparently. Like, what is even the point, I can already run code in the remote process, what's the big deal if I use `LoadLibraryW` to bring some more, that triggers this denial, like, I can manually implement `LoadLibraryW` then and call it a day... that should fix it forever.

It's very stupid, in this manner, we will end up rewriting the entire OS some day... some behaviors regarding stuff Microsoft does are weird to say the least... if I am allowed to run code in a particular remote process anyway, denying the use of `LoadLibraryW` just slows the inevitable so to speak, in that one has to manually put together a library loader... or idk, the code for Start is so few, I could rewrite it as to perform injections on demand whenever some setting changes... idk, I don't want to bother extremely much though...

And like, why deny injecting other processes at the same privilege level with some undocumented and erratic behavior...? Weird decisions on their part, that's for sure...

**Comment by CrendKing** [comment]
Correct me if I'm wrong. If you have to use remote thread to inject `dxgi.dll` to `StartMenuExperienceHost.exe` (which I think already loads the System32 `dxgi.dll`), why bother to have dxgi.dll placed in C:\Windows? Why not just create an executable that injects `ExplorerPatcher.dll` to all the necessary processes? That would ease the process of updating your dll, and probably ease the pain in debugging. I'm seriously considering of making a Windows 11 virtual machine just to help you test this dll.

**Comment by valinet** [comment]
> Is it because that approach would require admin, and you don't want to deal with elevation?

No; I mean, to drop a DLL in `C:\Windows` still requires admin, so... `explorer.exe` and `StartMenuExperienceHost.exe` run unelevated anyway, so messing with them is available to any regular process, mainly*.

There are a plethora of ways to have your code run in a remote process, all with their ups and downs. Before delving into that, understand the basic architecture of how EP works: you drop the DLL in `C:\Windows` to have it inject `explorer.exe` (`explorer.exe` uses `DXGIDeclareAdapterRemovalSupport` from `dxgi.dll`). This is possible by exploiting the DLL search order mechanism of `LoadLibraryW` and the fact that `LoadLibraryW(L"dxgi.dll")` is called by `explorer.exe` with a relative path and the fact that `dxgi.dll` is not on the list of `KnownDLLs` (a list of DLLs that are always loaded from `C:\Windows\System32`). So, with `dxgi.dll` in `C:\Windows`, `explorer.exe` gets injected.

Now, why this method? If you can afford it, this is the most reliable method - the DLL will be loaded, otherwise the executable cannot run, because it lists that library as required in order to run. The price to pay is that you need to be able to drop it near the target executable mainly. You do not even need to reimplement stubs for the library's function exports, as you can use forwarding and have exports that forward to the original DLL, and only stub whatever call in the target process you want to use as your library's entry point - in the case of `explorer.exe`, EP sets itself up when `explorer.exe` calls `DXGIDeclareadapterRemovalSupport` which is very early in the setup process, almost as soon as its entry point, `wWinMain` is called.

Why not set up from `DllMain`? Because that may be too early and the target process may not be fully prepared at that stage. Plus, `DllMain` is called for every other type of library load where you might not want to execute the set up.

Why not hook at runtime? Well, idk, two fold issue:

* Historically, it was just easier to get started with these schema; you do not have to worry of a runtime loading mechanism, you can just get loaded this way and since it is so early, but after the process is fully set up in the memory by the loader, you have plenty opportunity to do whatever you want in it; most stuff in `explorer` - not most, **ALL** - hasn't even started running, so no race conditions, just a clean slate to patch whatever one needs
* Runtime hooking is tricky: what loads you into the process? Be a shell extension? That's too late, probably, the taskbar is already created by that time. How do others do it (SAB for example)? Through plenty of tricks. 
  * One other way is to impersonate some COM library that Explorer loads, so have it load you at some stage you determine is still fine and from there start doing your job. It's a similar principle to the "`dxgi` method", but COM overrides can be set via `HKEY_CURRENT_USER` as well. You also have to spend time studying the executable more and determine when it calls `CoCreateInstance` for that particular object, spend time writing a proper impersonator for that etc.
  * Another way is how EP did it way back in August, initially: `explorer.exe` runs a program listed in some `Taskman` registry entry in `HKEY_LOCAL_MACHINE` as well, also early in the startup sequence; not as early as `DXGIDeclareAdapterRemovalSupport`, but still, early enough; I don't remember exactly what the purpose of `Taskman` is, but it is a mechanism available since stone age and it will always work. That's your entry point: set your application as that (it has to be an executable), and that executable probably injects `explorer.exe` with some DLL (via `CreateRemoteThread`/`LoadLibraryW`) that contains our code, or does it via shell code or whatever... to minimize the racing (normally, when your application starts running, `explorer.exe` also continues its execution and startup flow - you kind of don't want that; ideally, `explorer.exe` should wait until you are done doing the initial setup and patching whatever things have to be patched from that point on), so, to drastically minimize this racing, 2 techniques that I can think of:
    * Attach yourself as a debugger to `explorer.exe` with `DebugActiveProcess`; this will suspend all threads in `explorer.exe`; we setup EP (patch the memory in various ways, mainly, and set up some worker threads) and then we detach with `DebugActiveProcessStop` which will resume the process. This has the limitation that only one debugger can be attached at a certain time - a theoretical limitation mainly, in practice whoever does that is plenty aware of that, probably
    * Use some undocumented stuff from `ntdll.dll`, like `NtSuspendProcess` and `NtResumeProcess` in the same manner as described above basically.

So yeah, runtime hooking is tricky, because it has to be done at the right time and is potentially racy. In this case, it has to be performed early in the lifetime of `explorer.exe`; you cannot just drop a shortcut to EP in `shell:startup` and have it load at some point after log on - at that point, it is way too late, not to mention there is a delay at logon which EP also has to fix =)))

The other methods? Idk, this one works just fine, is very reliable, admin access for install is not a concern for me, installation procedure is very easy, imo, like, that can be easier than copying a file...? That some people are at the intersection of these 2 Venn diagrams is unfortunate, but what can you do:
* people that do not read the README which tells users how to overcome the "File in use" error
* people that do not have enough tech knowledge to anticipate why that may happen and knowing how to resolve it without needing to read the README

Finally, regarding `StartMenuExperienceHost.exe`, initially, idk if you remember, at some point when EP was much younger, it injected that by dropping EP in `C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy` or something like that (the path where `StartMenuExperienceHost.exe` is located), also named `dxgi.dll` and it used basically the same mechanism. I changed to the current solution because:

* It was cumbersome to update, as you had to replace stuff in 2 places, one being this very obscure location - on hindsight, the Start menu code is not that frequently updated, but whatever...
* Racing or being very early is not a concern here - the current tweaks do not need to take effect before the menu is created; I just override a couple of functions and that's it, it can be done whenever.

So considering that, hooking at runtime was natural; it's also relatively easy, there are plenty of techniques. This stupid issue with `ERROR_ACCESS_DENIED` only happens for these blessed Microsoft executables and is a poor attempt at a security mechanism, probably. If you are anyway allowed to run code in a foreign process, denying some library calls is futile. Anyway, I will fix this eventually as well, I was actually more interested in figuring out why it is happening, as the fix I already know, as I said, implementing a custom loader. What I am more curious but don't know how to find out is why this happens at all... the solution sounds complicated? Check the latest fix for the window switcher not identifying correctly the key above `Tab` and how much over engineering had to be done there to receive a fucking notification when the input language is changed by the user... it's Windows/Microsoft.

Remember the * at the top? Yeah, well, even when unelevated, some apps still are more priviledged. On one hand, there are protected processes light which is another topic, but besides that, on the other hand, in yet another poor attempt at some form of "security" or capabilities, Microsoft restricts the usage of certain APIs to only executables signed with their certificate - for example, `CreateWindowInBand` which allows creating windows in other bands (bands are groups of windows at the same z-order - that's how `osk.exe` or `taskmgr.exe` can appear on top of other apps, they are simply run in the `ZBID_SYSTEM_TOOLS` band, while regular apps run in `ZBID_DESKTOP`, or how the volume/brightness sliders, the Start menu etc appear in front). This, again, is pretty stupid, as on one hand, these APIs are already harmless and pranksters can still annoy people by creating windows on top in the regular band and still annoy users, for example, and on the other hand, injecting Microsoft-signed processes is still permitted, so like... one just creates a thread in a process of a Microsoft-signed executable and then can use the APIs just fine... maybe a permissions model is needed, but I don't really think so in this case honestly, but anyway, not this poor attempt.

Why don't I make separate DLLs for each component? Why don't I make a separate EXE for configuration? Idk, I like having a single executable that does it all, it's also just easier to download, there is a single file one needs: `dxgi.dll` and you're off to the races!

Maybe I should pin this answer somewhere, it offers some insight about some particular choices regarding the architecture of EP. Next time, maybe we talk about symbols, that's another big topic of interest. Or even the window switcher stuff... Maybe I should host an AMA for people interested in technical stuff =)))) anyway, as I said multiple times, this project's primary raison d'etre is educational, I want to learn stuff and hope that people also find this as a good resource to develop their skill set and learn things in these areas.

**Comment by CrendKing** [comment]
You could make an wiki entry of this reply.

Also, [`ReplaceFileW`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-replacefilew) automatically rename the target file with a "~RF*.TMP" suffix if it's in use, which helps me update EP with a script.

**Comment by valinet** [comment]
> 
> 
> You could make an wiki entry of this reply.

True.

> 
> Also, [`ReplaceFileW`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-replacefilew) automatically rename the target file with a "~RF*.TMP" suffix if it's in use, which helps me update EP with a script.

Yeah, nice. Or even doing it 2 steps, it doesn't take that much time...

**Comment by valinet** [comment]
So, a resolution about this issue: the latest version brings quite a few improvements, including a setup program and an updater; thus, things being automatic now, I reverted back to injecting Start by placing `dxgi.dll` in its folder as well. This, as reported previously, seems to solve the problem, and Start is now injected reliably, enabling the functionality exposed via the configuration interface.

Thus, even though not solved as originally envisioned, this works very well for now and has no practical disadvantages compared to the other method, so I think it is an ok fix. Thus, I consider this issue and the related ones solved.

Thanks for the help, support and patience.
