### ISSUE TITLE
Too many flags on VIRUSTOTAL

### ISSUE THREAD

**Issue by Objectivite** [valinet/ExplorerPatcher#3008]
Hello,

Would you be able to get the latest version of Explorer Patcher cleared up on  VIRUSTOTAL.

You may not realize but your extension is used extensively in business environments.  We use it in a business environment, and in a business environment we can't just install something that gets flagged up by MANY engines on VirusTotal and tell management  _"Oh, it's OK - the developer says it is false positives"._  **In fact, even home users would be totally foolish to simply go on the say-so of the developer - it is just common sense.**  That's for starters - the second issue is that if a user has one of those antivirus programs, Explorer Patcher does not get installed - this is what happened to me today when I tried to install it on a test system despite the red flags on VirusTotal.

I am writing this long piece because the last time I raised this issue, half a year ago, that was the response I received.  I totally respect that you are not getting paid for this, I get that (and, personally, I would pay for it), but for me the ethos of developing software should include, in 2024, the will to ensure that anyone who uses the software feels safe.

The last two versions of Explorer Patcher have fared badly on VirusTotal - as mentioned above, I believe that as part of your development, your workflow should include ensuring that it does not get flagged up by the reputable AV engines.  I specifically emphasize the reputable engines - I am not concerned about the disreputable ones that I have made a list of.  I have highlighted on the screenshots below the reputable AV engines - I didn't install the version before last because as you can see below it was RED everywhere.  Thankfully your last version only has two concerns :  Webroot SecureAnywhere Corporate (which I use), and Sophos.

![image](https://github.com/valinet/ExplorerPatcher/assets/89191739/d41dbae6-35e2-4dbd-aaf2-1ebd99c36011)

![image](https://github.com/valinet/ExplorerPatcher/assets/89191739/3dffe5b9-f75a-4a3a-a872-4cc36c73df4e)

Many Thanks,

O.

**Comment by Amrsatrio** [comment]
I have some things to explain here. Sorry to have stirred you up.

1. I have released a new version: 64.1 and 64.2. 64.1 is currently spreading because I've set it as a release. It currently [has 3 detections](https://www.virustotal.com/gui/file/167f90fad0d3df4e2bfd4a6b07e459a6e414f63fa20e473aedc8c82f3b21eaef/detection), as you see. This never went past 3 detections so so far a good thing compared to the flopped 63.2 and 63.3.
2. 63.2 and 63.3 all began with 3 detections, they only rose as the exes are spread. 
3. How are we supposed to get Sophos's **Machine Learning models** and Webroot to unflag us as malware, I mean, if you see how this software works, it's putting DLLs into the folders of system files which is maybe what a typical malware would to to achieve persistence. If we were to employ a VirusTotal check then theoretically there are no more updates that we can make.
4. [Check 62.2 out](https://www.virustotal.com/gui/file/e44790e25db09d1fdcaa1b4a8e868a31d646a260c9df4923aea7be8efa0d8e1d/detection), the release from December 2023 it has 2 detections as well although they are not from the top vendors you highlighted. I am pretty sure people submitted false positive reports to Sophos for instance to have their models trained not to include EP. But as EP gets updates, new EXEs are built, are we supposed to send them our new EXE every time? I think it's too much to achieve zero detections on VT, if you look closer at how the software works.
5. Once the next update (24H2) has dropped, I'm afraid to say that this software will now be dangerous to be used in a business environment. Microsoft does NOT want us to use the old taskbar anymore, and they have crippled it to the point it crashes Explorer. Reimplementation is the only way, yet they still really like to make changes on the taskbar, breaking the code interfaces, therefore causing crashes after updates and [making people make issues with "this is a serious bug!"](https://github.com/valinet/ExplorerPatcher/issues/3002). Microsoft has crippled too much stuff leading complex solutions and patches that have to be made in order to have a working experience again.

**Comment by Objectivite** [comment]
Hi,

We write software ourselves and we fall foul of AVs sometimes too. There is a mechanism whereby you can report false positives to the AV providers - we use it, you can even do it through VirusTotal by registering with them.

As to your second and third replies : you go to the market and guy wants to sell you a second-hand motorbike. You ask for service history, and the guy says "Why" - everyone visiting this market can see this motorbike, can walk around it, can touch it - you just have to trust me it is good.


O.

**Comment by Objectivite** [comment]
Well, your "very special" customer service skills have had a very beneficial effects - it's forced me to create my own sets of REG files to set the settings I was using Explorer Patcher for, and then simply write a quick user interface to action them at will, and I no longer need Explorer Patcher

Some great silver lining.

So, **Thank You !**

O.

**Comment by Amrsatrio** [comment]
I'm not here for customer service 🤪 I'm here for fixing fixable  bugs and crashes users are experiencing. You do you though. See ya!
