### ISSUE TITLE
Clearing Anti-Virus Verifications

### ISSUE THREAD

**Issue by Cr8zyIvan** [valinet/ExplorerPatcher#3011]
I use your App on every machine that I use, that has Win11. It's seriously a game changer. At work however, and unfortunately, I am subject to outside verifications, checks and balances. 

I can't install the new ExplorerPatcher Update until my IT department clears it. They tell me they use virustotal.com as a first step verification. As of today, ExplorerPatcher, the GitHub URL passes the verification, but the installation file "ep_setup.exe" is flagged by 3 providers. 

for the last update, I had to wait a week or two for the ExplorerPatcher Flags to get cleared. Perhaps this is totally out of your control, I have limited knowledge on how all this works. In the case that there is something that can be done, I raise the issue here. Modification of the Script perhaps, or specific tests these Providers might be able to execute to clear ExplorerPatcher? I don't know.

I fear the day I might have to revert to the Win11 default Taskbar. And also, awesome job with ExplorerPatcher by the way. I believe it to be appreciated by an army of users.

Thanks, Cheers!

**Comment by Amrsatrio** [comment]
Yeah, there is nothing we can do. We drop dxgi.dll in C:\Windows and that's enough to trigger Cynet's detections since EP was born. Take a look at the [VT detection report of 56.3](https://www.virustotal.com/gui/file/08a5017e3119978abd3a71519613e94feff9890a80b2d8aadd31e2e55c8cf120) which was the last version before I jumped in, it's still detected by 1 vendor which is Cynet. I assume your IT department won't allow it as well. In that case unfortunately you cannot use EP at work :(

**Comment by Amrsatrio** [comment]
Also take a look at the [Sophos analysis results of 64.1](https://intelix.sophos.com/report/b209b683cf3a4b19be4db11fe786528e), looks like my addition of Russian translations contributed into the factors. Weird...

**Comment by valinet** [comment]
> Also take a look at the [Sophos analysis results of 64.1](https://intelix.sophos.com/report/b209b683cf3a4b19be4db11fe786528e), looks like my addition of Russian translations contributed into the factors. Weird...

Not really that weird: https://www.blackhillsinfosec.com/bypass-anti-virus-run-mimikatz/
