### ISSUE TITLE
System Tray Icons not following settings in Windows 10 Mode.

### ISSUE THREAD

**Issue by Mohsyn** [valinet/ExplorerPatcher#3031]
When using windows 10 taskbar mode:

1. Only System Icons show on Tray. Regular Icons do not show irrespective of taskbar orientation.
2. Only way to show app icons in Tray is to go to "Notification Area Icons" and check "Always show all icons and notification on taskbar" (which is weird because of too many icons clogging up tray area)

Would kindly request that system tray icons to respect custom icon visibility settings.

PS: Copilot icon is also invisible in windows 10 mode

**Comment by Amrsatrio** [comment]
In Windows 11 22H2 build 22621.1344 (from around March 2023), the system tray in the new taskbar has been overhauled as well as the backend for storing the tray icons information. Therefore the settings app which contains the updated code does not have any effect on the tray icons anymore.

However as a workaround you can drag the icons from the hidden icons popup to the taskbar. This feature has been since Windows 7.

I haven't been motivated to make a fix for this either because of that workaround that works, but you can keep this open so that I can be reminded of it once I have made a fix in the (distant) future.

**Comment by michaelkuzmin** [comment]
@Amrsatrio thank you, dragging worked. Except for the "Contol Center" icon. How can I hide that one?

**Comment by tallman69** [comment]
In the ExplorerPatcher Properties app, in the System tray tab there is a setting to hide or show the Control Center button.
