### ISSUE TITLE
Start menu sometimes doesn't open on build 22000.318

### ISSUE THREAD

**Issue by DavidIlie** [valinet/ExplorerPatcher#306]
Hey everyone,

I've been running ExplorerPatcher for a couple of weeks on my main PC and decided to upgrade my laptop to windows 11 and install ExplorerPatcher there too. However, there is a problem.

When I startup the computer, there is around a 90% chance that the start menu won't open, and that I would have to restart or sign out from the account to be able to get it working.

If it helps my laptop model is an XPS 13 9310 and I am running the latest build of Windows 11 stable with all the correct drivers.

Any help would be appreciated!

**Comment by valinet** [comment]
Hi

Hooking the Windows 11 Start menu apparently is more problematic under certain unknown circumstances because Microsoft decided so. Or they half implemented some “security” feature, I don’t really know, a technical discussion is still underway here: https://github.com/valinet/ExplorerPatcher/issues/299

Some generic pointers:
* Try disabling the patcher for Start menu from Properties and see if the problem persists: “Properties” - “Start menu” - “ Enable Start menu support”
* Try enabling the console from Properties - Advanced and see if some text like “HOOKED START MENU” appears at startup in the debug console that will be shown (of course, do this with the setting “Enable Start menu support” enabled)
* Try taking ownership of the folder where Start is located: `C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy`

If it works without EP support for it, then yeah, idk what else to suggest, injecting Start is sometimes problematic for God knows what reason I am looking into. It is hard though to test on a variety of hardware, as I have only an XPS 15 7590 on which I develop, a Ryzen 5900X based desktop I test also from time to time and a couple of virtual machines.

Thanks

**Comment by DavidIlie** [comment]
I did all the 3 and still the same problem, the console does say "HOOKED START MENU" even when the start menu doesn't work.

**Comment by valinet** [comment]
So, if you disable Start menu support, it still does not work?
