### ISSUE TITLE
Update loop for ever... KB5035942

### ISSUE THREAD

**Issue by gorillale** [valinet/ExplorerPatcher#3061]
When updating KB5035942 Windows 11, I have a permanent loop at "update". No percentage is displayed anymore, it just loops forever without any progress. After restoring the C drive, Explorer Patcher was removed. Now here's the update...

**Comment by Amrsatrio** [comment]
I've never had issues with update installation on my devices with EP installed, like ever since I first installed in 2022.

**Comment by gorillale** [comment]
After the update I reinstalled the EP

I don't understand why Microsoft is so aggressive and simply doesn't want you to be able to work properly again. 
Touch and tablet displays should be adjustable, so we would have our toolbar again.

As a developer you can no longer work with Win11, it's just a disabled home and I totally regret switching from Win10. and I've definitely had enough and am thinking about whether it would be better to install Linux on the master partition. 
In any case, I only buy programs that can run on Windows and Linux. 
because the day of Linux will come, definitely!! 
That can't be the case anymore.

Thanks for the great EP tool!
Long live the EP!

**Comment by pyrates999** [comment]
That is a preview update: https://support.microsoft.com/en-us/topic/march-26-2024-kb5035942-os-builds-22621-3374-and-22631-3374-preview-3ad9affc-1a91-4fcb-8f98-1fe3be91d8df

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by pyrates999** [comment]
You will still get offered those preview updates.  They just won't automatically install themselves.  You must resist the urge to install any updates that are being prompted to be downloaded.  You got it installed because you chose to download and install it.

**Comment by gorillale** [comment]
Yes, thanks. Weird update philosophy has MS.

**Comment by goshante** [comment]
Just never use something later than 22H2 build. This is the most usable version of Windows 11, without trash like copilot and other shit like preventing of 3rd party UI customization
