### ISSUE TITLE
"Expand to current folder" in Explorer doesn't work

### ISSUE THREAD

**Issue by bonanzaeducation** [valinet/ExplorerPatcher#3079]
(I'm using Swedish windows so maybe the exact phrase is different than in the heading? In swedish it is "Utöka till aktuell mapp")

Using Windows 11 Pro, 23H2
In a newly openen explorer window, "Expand to current folder" in nav menu doesn't expand to current filder until you de-select the option and re-select it again.

**Comment by pyrates999** [comment]
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by bonanzaeducation** [comment]
1. Winver: 
![winver](https://github.com/valinet/ExplorerPatcher/assets/117730785/ec5d8b77-beed-4e99-9eef-41bcab8caf17)
2. Explorerpatcher:
![expl-patcher](https://github.com/valinet/ExplorerPatcher/assets/117730785/c75bd3bc-74ac-4659-a671-c4daf0099240)
3. 
[ExplorerPatcher_22621.3296.64.1.reg.txt](https://github.com/valinet/ExplorerPatcher/files/14834935/ExplorerPatcher_22621.3296.64.1.reg.txt)

4. No other UI modifiers.

**Comment by pyrates999** [comment]
Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.

**Comment by marsa47** [comment]
Hi,

I just wanted to mention, that unfortunately this problem has nothing to do with Explorer Patcher. It is a known problem of Windows Explorer itself, since few months ago.

Currently the only working solution is to enable the "Show all folders" option too, and then "Expand to current folder" will work again. Problem is, the folders tree becomes cluttered.

Here is a topic on MS support forums about this issue:
https://answers.microsoft.com/en-us/windows/forum/windows_11-wintop_update/how-to-re-enable-the-expand-to-open-folder-option/bd8042f9-f71b-400b-9540-ca10b89b1ff8

**Comment by bonanzaeducation** [comment]
Thanks, Marsa! 👍
