### ISSUE TITLE
Start Menu opens like in Win11 when it is set to Win10

### ISSUE THREAD

**Issue by halidsert** [valinet/ExplorerPatcher#3087]
This is a fresh Win11 install and the start menu looks like below. I tried the latest release and the pre-releases but couldn't fix it. I tried restoring defaults but that didn't help either. My OS build is 22631.3374 . Am I missing something here or is there a bug?

![image](https://github.com/valinet/ExplorerPatcher/assets/32898039/5c13f59c-6839-4278-a63a-309c9772820c)

**Comment by pyrates999** [comment]
Don't install preview updates: https://support.microsoft.com/en-au/topic/march-26-2024-kb5035942-os-builds-22621-3374-and-22631-3374-preview-3ad9affc-1a91-4fcb-8f98-1fe3be91d8df

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by halidsert** [comment]
I have realised that the start menu was on Win10 style. I mistook start button style for start menu style and I'm sorry.
