### ISSUE TITLE
Weather widget doesn't work properly in Windows 10 mode taskbar

### ISSUE THREAD

**Issue by ShiranuiAegis** [valinet/ExplorerPatcher#3115]
The Weather widget does not work properly in the Windows 10 Mode taskbar, and no icon is shown on the taskbar after opening the Weather widget.

my Windows version :22631.3374

**Comment by pyrates999** [comment]
you're running a preview update: https://support.microsoft.com/en-au/topic/march-26-2024-kb5035942-os-builds-22621-3374-and-22631-3374-preview-3ad9affc-1a91-4fcb-8f98-1fe3be91d8df

Please install latest preview update of EP.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by bbmaster123** [comment]
running same exact build, working fine on my windows 10 taskbar. Probably just need to turn off DeprecatePeopleInTaskbar with vivetool.
If it helps, here's the whole list of features from 22631.3374
[22631.3374.txt](https://github.com/valinet/ExplorerPatcher/files/14919320/22631.3374.txt)
cheers :)
