### ISSUE TITLE
Volume Popup not working

### ISSUE THREAD

**Issue by gh-log** [valinet/ExplorerPatcher#3119]
Volume Popup with Media Keys changes volume but doesnt show volume level changes.

EP
22621.3296.64.1

WIN 11
22631.3374

**Comment by pyrates999** [comment]
You got a preview update installed.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

The April windows updates have been released as well.  So please update to it.

And try to install the pre-release version of EP after you do this.

**Comment by pyrates999** [comment]
I know, but it's easier to tell them not to install preview updates in the first place and let the developers like you only install them.

**Comment by gh-log** [comment]
Im DevOps.

Will try EP pre-release.

**Comment by Amrsatrio** [comment]
Prerelease shouldn't make a difference because I did not touch the code for patching the volume popups between 64.1 and 64.3.

Also, please paste the [HC] lines in your EP console (EP properties > Advanced > Enable console > Restart Explorer)

**Comment by Amrsatrio** [comment]
Any updates on this issue?
