### ISSUE TITLE
Enable SysListView32 in folder views causes dark file name text on dark background

### ISSUE THREAD

**Issue by chip33** [valinet/ExplorerPatcher#316]
Hi, thanks for enabling Win 11 to actually be usable!
Using 22000.318.36.1 on a fairly clean win 10 upgrade to win 11 22000.318 using Glow (dark) theme at 4K 350% dpi scaling
I tried the new  Enable legacy list view feature and the File Explorer filenames become illegible dark text on a dark background. Also (possibly not important) my desktop icons become unarranged every time the new setting is applied and require repositioning.
Just thought I should let you know. I suspect this is just an incompatibility between legacy list view and dark themes so it is not really a bug but a feature for customizers.
However, if a setting will break usability for the many users with a dark theme (and possibly cause support questions) is it not better to just list it as an optional user choice [registry configuration setting](https://github.com/valinet/ExplorerPatcher/issues/9)?
Steps to reproduce, unless it is a quirk of my setup, just use a dark theme and Enable Legacy list view in EP properties and Restart File Explorer.
![Enable legacy List view (Medium)](https://user-images.githubusercontent.com/48499740/141290430-6f36c87a-d50d-4a26-98cc-4aaae2f71fee.png)

I really appreciate all the work and interesting coding you are doing to achieve this. It blows my mind that MS have made this necessary. I am a long time user of the Quick Launch toolbar so that absence alone made Win 11 unusable for me.

**Comment by Anixx** [comment]
Do you experience the same problems when you install [Folder Options X](https://github.com/T800G/FolderOptionsX) and check any of the first 3 options?

**Comment by chip33** [comment]
> Removal of this setting from the GUI would mean removal of it altogether, because Explorer Patcher does not do anything except changing that registry value.

Hi, yes I am suggesting it be removed from the GUI as problematic and just have the registry edit to Enable SysListView32 in folder views linked to in the [FAQ](https://github.com/valinet/ExplorerPatcher/issues/9) for reference for those that may find it useful.

**Comment by Anixx** [comment]
It seems you are just complaining to remove an option for which people were searching a solution for years, were writing complicated programs to implement and all that only because it looks bad with your theme (even though you can uncheck it any time).

**Comment by Anixx** [comment]
Why you do not go to the Folder options X github then and not ask to delete that program altogether?

**Comment by chip33** [comment]
Smiles.. no answer to that.

**Comment by Anixx** [comment]
Well, this is legacy SysListView with tark theme. Just change the font color:
![изображение](https://user-images.githubusercontent.com/1271736/141324872-c82ac311-e091-4033-85f3-518a51dd81c5.png)

**Comment by chip33** [comment]
> Well, this is legacy SysListView with tark theme. Just change the font color: ![изображение](https://user-images.githubusercontent.com/1271736/141324872-c82ac311-e091-4033-85f3-518a51dd81c5.png)

Hi, yes, I did think maybe Valinet might implement a font colour change if a dark theme can be detected but that is up to him as it his work to do it if he thinks it is a good addition.

**Comment by Anixx** [comment]
As to the desktop icons, I have no idea really, because it uses SysListView control anyway by default.

**Comment by Anixx** [comment]
The dark theme is not even fully implemented in Windows 11 yet: you have dark theme in half of windows and light theme in others. If ExplorerPatcher would implement automatic font color change, there is a chance that it would fix explorer but break Explorer's dialogs, where the background is white.

**Comment by chip33** [comment]
> The dark theme is not even fully implemented in Windows 11 yet: you have dark theme in half of windows and light theme in others. If ExplorerPatcher would implement automatic font color change, there is a chance that it would fix explorer but break Explorer's dialogs, where the background is white.

Fair point, I don't have the knowledge of exactly where the tweak is applied.

**Comment by Anixx** [comment]
> Fair point, I don't have the knowledge of exactly where the tweak is applied.

What "tweak" are you referring to?

**Comment by chip33** [comment]
> > Fair point, I don't have the knowledge of exactly where the tweak is applied.
> 
> What "tweak" are you referring to?

"Enable SysListView32 in folder views" and your response to the effectiveness of changing (tweaking) font colour to white to match a dark theme.

**Comment by Anixx** [comment]
My point was completely unrelated to this tweak. My point is, the dark themes is a completely broken (or unfinished) API in Windows 11.
Before there were dark and light themes that affected all programs via common colors. In Windows 11 they added (as of yet) unfinished API that instead of providing colors just tells the programs whether the theme is dark or not. And those programs that are unaware of this API simply do not change appearance. And this affects even Explorer's own dialog windows. On the screenshot you can see the status bar provided by ClassicExplorer which is displayed light even though the "dark mode" is active. If we make the font white, it will be invisible on the Classic Explorer status bar, for instance.

**Comment by chip33** [comment]
> On the screenshot you can see the status bar provided by ClassicExplorer which is displayed light even though the "dark mode" is active.

So you show a dark theme with legacy SysListView32 and the font changed to white against the dark background but the text in the status bar remains dark. 
The question is as you said will it break legibility somewhere else if it were implemented or am I being overly concerned about something that may be more trouble than it is worth.
I am happy to just point it out and see what is decided.

**Comment by Anixx** [comment]
> The question is as you said will it break legibility somewhere else if it were implemented

Yes. As I said, File Explorer's own dialogs are completely unaware of this new dark/light API  and show white background even under dark mode:
![изображение](https://user-images.githubusercontent.com/1271736/141331450-993873d0-e0cc-47c3-a22c-a0ad19404671.png)

**Comment by Anixx** [comment]
> The question is as you said will it break legibility somewhere else

What is ALREADY broken is the Win11 darek/light APIs, not the control that has been around since Windows95. Even if you do not enable SysListView in Explorer, you will encounter it in other programs and will similarly see font color inconsistency if you use dark mode.

**Comment by Anixx** [comment]
> I am happy to just point it out and see what is decided.

It is due to users like you who lobbied for removal of functionality and customizability we are where we are with Windows development.

**Comment by chip33** [comment]
> > The question is as you said will it break legibility somewhere else
> 
> What is ALREADY broken is the Win11 dark/light APIs, not the control that has been around since Windows95. Even if you do not enable SysListView in Explorer, you will encounter it in other programs and will similarly see font color inconsistency if you use dark mode.

Yes, it's okay this issue has been closed anyway. Just glad this program exists to patch up what MS has given us.

**Comment by Anixx** [comment]
When people bother only about their own use case, I call it "Linux syndrome". Because if you remove an option that is used only by 1%, then eventually you will find out that 99% have one such option that they need but was not implemented because the others do not need it and break it.

**Comment by chip33** [comment]
> > I am happy to just point it out and see what is decided.
> 
> It is due to users like you who lobbied for removal of functionality and customizability we are where we are with Windows development.

I  should not respond to this, but that is just rude and arrogant. I merely pointed out some issues around Enable SysListView32 in folder views. I did not come here to have you be rude to me.

**Comment by Anixx** [comment]
When people bother only about their own use case, I call it "Linux syndrome". Because if you remove an option that is used only by 1%, then eventually you will find out that 99% have one such option that they need but was not implemented because the others do not need it and break it.

**Comment by Anixx** [comment]
> I merely pointed out some issues around Enable SysListView32 in folder views.

As I can tell, you asked to remove functionality, used by others.

**Comment by chip33** [comment]
> When people bother only about their own use case, I call it "Linux syndrome". Because if you remove an option that is used only by 1%, then eventually you will find out that 99% have one such option that they need but was not implemented because the others do not need it and break it.

Call it what you like, it does not stop you acting like you know it all when in truth, none of us do.

**Comment by chip33** [comment]
> > I merely pointed out some issues around Enable SysListView32 in folder views.
> 
> As I can tell, you asked to remove functionality, used by others.

Or, to fix the desktop icon unsorting, or to fix the dark text if practical, or to maybe put a note that this setting is incompatible with dark themes.
I was open to what solution was decided.
Your rudeness and unpleasant attitude will probably outlast Windows 11.

**Comment by Anixx** [comment]
> to maybe put a note that this setting is incompatible with dark themes.

You can use grey or whatever font text. The dark mode (not themes) is rarely with what compatible, though (as of now). It is officially unfinished.

**Comment by valinet** [comment]
Hey

I closed the issue because it is not really an issue, but rather an observation. Belonged better to discussions.

The way this works is it just disables the COM component that is responsible for creating the new list view, and then in turn the old one is created by Explorer as a fallback solution. It does not add functionality to that, it just comes in the state and with the compatibility Microsoft left it in the system. Indeed, there may be issues, as @chip33 has pointed out, but I won;t spend time fixing those, because I think it is beyond the point of this program. This, again, is some niche functionality which has an alternative which is the currently supported one. Idk, I haven't made a motto out of my life to fix literally everything that is in some kind of a broken state in Windows, as that is a never ending work, basically. I just thought this option is indeed interesting and that some people might find a use case for it, after @Anixx pointed me at the thread where this was described. Indeed, as it may cause some issues under certain configurations on usual setups, I may consider moving it to the "Advanced" section of the configuration GUI in some later update.

Please do not fight for nothing. @Anixx, chill out a bit, please, no one is removing anything, I haven't added it just to remove it, of course I am trying to find a solution that will balance and take into account both concerns. Try a bit to understand the other side as well, it's like yesterday with me temporarily removing the shell extension builds from releases, if people have problems and flood the issues tracker with similar reports, of course I have to hide that a bit until I find a solution for it. Also, I am a single person and human, I cannot work on this non-stop, but I think I am more than giving it my best shot. Similarly here, I understand the concern of @chip33, it's valid, so a sensible solution of moving it less out of sight I think is acceptable.

> It is due to users like you who lobbied for removal of functionality and customizability we are where we are with Windows development.
While the statement is questionable, blaming him is even more questionable, like, do you know he asked Microsoft specifically to remove this or that...? And be serious, it's not the users, it's just management decisions. It's way easier to maintain a single code base, options just add complexity to the development team, that's the cold hard truth, look at EP and how many issues people raise just because it provides options. I can't deny that, it's just something one is willing to accept and do the work to maintain all the options, or not. It's Microsoft's OS, they can do whatever they want to it after all, no one forces us to use it or a particular version. It's the same everywhere, even here, I reserve the liberty to steer this project any direction I see fit, and offer viable and real alternatives for anyone maybe not agreeing with a particular choice or direction, in th way of forking and maintaining a separate copy of it tailored to one's needs, which is so much more than a lot of other software does not provide.

> When people bother only about their own use case, I call it "Linux syndrome"
Like, I don't want to be rude or anything a well, but you kind of do exactly what you point to in your statement. We had this talk yesterday as well, you gave me a reply that disregarded any other concerns, just because it impeded for a little while the process of enabling the classic theme for your use case. I am sorry, but that's the truth. And that, considering that I have ALWAYS been supportive and helped you with your use case. I indeed have this unfortunate feeling that there is a lack of reciprocity between us and I do not understand why, honestly. Would it have been better to just not bother...? Again, as I said, I think I am doing more than the reasonable in trying to help everyone as much as I can. But I expect people to behave in good faith as well, otherwise it just feels stupid and it becomes a waste of time for me. And no need to mislabel it with "Linux syndrome", it does not make any sense. What does Linux have to do with all of this conversation? I think it is a well maintained project and I don't understand why this unfair association.

> What is ALREADY broken is the Win11 dark/light APIs, not the control that has been around since Windows95.
Nah, I think they are an attempt at providing a solution without breaking legacy applications. I don't understand why you say they are broken. Of course the newer API uses separate configuration parameters, so it does not affect older apps, and of course older unaware components may break if you somehow force the new behavior on them, which was the case here.

Also, in general, themes are bad for application developers. I am sorry, but that is the truth. I mean, indeed, the Windows 95 way of having apps use the system color palette and skinning everything in one go by changing it is indeed idealistic and nice, but it does not work in the real world, unfortunately. See, application developers want branding, many want to provide an experience that is recognizably theirs. Themes break that, by making everything look the same. It also limits the possibilities one has when designing an interface: you cannot have the background of the app red, you have to respect what the user set as a background color. Indeed, one approach is consistent, but against the liberty of the others. In the end, many apps bypassed that for reasons described above, so Microsoft eventually just dropped insisting on that altogether, providing some defaults in order to keep legacy software looking fine, and then each app is expected to skin itself however it sees fit. Idk, there are approaches and approaches, but a uniform look is hard to achieve when the software involved comes from so many decentralized places. And one more thing: application developers also DO NOT like themes being applied to their products either, because it breaks the visual identity they strive to achieve, and may also introduce bugs because the upstream did not develop considering that particular configuration. An operating system is supposed to offer a level playing field and an environment in which software to run and express their functionality without imposing unreasonable conditions on them. In the past years/decades, it had become more and more perceived that theming is an unreasonable condition placed on a software's ability to freely manifest itself when run by the user, i.e. it limits the range of experiences possible. It's a complicated talk, but it is worth reading into the subject and trying to understand it from both sides of the argument:

Not to mention, there is also a need to provide certain advancements in the technology altogether: for example, DWM has become mandatory since Windows 8+, since certain experiences need it in order to run at the efficiency or performance level people expect nowadays. You wouldn't be able to have apps like Parsec without DWM, for example. Should they kept supporting running the interface without a compositor forever if it provides few use cases, if any? Similarly with making certain processor instructions mandatory, themes and whatever we can think of. Every functionality they keep around needs more maintenance. And at some point, so many experience rely on certain behaviors, that it does not make sense to keep certain modes still around. Do you run your OS without virtual memory support, for example, or do you run it in real mode?

Thanks

**Comment by chip33** [comment]
smiles, thanks Valinet, I am actually (or was ) an open source software developer for a well known media organiser application.
We had a forum where the users could suggest improvements and log bugs and I enjoyed picking up the ones that I could fix and making people happy.
I agree it was probably better as a discussion topic and I didn't mind at all if you decided to leave it as is.

**Comment by valinet** [comment]
Me too, I try to implement as much stuff as I can and help people as best as I can, while also attempting to somehow manage my time. If I find a doable solution for anything really, I don’t hesitate including it in.

Thanks

**Comment by chip33** [comment]
From a pleasing overall design point of view I agree that eventually this option could be less invitingly tucked away (in Advanced) as you said and maybe noted as having compatibility issues with the newer API.
That way its inevitably imperfect legacy behaviour is legitimised while still providing the functionality and clearly distinguished from the smooth operation of the other features of your application.

**Comment by Anixx** [comment]
This control is used in many apps, if your theme cannot handle it, it is imperfectness of your theme, not of ListView.

**Comment by chip33** [comment]
> This control is used in many apps, if your theme cannot handle it, it is imperfectness of your theme (or color scheme), not of ListView.

Annix, as Valinet explained this legacy ListView will not work perfectly with the modern Win 11 GUI and its included themes. However the feature is being kept in just as you requested.  I am not asking that it be removed, just saying that I agree with the explanation Valinet kindly gave and if he ever has the time I agree it would fit nicely in the Advanced section. I am going to sleep now. Be happy,

**Comment by Anixx** [comment]
Dark theme in modern GUI cannot work perfectly with ANY control. Because you have dark file manager and light dialogs, as I said. 
If you use light theme, everything looks good.

**Comment by chip33** [comment]
> Dark theme in modern GUI cannot work perfectly with ANY control. Because you have dark file manager and light dialogs, as I said. If you use light theme, everything looks good.

Smiles, I like a dark theme, call me weird, and I got bored of windows 95 a long time ago, This is my final comment on this thread. Sleep well.

**Comment by Anixx** [comment]
One can like a dark theme or not, but currently in Win11 the **dark mode** is inconsistent and one cannot make it consistent.

**Comment by valinet** [comment]
What’s the point of this talk anymore?

And not to mention that a thing not being implemented “everywhere” doesn’t mean that it doesn’t work.

I thought this place could be an inspiration and learning venue for interested people, not a place for useless chatting…

I want to work on great new stuff, not to waste time moderating a  discussion that doesn’t bring any value, sorry to say. This should have long been over. I wish people talked about technical stuff here in the same lengths or more as this discussion.

:(

**Comment by chip33** [comment]
> One can like a dark theme or not, but currently in Win11 the **dark mode** is inconsistent and one cannot make it consistent.

I do understand, I am also a little frustrated that the dark theming in Windows 11 is still so incomplete. It is a work in progress hopefully they will unify it one day.

**Comment by valinet** [comment]
I mean, you can talk, I don’t mind, I wish though to not invest the energy in arguing one another over looks which will always be a subjective matter. The main subject of the thread I consider solved in a more than reasonable way.

**Comment by chip33** [comment]
Yes, sorry Valinet, I left that last comment about the Advanced option just to say that seemed like a great solution if you ever got time. I meant well, I didn't know it would cause a reply and lead to this.

**Comment by valinet** [comment]
As I said, no worries, I don’t mind it, I am just sad seeing arguments and energy invested in subjective things and a lack of interest from some participants towards reaching a middle ground. Thank you.

**Comment by Avatar007z** [comment]
Hello, I am hitting this issue, but I after update of Windows and company Antivirus updates I can no longer run Explorer PAtcher in any form as the antivirus blocks it and the .dll files and almost everything it tries to do, so I no longer can change the "Legacy list view" setting. 
Despite my searches (I am not that good in coding) I could not find what registry should I set to disable the setting. I wwould greatly appreciate if someone could point me in the right direction.

**Comment by Avatar007z** [comment]
> > Hello, I am hitting this issue, but I after update of Windows and company Antivirus updates I can no longer run Explorer PAtcher in any form as the antivirus blocks it and the .dll files and almost everything it tries to do, so I no longer can change the "Legacy list view" setting. Despite my searches (I am not that good in coding) I could not find what registry should I set to disable the setting. I would greatly appreciate if someone could point me in the right direction. From the current thread I think i just need to manually disable SysListView32 .
> 
> It's right there in the release notes: https://github.com/valinet/ExplorerPatcher/releases

hhhm, I may be missing something, but just a search for SysListView32  does not find anything and I went as far back as page 9 in the release list. 
PS I do not have access to add exception to the antivirus application, but in the past it has never been an issue!

I knew about the warning for work machines, but I always used EP first on my personal machine or on a separate account to tested before proceeding with my main account. And to be honest most errors are tolerable even on work machine :D My problem is that I am not very productive with the new 11 taskbar behavior, but I am even less productive in Light mode or with black text on black background!

**Comment by pyrates999** [comment]
> > > Hello, I am hitting this issue, but I after update of Windows and company Antivirus updates I can no longer run Explorer PAtcher in any form as the antivirus blocks it and the .dll files and almost everything it tries to do, so I no longer can change the "Legacy list view" setting. Despite my searches (I am not that good in coding) I could not find what registry should I set to disable the setting. I would greatly appreciate if someone could point me in the right direction. From the current thread I think i just need to manually disable SysListView32 .
> > 
> > 
> > It's right there in the release notes: https://github.com/valinet/ExplorerPatcher/releases
> 
> hhhm, I may be missing something, but just a search for SysListView32 does not find anything and I went as far back as page 9 in the release list. PS I do not have access to add exception to the antivirus application, but in the past it has never been an issue!
> 
> I knew about the warning for work machines, but I always used EP first on my personal machine or on a separate account to tested before proceeding with my main account. And to be honest most errors are tolerable even on work machine :D My problem is that I am not very productive with the new 11 taskbar behavior, but I am even less productive in Light mode or with black text on black background!

It is not recommended to use EP on work machines where you do not have admin privileges and cannot add antivirus exceptions to: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation#%EF%B8%8F-warning---read-thoroughly-before-using
