### ISSUE TITLE
EP 22621.3527.65.1 Pre-release crashes W11 Explorer

### ISSUE THREAD

**Issue by markusb68** [valinet/ExplorerPatcher#3178]
EP 22621.3527.65.1 Pre-release crashes W11 Explorer
![image](https://github.com/valinet/ExplorerPatcher/assets/20417704/01d32c1d-575a-49ab-9ae1-fd1c417257d4)

**Comment by Amrsatrio** [comment]
Hi, sorry for the inconvenience. Does this crash happen on EP 64.1 and 64.3?

**Comment by Vikijaka** [comment]
Same here Win 11 Pro 23H2 Build22631.3447, coming from EP 22621.3296.64.2 due to being 64.3 unusable for being detected by WinDefender

What i did: 
Update via ...64.2 -> inf. crashing explorer.
"fixed" via ep_setup.exe /uninstall
trying again after restart ^loop

reinstall 64.2
export config
setting Config to default
deinstall via ep_setup.exe /uninstall
manually install of ....65.1
same loop as above -> explorer.exe cperma crashing over and over again

**Comment by Amrsatrio** [comment]
Those who are affected by the crashing issue, please post all pages of your Properties window (don't forget to set the language to English first).

**Comment by Menno5** [comment]
Same here. Went back to 64 (no Defender message, I have Kaspersky) and 64 runs fine.
This on Windows 11 Pro (22631.3447)

Windows log shows errors to Explorer.exe and to the module C:\WINDOWS\System32\ucrtbase.dll

**Comment by Amrsatrio** [comment]
Pulled the faulty prerelease. A new prerelease build which have it fixed is being built right now. Sorry for the inconvenience.
