### ISSUE TITLE
Windows 10 Taskbar does work on version 26100.1

### ISSUE THREAD

**Issue by account183892** [valinet/ExplorerPatcher#3187]
No reason to remove Windows 10 taskbar on new builds.

**Comment by pyrates999** [comment]
Microsoft is removing windows 10 taskbar, not EP.

Please close this as EP can't fix this once windows 10 taskbar is completely removed.

**Comment by Amrsatrio** [comment]
Do you know the news that EP and SAB are both blocked on 26100+? I've got confirmations that it's because of them fighting the DisableWin10Taskbar feature flag. So I've removed it in hopes of MS lifting the block.

> EP can fix this by patching system files to restore the taskbar

EP will never patch existing system files on disk. I've tried swapping explorer.exe with the one from 22621, it didn't work. Also tried swapping explorer.exe with the one from 19045, it was pretty buggy.

The reimplemented taskbar will come one day, just not this month or next month, it will be released once it no longer uses code from the 10 taskbar in explorer.exe.

**Comment by Amrsatrio** [comment]
I wouldn't say a taskbar without system tray a working taskbar.

**Comment by Anixx** [comment]
Can the tray be artificially invoked?

**Comment by pyrates999** [comment]
> Can the tray be artificially invoked?

https://github.com/valinet/ExplorerPatcher/wiki/Frequently-asked-questions#i-just-installed-explorerpatcher-but-my-taskbar-stays-the-stock-windows-11-taskbar-how-to-change-it-to-the-windows-10-one

please see this for more info: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

**Comment by Anixx** [comment]
Why are you posting it to me? I know about EP taskbar.

**Comment by pyrates999** [comment]
sorry :)
