### ISSUE TITLE
Can't open Properties

### ISSUE THREAD

**Issue by Julian070708** [valinet/ExplorerPatcher#319]
I deactivated the old Windows 10 Taskbar in the properties and now I can't open the properties anymore if i rightclick on the windows button

**Comment by valinet** [comment]
It's expected behavior, for now, at least. The Windows 11 Start button is different than the Windows 10 one. This application only changes the Windows 10 one. To display back the "Properties" GUI, run the following command which is also described in the README: `rundll32 C:\Windows\dxgi.dll,ZZGUI`.

Thanks

**Comment by Julian070708** [comment]
ok thank you
