### ISSUE TITLE
Start Menu Search Not working?

### ISSUE THREAD

**Issue by kentdtran** [valinet/ExplorerPatcher#3199]
I updated the latest version and the Start Menu Search doesnt work?

I click on start menu, then typing any search string will not search but just highlight the latest apps.
I cant type anything into the Search field.

![image](https://github.com/valinet/ExplorerPatcher/assets/64054027/35fcf693-bbfa-4bc9-817a-7e4048a94b08)

**Comment by Amrsatrio** [comment]
Please try uninstalling ExplorerPatcher and restarting your PC and see if the start menu search works. Then try installing ExplorerPatcher and see again if it works or breaks. I haven't had a single issue with search not working on my machines so can't really do much to fix this issue.

One thing to note, there was an issue before EP 64.1 where if you have Windows 10 taskbar enabled, "Let's finish setting up your PC" will crash repeatedly and the search menu will refuse to open. That has been fixed in EP 64.1 so that it will appear normally, allowing you to select "Remind me later" so that the search menu can open.

**Comment by kentdtran** [comment]
Thanks for that!
I uninstalled, restarted and the default menu was working.
Then I reinstalled the latest version and Search works now!

**Comment by Amrsatrio** [comment]
Alright, glad it worked! Feel free to reopen if the issue still persists.
