### ISSUE TITLE
update winows now nothing works

### ISSUE THREAD

**Issue by Davies1998** [valinet/ExplorerPatcher#3201]
since i've updated my window, my start menu as reset back to window 11 and can't seem to go back to it now, any idea?

**Comment by Fr0stX76** [comment]
Use the latest [pre-release](https://github.com/valinet/ExplorerPatcher/releases/download/22621.3527.65.1_d11445a/ep_setup.exe)

**Comment by pyrates999** [comment]
Stop installing preview updates.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.
