### ISSUE TITLE
Windows 10 Start menu style stopped working

### ISSUE THREAD

**Issue by msolla-ligno** [valinet/ExplorerPatcher#3236]
Suddenly after months working perfectly, today windows 10 start menú just stopped working
![imagen](https://github.com/valinet/ExplorerPatcher/assets/126880127/d1ea64f7-3494-4c0c-ad16-5c736c109160)

ExplorerPatcher version 22621.3296.64.1 (no pending updates at the moment)
Windows 11 23H2 (22631.3527)

**Comment by pyrates999** [comment]
You installed a preview update: https://support.microsoft.com/en-us/topic/april-23-2024-kb5036980-os-builds-22621-3527-and-22631-3527-preview-5a0d6c49-e42e-4eb4-8541-33a7139281ed

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

This was fixed with pre-releases after 22621.3296.64.1, and then released as a release here: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.2_c245b8f

**Comment by msolla-ligno** [comment]
Thanks you @pyrates999 , with this version works fine.
I had this setting off, I guess:
![imagen](https://github.com/valinet/ExplorerPatcher/assets/126880127/d1d5ba20-3c30-4ac0-839b-eda0df5048c8)

**Comment by msolla-ligno** [comment]
Oh, I see the "Get the latest updates as soon as available" option in windows updates settings.
I unchecked that. Thanks!!

**Comment by pyrates999** [comment]
You're welcome.
