### ISSUE TITLE
Return Windows 10 Taskbar on ExplorerPatcher on 24H2

### ISSUE THREAD

**Issue by DraganVictor14** [valinet/ExplorerPatcher#3257]
As you can see on the following links (news and posts) Windows 10 is working perfectly  whenyou have this feature id disabled (DisableWin10Taskbar).
If this feature id is turned on is enabled on build 26100 which it is Windows 11 24H2 RTM, we can easily disable this feature id using ViVeTool
Links:
https://www.neowin.net/news/windows-11-build-26002-adds-a-feature-id-that-breaks-the-old-windows-10-taskbar/

https://www.xda-developers.com/latest-windows-11-update-breaks-windows-10-taskbar-apps/

pic.twitter.com/OcPVRpSXoF

Now the developer to explain us why he removes it on ExplorerPatcher

**Comment by pyrates999** [comment]
Windows 11 24H2 hasn't been released yet, so it is not RTM.

**Comment by Amrsatrio** [comment]
No. It is not even usable. It does not have a system tray.

**Comment by phoenX80** [comment]
Yeah, on 26100.268 it is first intercepted by WinDefender and if you deactivate it it is intercepted via program "comaptibility". I am still trying to bypass this crap but haven't succeded yet.

**Comment by DraganVictor14** [comment]
> No. It is not even usable. It does not have a system tray.

Yes and it doesn't have more buttons (network/sound flyout  clock flyout and actin center)
But how to show these?

**Comment by Anixx** [comment]
Not having tray looks like a separate issue that definitely can be fixed. At least, it has a functional taskbar.

**Comment by Anixx** [comment]
Restoring support for Win10 taskbar in 24H2 is very important, because it would affect also IoT Enterprise LTSC and Windows Server 2025. The IoT Enterprise LTSC has support term of 10 years.

I think, MS did not remove the Win10 taskbar from 24H2 intentionally, so, there should be a way to re-enable the system tray as well.

Also, the notes on Windows Server 2025 say that it boots into Win11 shell "by default", which suggests that maybe booting into Win10 shell is also possible and supported.
