### ISSUE TITLE
Large icons on system tray on primary monitor

### ISSUE THREAD

**Issue by Isokub** [valinet/ExplorerPatcher#3299]
![Skärmbild 2024-05-20 132139](https://github.com/valinet/ExplorerPatcher/assets/157760002/be234559-7989-437f-884f-011175090513)

Today when I started my computer I saw that the taskbar was big. And that the start menu and systems icons had increased in height.
Only affects the primary monitor. On the other display the taskbar looks normal.
I've uninstalled and reinstalled and updated without any solution to the issue. I think it happened after the latest Windows update.

**Comment by pyrates999** [comment]
This isn't something caused by EP and has been around since windows 95 was released. Apparently you've never resized the taskbar in windows.

Right click on the taskbar and untick lock the taskbar.  You can now resize the taskbar.  To lock the taskbar again, right click on the taskbar and tick lock the taskbar.
