### ISSUE TITLE
Tray icon size is too small

### ISSUE THREAD

**Issue by peter8777555** [valinet/ExplorerPatcher#3349]
ExplorerPatcher : 22621.3527.65.5
OS : Windows 11 23H2 22631.3085

How to Change Size of Caption Buttons in Windows 10/11
https://www.tenforums.com/tutorials/79900-change-size-caption-buttons-windows-10-a.html

I set 
CaptionWidth=-120
CaptionHeight=-120

Tray icon size is too small.

If i un-install ExplorerPatcher,Tray icon size is OK.

**Comment by pyrates999** [comment]
Your windows version is from January 23/2024: https://support.microsoft.com/en-au/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

Then install the latest windows update excluding any preview updates.

**Comment by peter8777555** [comment]
> Your windows version is from January 23/2024: https://support.microsoft.com/en-au/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.
> 
> You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.
> 
> Then install the latest windows update excluding any preview updates.

I have installed the latest windows update to Windows 11 23H2 22631.3672

I set
CaptionWidth=-120
CaptionHeight=-120

Tray icon size is too small.

If i un-install ExplorerPatcher,Tray icon size is OK.

**Comment by pyrates999** [comment]
That would be a preview update: https://support.microsoft.com/en-us/topic/may-29-2024-kb5037853-os-builds-22621-3672-and-22631-3672-preview-dcf14fd8-84d6-4234-9d5b-784c319cd7cf

> Then install the latest windows update excluding any preview updates.

I said not to install preview updates.  But since you did, install the latest pre-release of EP now.

**Comment by peter8777555** [comment]
> That would be a preview update: https://support.microsoft.com/en-us/topic/may-29-2024-kb5037853-os-builds-22621-3672-and-22631-3672-preview-dcf14fd8-84d6-4234-9d5b-784c319cd7cf
> 
> > Then install the latest windows update excluding any preview updates.
> 
> I said not to install preview updates. But since you did, install the latest pre-release of EP now.

OK.
I give up this issue.
