### ISSUE TITLE
Crashes every time Start Menu is opened.

### ISSUE THREAD

**Issue by notNSANE** [valinet/ExplorerPatcher#3351]
![image](https://github.com/valinet/ExplorerPatcher/assets/7162375/dd4c2e9f-514e-47be-b45e-56e821903eb2)

latest explorer patcher version, 22621.3527.65.1

**Comment by h4rry431** [comment]
this happened to me aswell
tried reinstalling, however kept crashing

**Comment by pyrates999** [comment]
Try updating to the pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

Also check if symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

Open up EP properties application and go to advanced, and check that **Enable symbols download** is ticked.

Symbols need to be downloaded for every new update of windows because they change with each new update for windows.

You can check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by LYCAON68** [comment]
Hello everybody,

I had a same trouble since _Explorer Patcher version 22621.3527.65.1_ ... under Microsoft Windows 11 Pro Version 22H2 (build 22621.3672) - (Build 22621.ni_release.220506-1250) : 

So not be able to right click on Start Menu to get in Parameters and so ... but left click open the Start Menu without problem's !

When trying to opening Start Menu it restart EP up to 4 time, then it crash with a error message box wich tell me for some instructions and to uninstall EP !

Finally i downloaded and installed the **_**latest Explorer Patcher pre-release version 22621.3527.65.5**_**, wich i think solved the problem for the moment and with new options added in Setting and uninstall Tab !

Thank's to the Team for the job ...
