### ISSUE TITLE
Adapt to 22631.3672

### ISSUE THREAD

**Issue by zerosherd** [valinet/ExplorerPatcher#3354]
![image](https://github.com/valinet/ExplorerPatcher/assets/45382820/ad15d681-245a-4bf2-9e8e-b4d612b0ad39)

changelog said this version is share same file but still not be adapted. hopefully get adapt soon.

**Comment by pyrates999** [comment]
You installed a preview update: https://support.microsoft.com/en-us/topic/may-29-2024-kb5037853-os-builds-22621-3672-and-22631-3672-preview-dcf14fd8-84d6-4234-9d5b-784c319cd7cf

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by zerosherd** [comment]
> You installed a preview update: https://support.microsoft.com/en-us/topic/may-29-2024-kb5037853-os-builds-22621-3672-and-22631-3672-preview-dcf14fd8-84d6-4234-9d5b-784c319cd7cf
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.
> 
> You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

appreciate your reply, already turned off.
