### ISSUE TITLE
When launched it crashes forcing a restart or restore point action

### ISSUE THREAD

**Issue by SwordSlayer313** [valinet/ExplorerPatcher#3418]
Whenever I install this program and launch it, it will load the taskbar at first but then immediately start to bug out, which forces me to restart my computer. If restarting the computer isn't available, I have to access my recovery settings and restore a previous point recorded on my laptop.

Therefore, this is unusable for me.

**Comment by pyrates999** [comment]
Please install the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3527.65.5_6f6666b

Please post windows version and build.  You can find this by running winver.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment]
1. Are you using EP 65.5? I have just made that the latest release due to all the crashes like yours affecting 65.2 and earlier.
2. You do not need to go that far to restore your computer to a working state. You can use task manager's Run feature to uninstall EP. The command is `"C:\Program Files\ExplorerPatcher\ep_setup.exe" /uninstall`

**Comment by Amrsatrio** [comment]
Closing due to no response.
