### ISSUE TITLE
Version 22621.3810.66.1 detected by Windows Defender

### ISSUE THREAD

**Issue by YSYavuzSelim** [valinet/ExplorerPatcher#3489]
When I download ExplorerPatcher, it instantly gets detected and removed by Windows Defender. TROJAN:Win64/Malgent!MSR 
![image](https://github.com/user-attachments/assets/c8a04bc1-cd26-4387-ba82-eb377ac292bf)

Sorry for Turkish language

**Comment by YSYavuzSelim** [comment]
I don't know if it matters but I am on build 22631.3880 with all updates installed and Windows Defender is up to date with all features enabled.

**Comment by KelvinCYDev** [comment]
Confirmed having the same warning on my side when updating to 22621.3810.66.1.

**Comment by pyrates999** [comment]
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

**Comment by YSYavuzSelim** [comment]
> Duplicate of: #3228
> 
> Please close this.

The problem is other Antilmalware like Avast and Malwarebytes flag this perticular version

**Comment by Amrsatrio** [comment]
I am optimistic this is because I added a new dll named ep_taskbar.2.dll which is the reimplemented taskbar for 226xx builds which is not open source. And how EP works is already giving it a bad reputation in the AV scene, so there's no other way than adding EP's folders into exclusions I think.

The reimplemented taskbar will be the only option for having an authentic Windows 10 taskbar experience in 24H2 going forward, so I can't remove that DLL either...

**Comment by YSYavuzSelim** [comment]
> I am optimistic this is because I added a new dll named ep_taskbar.2.dll which is the reimplemented taskbar for 226xx builds which is not open source. And how EP works is already giving it a bad reputation in the AV scene, so there's no other way than adding EP's folders into exclusions I think.
> 
> The reimplemented taskbar will be the only option for having an authentic Windows 10 taskbar experience in 24H2 going forward, so I can't remove that DLL either...

Thats very annoying...
