### ISSUE TITLE
Unable to open task manager from explorerpatcher 

### ISSUE THREAD

**Issue by Michellehdr** [valinet/ExplorerPatcher#3556]
ExplorerPatcher version: 22621.3880.66.4
Windows Version: Windows insider build

Repro Steps:
1. Deploy latest OS build.
2. Perform Windows Updates.
3. Install the application from vendor site.
4. Launch the application.
5. Right click on taskbar.
6. Click on Task manager.
7. Observe.

Actual result:
Fails to launch Task manger from Explorer patcher

**Comment by Amrsatrio** [comment]
Hi, I can fix this issue rather easily by adding some code in the handler for the custom context menu, but I would like to inquire about the reasons behind the Defender flags your security response team have been giving us lately. We have difficulties rolling out updates due to this, making users who are still on the latest release version risk facing breakages due to the ever-updating nature of Windows.

**Comment by Michellehdr** [comment]
@Amrsatrio Please submit the file detected as a false positive through this website and our research team will look into it: [https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fwdsi%2Ffilesubmission&data=05%7C02%7Cv-haiwang%40microsoft.com%7Ca454345b56fc4b36f79108dcc784047d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638604617071659588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xkrtq%2F%2FgD4Yg3ygnhSau0Q8loOkKss3HNYp%2FdMMc28U%3D&reserved=0](url)

**Comment by Amrsatrio** [comment]
I have tried, unfortunately they flagged this as HackTool:Win64/ExplorerPatcher!MTB and does not want to treat this as false positive (yes, it even got ExplorerPatcher in the threat name)

**Comment by Amrsatrio** [comment]
Fixed in 66.5.

**Comment by Michellehdr** [comment]
Issue found to be no longer repro on new version: 66.5.
