### ISSUE TITLE
Built in offsets for known Windows versions

### ISSUE THREAD

**Issue by gailium119** [valinet/ExplorerPatcher#37]
Can the settings.ini automatically added to the dll when the system is of a known version?Or can i add this myself?

**Comment by gailium119** [comment]
Also,putting it in the registry enables it to be added to install.wim simply adding to the NTUSER.DAT
Also, I think the settings should have a 'silent' button that disables all notifications.

**Comment by gailium119** [comment]
BOOL LoadSymbols(symbols_addr* symbols_PTRS)
{
    HKEY hKey;
    DWORD dwDisposition;
    DWORD dwSize = sizeof(DWORD);
    RTL_OSVERSIONINFOW rovi;
    DWORD32 ubr = VnGetOSVersionAndUBR(&rovi);
    switch (rovi.dwBuildNumber) {
    case 22000: {
        switch (ubr) {
        case 1: break;
        case 194: {
            symbols_PTRS->twinui_pcshell_PTRS[0] = 0x214f76;
            symbols_PTRS->twinui_pcshell_PTRS[1] = 0x5ca7b0;
            symbols_PTRS->twinui_pcshell_PTRS[2] = 0x5f40c8;
            symbols_PTRS->twinui_pcshell_PTRS[3] = 0x5f48d0;
            symbols_PTRS->twinui_pcshell_PTRS[4] = 0x5d8e48;
            symbols_PTRS->twinui_pcshell_PTRS[5] = 0x5d8b04;
            symbols_PTRS->twinui_pcshell_PTRS[6] = 0x5cbc00;
            symbols_PTRS->twinui_pcshell_PTRS[7] = 0x4c8a0;
            symbols_PTRS->startdocked_PTRS[0] = 0x188ebc;
            symbols_PTRS->startdocked_PTRS[1] = 0x188ebc;
            symbols_PTRS->startdocked_PTRS[2] = 0x187120;
            symbols_PTRS->startdocked_PTRS[3] = 0x3c10;
            symbols_PTRS->startdocked_PTRS[4] = 0x160aec;
            return FALSE;
            break;
        }
        default:break;
        }
        break;
    }
    default:break;
    }
    RegCreateKeyExW(
        HKEY_CURRENT_USER,
        TEXT(REGPATH) L"\\" TEXT(TWINUI_PCSHELL_SB_NAME),
        0,
        NULL,
        REG_OPTION_NON_VOLATILE,
        KEY_READ,
        NULL,
        &hKey,
        &dwDisposition
    );
    RegQueryValueExW(
        hKey,
        TEXT(TWINUI_PCSHELL_SB_0),
        0,
        NULL,
        &(symbols_PTRS->twinui_pcshell_PTRS[0]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(TWINUI_PCSHELL_SB_1),
        0,
        NULL,
        &(symbols_PTRS->twinui_pcshell_PTRS[1]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(TWINUI_PCSHELL_SB_2),
        0,
        NULL,
        &(symbols_PTRS->twinui_pcshell_PTRS[2]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(TWINUI_PCSHELL_SB_3),
        0,
        NULL,
        &(symbols_PTRS->twinui_pcshell_PTRS[3]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(TWINUI_PCSHELL_SB_4),
        0,
        NULL,
        &(symbols_PTRS->twinui_pcshell_PTRS[4]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(TWINUI_PCSHELL_SB_5),
        0,
        NULL,
        &(symbols_PTRS->twinui_pcshell_PTRS[5]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(TWINUI_PCSHELL_SB_6),
        0,
        NULL,
        &(symbols_PTRS->twinui_pcshell_PTRS[6]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(TWINUI_PCSHELL_SB_7),
        0,
        NULL,
        &(symbols_PTRS->twinui_pcshell_PTRS[7]),
        &dwSize
    );
    RegCloseKey(hKey);

    RegCreateKeyExW(
        HKEY_CURRENT_USER,
        TEXT(REGPATH) L"\\" TEXT(STARTDOCKED_SB_NAME),
        0,
        NULL,
        REG_OPTION_NON_VOLATILE,
        KEY_READ,
        NULL,
        &hKey,
        &dwDisposition
    );
    RegQueryValueExW(
        hKey,
        TEXT(STARTDOCKED_SB_0),
        0,
        NULL,
        &(symbols_PTRS->startdocked_PTRS[0]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(STARTDOCKED_SB_1),
        0,
        NULL,
        &(symbols_PTRS->startdocked_PTRS[1]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(STARTDOCKED_SB_2),
        0,
        NULL,
        &(symbols_PTRS->startdocked_PTRS[2]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(STARTDOCKED_SB_3),
        0,
        NULL,
        &(symbols_PTRS->startdocked_PTRS[3]),
        &dwSize
    );
    RegQueryValueExW(
        hKey,
        TEXT(STARTDOCKED_SB_4),
        0,
        NULL,
        &(symbols_PTRS->startdocked_PTRS[4]),
        &dwSize
    );
    RegCloseKey(hKey);

    BOOL bNeedToDownload = FALSE;
    for (UINT i = 0; i < sizeof(symbols_addr) / sizeof(DWORD); ++i)
    {
        if (!((DWORD*)symbols_PTRS)[i] &&
            (((DWORD*)symbols_PTRS) + i) != symbols_PTRS->twinui_pcshell_PTRS + TWINUI_PCSHELL_SB_CNT - 1
            )
        {
            bNeedToDownload = TRUE;
        }
    }

    TCHAR szReportedVersion[MAX_PATH + 1];
    ZeroMemory(
        szReportedVersion,
        (MAX_PATH + 1) * sizeof(TCHAR)
    );
    TCHAR szStoredVersion[MAX_PATH + 1];
    ZeroMemory(
        szStoredVersion,
        (MAX_PATH + 1) * sizeof(TCHAR)
    );
    wsprintf(
        szReportedVersion,
        L"%d.%d.%d.%d",
        rovi.dwMajorVersion,
        rovi.dwMinorVersion,
        rovi.dwBuildNumber,
        ubr
    );
    RegCreateKeyExW(
        HKEY_CURRENT_USER,
        TEXT(REGPATH),
        0,
        NULL,
        REG_OPTION_NON_VOLATILE,
        KEY_READ,
        NULL,
        &hKey,
        &dwDisposition
    );
    dwSize = MAX_PATH;
    RegQueryValueExW(
        hKey,
        TEXT("OSBuild"),
        0,
        NULL,
        szStoredVersion,
        &dwSize
    );
    RegCloseKey(hKey);
    if (!bNeedToDownload)
    {
        bNeedToDownload = wcscmp(szReportedVersion, szStoredVersion);
    }
    return bNeedToDownload;
}

**Comment by valinet** [comment]
> 
> 
> Also,putting it in the registry enables it to be added to install.wim simply adding to the NTUSER.DAT Also, I think the settings should have a 'silent' button that disables all notifications.

Latest update already reads and writes all settings to registry. I don't remember if you or someone else asked about this at some point, I did not do it then but have done it now as it is indeed easier. So yeas, if you prefill the settings in the registry and then restart Explorer and have the app loaded, it will load from registry and just work.

Regarding the messages, idk, some people want it more verbose, some don't want it at all, idk... If you prefill the registry with the settings, it will be silent, in that no notification will show and it will just work. Ideally, one would not need any symbols and would get everything done by patching only known functions in the import address table. To do this effectively, for Start menu it is kind of hard (for example, the number of "most used" apps is hardcoded to "6" in the source code, no IAT patch helps you there), while for Explorer it would mostly boil down to reimplementing the Win+X menu logic in the program itself instead of relaying on the code still existing in `twinui.pcshell.dll`. This is what StartIsBack does, for example. The program could also hook to the function in there and use that, maybe, like it does for the Mica effect on File Explorer title bars and reskinning the taskbar icons. To be honest, I prefer using already known to work implementations from other places, especially if I know they will remain there. Eventually, those may be ported over as well, but it just takes time... if someone else wants to do it, why not... personally I prefer to work on adding other stuff and get by with reusing some implementation that I know is good and works well, and the dormant Win+X code in `twinui.pcshell.dll` is just fine for the time being.
