### ISSUE TITLE
Enable Taskbar Location: Top

### ISSUE THREAD

**Issue by diego10arg** [valinet/ExplorerPatcher#373]
Hi, thank you so much for this patch.

I would love to be able to place my taskbar at the top of my screen instead of the default and only option at the bottom.

I used Winaero Tweaker to do so with the unpatched W11, but after applying this patch, it does not work anymore.

Thanks in advance!
Diego

**Comment by valinet** [comment]
Hi

Yeah, I don't know who's exactly to blame in this instance, EP or Winaero Tweaker, but I found a workaround to do it:

1. Uninstall ExplorerPatcher.
2. Set the taskbar to top in Winaero Tweaker.
3. Reinstall ExplorerPatcher. The taskbar will still show at the top.

Your EP settings will be preserved, so don't worry.

As far as I know, I can't think of what I may be doing in the patcher that prevents this setting from taking effect when applied when the patcher is loaded. But fortunately, it works if you follow the above. I only redirect the `StuckRects3` registry entries when using the Windows 10 taskbar, in order to avoid those "famous" problems with setting the Windows 10 taskbar to the left and then reverting back to the Windows 11 one which doesn't support that and now crashes Explorer on a loop.

So yeah, just do the above, it should work. I have that applied at the moment on my system, as I just tested it:

![image](https://user-images.githubusercontent.com/6503598/141862371-eba5eb6f-5720-4fe4-b2ae-bf99f4c03d42.png)

For the moment, this workaround seems to work. Of course, if I figure out why this happens in the first place, I will patch it as well, but I cannot think of anything regarding this at the moment.

Thank you.

**Comment by diego10arg** [comment]
Hi Valinet,

Unfortunatelly the issue still persists... I already have my taskbar at the top set with Winaero Tweaker and after running EP it goes back to the bottom.

I tried setting my taskbar at the bottom, running EP and then trying to put it at the top with WAT but it does not work.

I am using W11 22000.318 with dark theme ON and using "Taskbar size = Large" on WAT as well.

If there is anything (log or something) I can send you please let me know, and once again, thank you so much for your efffort.

**Comment by valinet** [comment]
Hi

Then it must be something else, not EP. I told you, it does not seem to be EP. I was able to move it to the top just fine after doing the trick mentioned above. I now investigated more: after you set that setting, restart File Explorer from WAT; if you do it from EP, it will save the current setting (which is still bottom) and overwrite what WAT did (because Explorer restarts from EP first save Explorer settings, so that recently modified things by the user are not lost, while WAT seems to simply kill Explorer). So, set in WAT and restart Explorer from there immediately.

Idk what else to say, play with it, set EP taskbar to Windows 11, uninstall EP, reboot, move it to top using WAT, restart File Explorer from WAT, confirm it is at the top, reboot, confirm it sticks at the top after a reboot, reboot, install EP, and it should still be at the top. With steps separated so well, idk what could go wrong. I am on build 22000.318 as well and it works just fine. no need for any logs, as I can't do anything about it from over here, seems to work eventually.

Thanks
