### ISSUE TITLE
WHAT HAPPENED TO THE TOGGLES

### ISSUE THREAD

**Issue by GuestTheGamer** [valinet/ExplorerPatcher#3739]
![Screenshot 2024-09-25 211154](https://github.com/user-attachments/assets/7d282d91-6206-498b-9d98-942fa64ea335)

**Comment by GuestTheGamer** [comment]
![Screenshot 2024-09-25 214739](https://github.com/user-attachments/assets/d3f093a5-86ce-4c44-b58c-49750eb773c2)

**Comment by milesprower2293** [comment]
Do you have the Windows 10 action center enabled?

**Comment by pyrates999** [comment]
Your windows build is from July 9/2024: https://support.microsoft.com/en-au/topic/july-9-2024-kb5040442-os-builds-22621-3880-and-22631-3880-0864308e-61cc-413b-8194-0294331aba52

Please install the latest windows updates.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by milesprower2293** [comment]
Updating the OS doesn't always fix issues, specially related to third party programs like EP

**Comment by pyrates999** [comment]
Yes, but for me with trouble shooting a problem, updating the OS and having the latest version of EP is the first thing I'd do.
