### ISSUE TITLE
Search usually just flicks and black screen after I started typing the query.

### ISSUE THREAD

**Issue by EriksCat** [valinet/ExplorerPatcher#3750]
I have explorerpatcher version: 22621.3880.66.6.
Windows 11 OS build: 22631.4249
4 days ago the menu search just started not working, instead it flicks white screen, takes a long time to load or black screen. If you wait and type a few times it will stop doing this. But it still keeps going on and on.
Anyway to fix this or need to wait for update? 
![image](https://github.com/user-attachments/assets/fc7c952e-8dec-465c-b2c4-fe3089317dff)

**Comment by pyrates999** [comment]
You installed a preview update: https://support.microsoft.com/en-us/topic/september-26-2024-kb5043145-os-builds-22621-4249-and-22631-4249-preview-71ee16f6-9a39-4569-937c-fe0fd8577285

So if this is a bug, please wait for a developer to respond.

Did you try rebooting?

**Comment by EriksCat** [comment]
> You installed a preview update

I reinstalled explorerpatcher and deleted files from explorerpatcher folder in registry. I unchecked to use preview update before reinstalling, but still this version

**Comment by milesprower2293** [comment]
That seems more like a Windows Issue rather than a explorer patcher issue
Follow these instructions to disable Bing search:
1. Open the run dialog by pressing the Windows key and R
2. type regedit and press enter
3. put this on the registry editor address bar:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search
4. create a new DWORD Value named BingSearchEnabled 
5. open that dword value and press enter and reboot your PC

**Comment by EriksCat** [comment]
Well, it worked.
Thanks, I thought it was an explorerpatcher problem because it was working fine before.
Thanks!

**Comment by pyrates999** [comment]
In the settings app, did you untick "Get the latest updates as soon as available"?

If not, preview updates are still automatically installed.

If you did, preview updates are then shown as download and install and are never automatically installed.  So if you were prompted to install that preview update, and then installed it, next time don't do that.
