### ISSUE TITLE
 Weather Widget not working 

### ISSUE THREAD

**Issue by Ha7yad** [valinet/ExplorerPatcher#3789]
So I have tried a bunch of things for this to work like restarting ExplorerPatcher, turning the widget on and off. but none of them work. It is just a widget of people. Any idea's on how to fix this?
![image](https://github.com/user-attachments/assets/97e23c34-b91e-4d51-8c81-98ce8faf25e4)

**Comment by pyrates999** [comment]
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2010

please close this.

and weather is not yet supported on the windows 10 (ExplorerPatcher) taskbar: https://github.com/valinet/ExplorerPatcher/issues/3546

**Comment by Ha7yad** [comment]
It actually was when I didn't have to uninstall it

**Comment by Ha7yad** [comment]
Also I have Windows 11 and I use this for the Windows 10 taskbar @pyrates999

**Comment by Ha7yad** [comment]
It used to work before but when  I re installed it, it just was the people icon

**Comment by Jazzzed** [comment]
Have you tried clicking the “Clear weather widget local data” link in the settings area under Weather?

**Comment by Ha7yad** [comment]
@Jazzzed Yes I have. It just says error

**Comment by Ha7yad** [comment]
![image](https://github.com/user-attachments/assets/57c6deb0-dd6d-442f-9b89-19ea562bf0d1)

**Comment by pyrates999** [comment]
Please see my original comment.  Weather is not supported on the EP implemented windows 10 taskbar.

**Comment by Ha7yad** [comment]
@pyrates999 I'm confused. There are 2 types of different Windows 10 taskbars. Which one of them are not supported for weather? 
![image](https://github.com/user-attachments/assets/0bbbb742-9663-4758-9be5-81b734f5de4c)

**Comment by pyrates999** [comment]
Weather is not yet supported on the windows 10 (ExplorerPatcher) taskbar: https://github.com/valinet/ExplorerPatcher/issues/3546

please see this: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

The stock windows 10 taskbar doesn't work on windows 11 24h2 because it has been removed in that version of windows.

So you can't enable weather for the time being.

**Comment by Jazzzed** [comment]
The weather widget works fine for me with the Windows 10 taskbar, and has always worked fine for me.  Windows version 22631.4317.

![working](https://github.com/user-attachments/assets/0039fe93-acae-46e3-ab76-8887878ca25b)

**Comment by Ha7yad** [comment]
@pyrates999 Ok so will the **Windows 10 (ExplorerPatcher)** ever get weather supported?

**Comment by pyrates999** [comment]
The developers here can answer that.

**Comment by Ha7yad** [comment]
Ok I’ll close this
