### ISSUE TITLE
Two rows of icons in taskbar possible?

### ISSUE THREAD

**Issue by jlitz** [valinet/ExplorerPatcher#38]
Just installed Win 11 and ExplorerPatch thx much prefer Win 7 start. The ability to drag taskbar down seems gone as well as two rows of icons. Is there any way of changing those actions back ??

**Comment by valinet** [comment]
I don't understand. Right click taskbar, uncheck "Lock all taskbars", grab edge of taskbar, drag up...? Why you need to ask this if you come from Windows 7, it worked there like that and so since Windows 98 or something like that...

**Comment by jlitz** [comment]
my error

**Comment by valinet** [comment]
I repeat, AGAIN, this is clearly labeled "Issues", not general questions. Despite being a trivial question to answer if one used Windows in the past 20 years, I have made a single thread specifically for general questions in order not to clutter the issues panel (I won't bother to share the link since it anyway was of no interest, it seems). So I guess for some people it is hard to read, and even then, apply basic common sense...
