### ISSUE TITLE
Custom Toolbar Sort Order

### ISSUE THREAD

**Issue by jj9356** [valinet/ExplorerPatcher#3805]
When using Explorer Patcher to create and pin a custom toolbar to the task bar (like we used to in Windows 10), you can re-organize the order of the items in the toolbar. In Windows 10, the order of items was always remembered when re-starting windows, but in Windows 11 running explorer patcher, the order of items seems to re-sort to alphabetically when windows is re-started or File Explorer is restarted. I use my custom toolbar as 1 click shortcuts to many applications and I like to maintain a sort order with most used items on top and the rest sorted by application type. Can the sort order of toolbar items be remembered after windows 11 restart with explorer patcher? Windows 11 Enterprise, 23H2, 22631.4169  Running Explorer Patcher version 22621.3880.66.6 I already changed to Windows 10 taskbar (ExplorerPatcher).
![image](https://github.com/user-attachments/assets/dd674b7f-6a19-4c39-8de2-1b465cc7bdde)

**Comment by VulcanTourist** [comment]
You might want to consider [True Launch Bar](https://www.truelaunchbar.com/) as an alternative.  It's independent of Windows and can auto-sort its menus and sub-menus or not, at your whim, ***and*** of course remember them.  It's capable of quite a few other tricks as well.  It's freeware now.

**Comment by dunsparce9** [comment]
I found that the sort order is remembered on "horizontal" toolbars where all icons are visible (with or without labels), but not on toolbars that are a dropdown. Kinda annoying, also this only started happening after switching to EP's taskbar implementation, it did not happen before 24H2.

**Comment by Amrsatrio** [comment]
So you're on 22H2/23H2 and sort order is remembered in Windows 10 taskbar but not remembered in Windows 10 (ExplorerPatcher) taskbar? If so, give me a moment to fix it.

**Comment by Amrsatrio** [comment]
This is also an issue on a clean Windows 10 22H2 installation, so sorry, not on our plans to fix this defect on Windows side.

**Comment by VulcanTourist** [comment]
This is all the more reason for those affected to consider my earlier suggestion to use [True Launch Bar](https://www.truelaunchbar.com/) and abandon the Windows toolbar folder functionality.  It's freeware now.  It will restore that broken sort capability and add substantial additional capabilities that don't exist otherwise.  TLB still relies on the toolbar functionality to appear in the toolbar, so if Microsoft keeps yanking features it may eventually break, too, but for now it's quite functional.  I am completely reliant upon it.  Damned if I know what I'll use to replace it when it also fails.

![screenshot_00012](https://github.com/user-attachments/assets/df66e878-f4de-44d6-a34c-62ab638f8fff)
