### ISSUE TITLE
Explorer Patcher Check for updates.

### ISSUE THREAD

**Issue by Firebrand25** [valinet/ExplorerPatcher#3826]
The check for updates does not work on 24h2. I did work on 23h2.
I uninstalled Explorer Patcher before installing 24h2.

**Comment by Amrsatrio** [comment]
What's your EP version? If you are on 66.2, 66.3, 66.4, or 66.5, those versions are problematic. Please 66.6 manually.

**Comment by Firebrand25** [comment]
66.6 and that is exactly what I did. Manually. I did the same thing on
earlier versions.
It could be a bug in 24h2?
Thanks for the reply.
Greg

**Comment by Amrsatrio** [comment]
66.6 is currently the latest release version. 66.7 is the latest prerelease version. If you are on 66.6, and have receive prereleases off, you will get the message "No updates are available."

Can you explain in what way it does not work? No notifications that appear? In this case, please check your notification settings and check if notifications for Explorer are disabled. Windows suggests you to turn off notifications for Explorer after a while, and you probably clicked it. This problem is not isolated to 24H2; it works on my 24H2 ARM64 26100.1150 machine.

**Comment by Firebrand25** [comment]
[image: image.png]
When I click on check for updates I don't get a response.
When you say check notifications are you saying Windows notifications?
Windows File Explorer notifications?

**Comment by Amrsatrio** [comment]
Yes, Windows notifications.

**Comment by Firebrand25** [comment]
Turning on notifications did not make any difference.
The update function worked with 23h2.

**Comment by Firebrand25** [comment]
No wait. I was wrong. The notification did appear. Thank you.
