### ISSUE TITLE
Request for Windows 11 Start icon as opposed to windows 10 icon

### ISSUE THREAD

**Issue by randomguyreviewing** [valinet/ExplorerPatcher#383]
If this could be updated with the new Windows 11 icon instead of 10 that would make everything pretty much 1 to 1

**Comment by valinet** [comment]
PLEASE PLEASE PLEASE It's the nth time I am saying this, issues is for issues, not for feature requests, opinions etc. It clearly states that here as well: https://github.com/valinet/ExplorerPatcher/issues/56, also right in the title, which is pinned as a top issue, so that people notice it and RESPECT it. But no, why bother, eh...?

Also, what is stated there is not to open duplicate topics. This has been requested multiple times in multiple threads already, every now and then someone requests this; there are some workarounds listed in those threads, like using OpenShell just for a Start button etc. When I will have something regarding this, it will be released, as usual. For the moment, yeah, not supported yet.

Please do not get mad at me, but I just want to keep things organized. Thanks
