### ISSUE TITLE
After installing update Explorer Patcher stops working

### ISSUE THREAD

**Issue by crimle** [valinet/ExplorerPatcher#3890]
This afternoon I was prompted to update Explorer Patcher. So I installed and restarted Explorer Patcher. From this moment, my taskbar appears in Windows 11 style and all my settings are gone. Restarting the computer was unsuccessful. Desperately hoping for a solution, I am not willing to cope with Windows 11 toolbar, which is driving be crazy.
Explorer Patcher Version 22621.4317.67.1.

**Comment by crimle** [comment]
By the way: I accidentally found an old Explorer Patcher setup file. For a couple of minutes I am on an older version Explorer Patcher Version 22621.2428.59.1 and my taskbar is working again :-)

**Comment by Amrsatrio** [comment]
You did not specify the Windows version you're on. If you're on 24H2, the Windows 11 taskbar is indeed the default. You have to change it to Windows 10 (ExplorerPatcher) in the Properties window (search for Properties (ExplorerPatcher)). If you're on 67.1+, Always combine is the default, and you have to use the Properties window to change it to Never combine.

Let me know if you have further problems. Closing this issue because EP works on latest 22H2, 23H2, and 24H2 at least on my real machines and virtual machines.
