### ISSUE TITLE
"Open Start to All apps by default" is unreliable

### ISSUE THREAD

**Issue by kaivol** [valinet/ExplorerPatcher#40]
When the start menu is closed and then reopened in quick succession (for example by double clicking the start menu button or by "double clicking" the windows key) the default start menu page (with pinned apps and recommendations) is shown even though the "Open Start to All apps by default" option is activated.

**Comment by valinet** [comment]
Unreliable is an offensive word in this context, imo. Something unreliable is something that randomly changes behavior in normal conditions. With this setting, the Start menu ALWAYS opens to "All apps" unless you stress it by spamming the "Windows" key and only then it sometimes fails. I wouldn't call that unreliable, but whatever, each with their own opinion.

With that being said, the way this setting works is I hook into the `VisibilityChanged` event of the Start menu and issue a `ShowAllApps` command, let's say, regardless of whether the Start menu is opening or closing. It seems to work fine, so I haven't bothered to check the visibility flag (I did initially, but its symbol name changes, I could mock some code from the assembly and use that to check the flag, though).

The most I can do is add back the check for the visibility flag and then issue the command only when the menu opens. Maybe that helps. But I don't know whether it will still be reliable (the visibility flag structure may change and break the app on future updates). All for not much in return. From my testing, it seems to behave mostly the same. Which is fine 100% of the cases when it is operated normally. I'd even say triple pressing the `Win` key to go to the main view may be considered a feature, it spares you having to hunt down for `Back`.

Anyway, I think it is much better like this than to not have it at all. I prefer to look at implementing other things rather than spending time polishing something that works very well anyway.

**Comment by kaivol** [comment]
Thank you for the detailed answer!

I didn't mean to come across as rude, I just wanted to be sure that it is intended beavior and not a problem with my system.
