### ISSUE TITLE
KB5046740 Windows Cumul Update

### ISSUE THREAD

**Issue by MaddyEffingham** [valinet/ExplorerPatcher#4009]
Be advised!
Anyone having issues installing the update from windows, KB5046740, it appears the EP is blocking it.  After uninstalling EP, I ran the updater again and windows successfully downloaded and updated the updates.  Unfortunately, I was forced to reinstall EP and reconfigure it all again, but at least all is up to date.  MS REALLY needs to get with the program and STOP being a pain!  EP is GOOD and it PROVES MS's Windows 11 is doggy doo doo
<Mic drop>

**Comment by pyrates999** [comment]
that's a preview update: https://support.microsoft.com/en-us/topic/november-21-2024-kb5046740-os-build-26100-2454-preview-2040f716-b719-482a-8aff-f7f02c79b147

IMO you shouldn't be installing preview updates as they are not fully tested by MS and don't include any security fixes.

**Comment by MaddyEffingham** [comment]
OH I had no idea it was a preview update.  I just have my windows set to download updates as it finds them.  Geeze.  I am certainly NOT interested in being MS's Guinea Pig!
Thanks for the heads up!.

**Comment by pyrates999** [comment]
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.
