### ISSUE TITLE
Customize notification area icons not working in last version

### ISSUE THREAD

**Issue by mumpat** [valinet/ExplorerPatcher#402]
Hello,
First of all a big thanks for this great tool 👍 

In the last version (22000.318.37.5) it's not possible anymore to customize the notification icons. When you choose to display one, sometimes it does nothing, sometimes it restart the explorer. Only network and sound are displayed by default.

Only possible option is to display all icons. 

Thanks and best regards

**Comment by valinet** [comment]
First of all, maybe you're experiencing this, which is a known issue: https://github.com/valinet/ExplorerPatcher/issues/236, so be quick in that window and better is to make the changes and restart Explorer yourself from Properties, for example.

Other than that, it works just fine, if it saves the settings before crashing when the time changes, as is described in the bug above, it works just fine, so I don't think this is an issue in itself, rather than a side effect of the bug referenced in the issue above. it's possible to select certain icons for sure, I just tested it.
