### ISSUE TITLE
Latest Explorer patcher not working 

### ISSUE THREAD

**Issue by ratcac** [valinet/ExplorerPatcher#4048]
Just installed 24H2 and d'oaded the latest EP [22621.4317.67.1]   It goes black then back to the way it was, still cannot move my taskbar. Windows is blocking it somehow.

**Comment by Amrsatrio** [comment]
No it's not blocking it. EP no longer defaults to 10 taskbar since it has been removed completely in 24H2, and it doesn't default to the reimplemented taskbar either because it's dangerous to do so. Suppose a future version introduces incompatibility with it, that would be a meltdown, and Microsoft may put blocks on us again.

To assist you into the right direction, please right click your taskbar, select Properties, you will see "Taskbar style: Windows 10". Click it, and select Windows 10 (ExplorerPatcher). If you don't see it, please try running ep_setup.exe again as administrator and then the next time you open the Properties dialog it should appear.

After changing to Windows 10 (ExplorerPatcher) taskbar, don't forget to restart explorer to apply the changes.
