### ISSUE TITLE
EP not allowing taskbar to move in Windows 11 

### ISSUE THREAD

**Issue by sunnyorlando** [valinet/ExplorerPatcher#4050]
### Before reporting your issue

- [ ] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues
- [ ] I have confirmed that this issue does not happen when ExplorerPatcher is not installed

### Repro ExplorerPatcher versions

EP - 22624.4317.67.1

### Repro Windows Versions

Windows 11 24H2 12/1/2024 on Intel(R) Core(TM) i5-14600K 3.50 GHz
OS - 26100.2605
Windows Feature Experience Pack 1000.26100.36.0

### 3rd party tweak software installed

NONE

### Describe the bug

The changes requested in EP get applied correctly, except that I cannot move the taskbar anywhere.
The issue is reproducible

### Expected outcome

Allow the taskbar to be vertically located (L or R)

### Actual outcome

Nothing, not allowed to move taskbar

### Crash Dumps

N/A

**Comment by sunnyorlando** [comment]
I just installed EP and this is  anew W11 install. There are not other  shell modifying apps.

**Comment by pyrates999** [comment]
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

please see this for more info: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

**Comment by sunnyorlando** [comment]
That is where its at >>  "Windows 10 (explorer Patch)


[image: image.png]

**Comment by Amrsatrio** [comment]
Use Windows 10 (ExplorerPatcher) taskbar. Right click the empty space. Uncheck Lock the taskbar. And then drag it wherever you wish.

**Comment by Amrsatrio** [comment]
I cannot answer your question -- because it may be a misperception.

We've been able to unlock the taskbar which allows it to be moved and sized. In the case of the Windows 10 taskbar and reimplemented taskbar on Windows 11, one would untick "lock the taskbar" in the taskbar context menu and drag the empty space in the taskbar to move it, or drag the edge of the taskbar to resize it (to 2+ rows or something). And then when it is ticked again, the taskbar won't be movable and sizable. If you're talking about retention of settings after an Explorer restart, Microsoft designed the system such that the settings are saved after a certain delay where no further setting changes are made to prevent spams to the registry and the setting roaming system. So for example, if you moved the taskbar and then 1-3 seconds after Explorer crashes or you restart Explorer manually, the taskbar size/position will revert. But if you waited 30 seconds after making a change, the states will be persisted into the registry. At least that's what I've observed and studied the code responsible for them.

If you are referring to the taskbar position dropdowns in the EP properties GUI, yes, I understand that those are buggy and we have no urgent priority plans to fix it yet since the good ol unlock and drag method works perfectly fine.
