### ISSUE TITLE
Right-Click Taskbar Context Menu Options Missing Text Labels

### ISSUE THREAD

**Issue by itsmeroby** [valinet/ExplorerPatcher#4061]
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [X] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

Explorer Patcher 22621.4317.67.1

### Repro Windows Versions

Windows 11 24H2, OS Build 26100.2605

### 3rd party tweak software installed

Windhwak:

![image](https://github.com/user-attachments/assets/e95188b5-26cf-4583-ac7b-b11d367d1d19)

### Describe the bug

1. Update to Windows 11 24H2.
2. Install EP 22621.4317.67.1.
3. Enable Windows 10 (ExplorerPatcher) taskbar and restart Explorer.
4. Right Click on the taskbar.
5. Notice how only the 'Settings' and 'Desktop' options are displayed correctly, while the other options are missing their text labels.

### Expected outcome

All options in the context menu should include text labels, but currently, only icons are displayed.

### Actual outcome

No text labels in some context menu options, except for 'Settings' and 'Desktop'.

### Media

![Screenshot 2024-12-22 114619](https://github.com/user-attachments/assets/f7e55eb2-1665-468b-9ab8-7529cd44ba31)
![Screenshot 2024-12-22 114741](https://github.com/user-attachments/assets/047212f4-03e8-4413-988e-521fe3ee8161)

**Comment by pyrates999** [comment]
Open up EP Properties application, and go to File Explorer.  Check if you have enabled **Disable the Windows 11 context menu**.  Then click on **Restart File Explorer** in bottom left corner.  As mentioned here: https://github.com/valinet/ExplorerPatcher/wiki/All-features#disable-the-windows-11-context-menu

**Comment by itsmeroby** [comment]
> Open up EP Properties application, and go to File Explorer.  Check if you have enabled **Disable the Windows 11 context menu**.  Then click on **Restart File Explorer** in bottom left corner.  As mentioned here: https://github.com/valinet/ExplorerPatcher/wiki/All-features#disable-the-windows-11-context-menu
> 
> 

I've already disabled the Windows 11 context menu. What should I do now?

**Comment by pyrates999** [comment]
Before you do what I suggest below, set windows to use light mode instead dark mode and check if it is still happening.  If it is, continue.

---

To determine this is not caused by EP, try the following:

1. Uninstall Rectify11.
2. Disable all mods in Windhawk.  Doing this might cause windows to freeze though, so be prepared to power cycle your computer in case this happens.

If this no longer happens:

1. Install Rectify11 again.
2. Check if it is happening now, and if so, Rectify11 is causing it.
3. If not, enable each mod one by one in Windhawk and check if it is still happening after each one is enabled.
4. If it happens after a certain mod in Windhawk is enabled, that mod is the cause of it.

**Comment by milesprower2293** [comment]
This is not an ExplorerPatcher related issue
