### ISSUE TITLE
Window switcher not shown when a process is not responding

### ISSUE THREAD

**Issue by jdp1024** [valinet/ExplorerPatcher#449]
When a process is not responding (busy or dead-locked), EP's window switcher (Windows 10 mode) is not shown by Alt+Tab until a long timeout is due.

Currently to avoid this I have to use Windows NT mode. Maybe it's better to use a blank preview for the processes whose window contents are not available for a short period of time.

**Comment by valinet** [comment]
Thanks for the report. Sorry for the delay it took to fix this, I was playing some matches in some other threads...

I fixed this. I indeed forgot to add `SMTO_ABORTIFHUNG` to a `SendMessageTimeoutW` call where I query an icon from a window, and that was hanging up the window switcher thread when the window in question was hung, because it was waiting for a response which was never coming. This seem to fix it. Please test the latest pre-release (38.8) and tell me if it does. If everything's okay, I will push it as a release soon.

Adding to this, I never looked on this in depth, but since I was now spending time on it, I noticed that ghost windows were also appearing in the window list, alongside the hung window (ghost windows are displayed instead of the window from the not responding program in order to allow the user to minimize and move the window of a hung program, and they also display a bitmap of the program's last state of the UI). This shouldn't be the case: ghost window should not be shown, as they needlessly duplicate the window of the hung program, so I removed them. Also, I made it so that hung windows display the title of the ghost window instead of their own title, so you can quickly tell which window is not responding from the titles displayed in the window switcher as well (they contain " (Not Responding)" at the end).

Thank you again for the report.

**Comment by jdp1024** [comment]
Thanks for the detailed information on the problem.

My Windows 11 has been updated to 10.0.22000.348 by accident which EP doesn't support yet. A message popped up saying that EP will download the symbols but then nothing happened.

**Comment by valinet** [comment]
Download the latest pre-release, it addresses that somewhat as well.

**Comment by khalilme** [comment]
its working, thanks
