### ISSUE TITLE
Possible issue with double-click and auto-hide taskbar

### ISSUE THREAD

**Issue by PGomersall** [valinet/ExplorerPatcher#466]
Valinet,
I have tested this on a couple of systems and I can trigger the situation on both.
I enable the setting to allow double click to toggle taskbar auto-hide. If I then double-click to turn auto-hide on, my desktop icons are then jumbled from their predefined settings. I have a complex arrangement of icons so it is frustrating to re set them up.
It seems that the double click triggers a theme change possibly since if I uncheck "Allow themes to change desktop icons" it stops them been jumbled.
Maybe you know or can find what causes this and correct it or if not explain what is happening? Previously I have never had to uncheck "Allow themes to change desktop icons".
p.s. It seems that once auto-hide is enabled that the desktop icons jumble at what seems random times - these jumblings are not related to double clicking the taskbar just random. On my 2 systems that this happens on, I do have the taskbar addressbar loaded.
Regards,
Pete

**Comment by Anixx** [comment]
You can try the same function in 7+Taskbar Tweaker.

**Comment by PGomersall** [comment]
@Anixx, I do not use 7+Taskbar Tweaker - prefer to keep things minimal as possible. Hopefully Valinet can determine what is going on.

**Comment by valinet** [comment]
What’s to explain? It’s an option that someone requested me to include and honestly now I wish I did not, it only creates stress and a new wave of questions and possibly bug reports. Yeah, like the enemy of “good” is “better”. If I knew 7+TT had that, I wouldn’t have included it…

That is how it works… it’s optional… I didn’t code the Windows shell, it’s just a simple SHAppBarMessage call. I don’t know exactly if that is the 100% right way to toggle that, it’s Windows, there are always a dozen ways to do everything, it was a snippet someone shared around here, I tested it a bit, seemed to work, included it. Big mistake, apparently.

Yeah, and people wonder why I am reluctant to changes. As I said, every small little change seems to dynamite someone’s setup or trigger him/her in some way, and most people mostly care only about their particular interests, it is always me that has to come and clean up the mess, support everyone’s niche workflow and requests. Maybe it’s time to remove features from this program.

As @Anixx said, check how it behaves in 7+TT. If it’s different there, I will remove it, I can’t be bothered to find out why it happens, honestly, I am tired of this. Like, c’mon, think about my time as well, it’s not that hard to invest 5 minutes into an investigation rather than the easy route of “hope valinet can determine what is going on”. I am also starting to like to keep things minimal, like minimal distractions during my free time.

And why open an issue if it’s a possible issue…? Things I have repeated countless times. Again, no real effect…

**Comment by PGomersall** [comment]
Valinet, I shouldn't have suggested you try and find a fix, I can live without the feature. However, if it is not an issue what should I have called it - maybe side effect? Move it to Discussions if you like, I don't care. I will refrain for contributing comment to your very useful tool; I just thought that you like to know about the "side effect"?
Pete

**Comment by valinet** [comment]
> I enable the setting to allow double click to toggle taskbar auto-hide. If I then double-click to turn auto-hide on, my desktop icons are then jumbled from their predefined settings. 

Yeah, I have checked it out, that's the way it works, apparently. It works like that (shifts the icons around) when using "Automatically hide the taskbar" in "Taskbar settings" as well, the official Windows setting. It works the same in 7+ Taskbar Tweaker as well. I mean, it's pretty normal and obvious, like, why would it keep the bottom space reserved on the desktop is not it's only optionally covered by something, i.e. the taskbar when you hold the mouse over it only...? It's just a standard Windows API call, the source code also shows that. 7+TT calls it differently for some reason but it does the same thing and effect, basically.

> p.s. It seems that once auto-hide is enabled that the desktop icons jumble at what seems random times - these jumblings are not related to double clicking the taskbar just random. On my 2 systems that this happens on, I do have the taskbar addressbar loaded.
Idk... random jumps? What do you mean? Where do they jump...? They arrange a certain way...? When does it happen, there has to be some trigger... does it happen if setting auto-hide in Windows' taskbar settings or using 7+TT's option to auto hide on taskbar double click?

> However, if it is not an issue what should I have called it - maybe side effect?

It's not necessarily that, but you could have easily found this out yourself the first part if you spent 5 more minutes to investigate it more than checking it only within EP and rushing to call it a problem, and that especially after @Anixx suggested to test in 7+TT. My time is as valuable as everyone else's. That's all I said. Regarding the second part, as well, does this happen when you enable auto hide in Windows as well, or with 7+TT? Since you use that feature anyway, why not check that out like this and do a more complete report, eventually finding a pattern as well, rather than having me do it because why not...

> I will refrain for contributing comment to your very useful tool

As I said with other occasions, it's easy to play the victim role here and get offended just because I had this opinion on the matter. I never said I don't appreciate comments or reports, I just want them to be complete so we have something to work on. Try to put yourself in my shoes as well, what magic investigation I could do to figure it out faster than you, who you know actually more about it, provide me with all the relevant info you could gather...?

**Comment by chip33** [comment]
For what its worth I ran the identical code in ahk that valinet coded into EP and tried it for maybe one or 2 years with win 10 , 1080, 4K, dual (and triple) monitors and then Win 11 with EP  etc.
I am as obsessive about my icons and other things as many of us and if I had ever detected a glitch in the behaviour of the simple script I posted I would never have suggested it.
I personally really like it as a feature. I hope it stays.
I think so far at least it actually works perfectly, just as it should and just as changing autohide taskbar in the windows settings does, But far more conveniently.
I wouldn't have suggested it if I hadn't thought it was a good functional, well tested, value adding feature.

**Comment by chip33** [comment]
Also many people may not even know about 7+ Taskbar Tweaker ( I only did after finding this EP forum) and this functionality there is pretty hidden away.
Also, EP is already quite possibly far more famous than Taskbar Tweaker due to being just what is needed at the time MS drops the ball badly on Win 11 Taskbar.
I hope we can pull together to help keep this basically essential project going.
