### ISSUE TITLE
ExplorerPatcher settings interface is not compatible with Windows Classic theme

### ISSUE THREAD

**Issue by Anix-x** [valinet/ExplorerPatcher#47]
The settings dialog is empty:

![Безымянный](https://user-images.githubusercontent.com/92230793/136672564-64e86597-8a27-4fd4-bb22-4749105ae45a.jpg)

**Comment by valinet** [comment]
Thanks for the report. Can you please try this updated DLL?
[dxgi.zip](https://github.com/valinet/ExplorerPatcher/files/7316320/dxgi.zip)

**Comment by Anix-x** [comment]
No. I mean 
* https://winclassic.boards.net/thread/510/classicthemetray-quickly-toggle-classic-theme
* https://winclassic.boards.net/thread/456/simple-classic-theme

The DWM is still running.

**Comment by Anix-x** [comment]
I am trying to replace the DLL. I have not figured yet :-) The elevated cmd says access is denied

**Comment by valinet** [comment]
Use this:

```
del C:\Windows\dxgia.dll
ren C:\Windows\dxgi.dll dxgia.dll
xcopy "<PATH TO NEW DXGI>" C:\Windows
taskkill /f /im explorer.exe
explorer.exe
```

Ofc it says access denied, the DLL is in use by File Explorer...

**Comment by Anix-x** [comment]
No, the new dll still does not work.

**Comment by Anixx** [comment]
You asked me in a e-mail, how one programmatically detects if classic theme is enabled. I really do not know how to do this,
especially taking into account that there are different methods (such as deleting the theme handle, blocking access to the theme handle and disabling DWM plus deleting the theme files).

But I have encountered programs that could correctly detect this. How do they do it, I do not know.

But the majority of programs work correctly regardless of theme, so possibly, detection is not what should be implemented.

Still, if you use the same technology as used by the Control Panel pages, this way may work:
https://winclassic.boards.net/post/2889

**Comment by valinet** [comment]
Yeah, I briefly asked here, then I figured it out, it's an API call: `IsThemeActive()`. It has to be used. Most programs do not draw the whole interface over a Mica backdrop with the glass area extended to the whole window. To draw text there properly, one has to use `DrawThemeTextExW`, as that knows about alpha values etc. But since you disable the themes altogether, apps that use that fail to draw text, that's why some programs cannot work properly. So, when I detect that themes are not available, I have to switch back to using `SetTextColor` and `DrawTextW`, which is fine since Mica does not work anyway with the classic theme (I think?). Anyway, can you try this new DLL?
[dxgi.zip](https://github.com/valinet/ExplorerPatcher/files/7316594/dxgi.zip)

**Comment by valinet** [comment]
Makes sense, as it simply has no icon...

**Comment by valinet** [comment]
Yeah, I removed the icon entirely, as I don't have an icon anyway. The taskbar one is the default one provided by File Explorer.
[dxgi.zip](https://github.com/valinet/ExplorerPatcher/files/7316612/dxgi.zip)

**Comment by Anix-x** [comment]
Tested, looks OK
