### ISSUE TITLE
KeyBoard Setting

### ISSUE THREAD

**Issue by COKID** [valinet/ExplorerPatcher#498]
My win11 language is Chinese. So I only use Chinese inputting method. But when I install ExplorerPatcher, an English inputting method added to my language bar. And I can't remove it.

**Comment by valinet** [comment]
Idk, to be honest. Personally, I use US English keyboard so I can’t experience this. The program does not do anything on its own, maybe Explorer in this mode gets triggered somehow and adds US English automatically. I don’t really know. Check this thread where people discuss similar things, maybe it helps: https://www.elevenforum.com/t/new-version-of-explorerpatcher.1991/page-11

Thanks

**Comment by BraINstinct0** [comment]
Seems like this behavior is consistent across all other systems using non-US English keyboard as default.

**Comment by valinet** [comment]
What is the **behavior** and what fixes it? Somehow EP magically adds US English as a keyboard? What happens if you remove it, does it appear back at reboot or when…? I don’t understand why no one facing this issue bothers to do a rather more verbose report, otherwise how can this ever be fixed if there is anything to fix indeed? Does it happen with StartAllBack as well…?

**Comment by BraINstinct0** [comment]
Ah, sorry for the incomplete confirmation. Will update soon with more info. Until then feel free to close.

**Comment by BraINstinct0** [comment]
Huh. Once removed, uninstall, reinstall, reboot, restart EP, reboot, uninstall didn't give this.
Strange.
So I tested further: Rather, the below seems to be the true issue.

By default I tried having both US and KR(Korean) language packs(and input methods), installed EP(latest stable),
restarted explorer.exe(might not have to, but at least it does restart explorer at least once.).

Despite setting default input method to Korean IME, **Not always**, but many times(usually when a program is closed,or restarted) the input method changes to a US one.
Once changed to Korean IME at a program's input field(textbox or whatever), the setting works well for that program. Doesn't affect other programs' behavior(e.g. using default input method since program start, or ignoring the default and using EN-US.) (still, no consistent behavior; seems to happen a lot with Cisco Webex but that's already buggy by its own).

Honestly I don't fully understand what's going on;
but anyways......
Summary: the core behavior is that
1) when the current latest stable ExplorerPatcher is 
2) used on a system with two or more input methods(at leas US and Korean, seemingly applies to Chinese and Japanese) with the Non-US one set as default
3) sometimes the default is ignored and EN-US input method is used for a (not necessarily, but) newly started program.
4) And this happens......seemingly randomly. About rate of 1/10 or so.
5) I 'do not consider' this as a major bug, nor can confirm I can provide a method to replicate this consistently.

Seems like checking if ExplorerPatcher preserves input method on installation/restart might be relevant, but other than that I have no idea either. Those shouldn't change, but *maybe* MS did something awful.

If what @COKID experienced is not this, and surely did not have US input method installed unknowingly(it is installed by default on some devices), I could not replicate the behavior using Chinese, Japanese, Korean input.

Note that I only used input methods provided officially by Microsoft; I cannot/do not plan to test other settings.

**Comment by BraINstinct0** [comment]
Bah, missed one thing.
The 'behavior' should mean, 'an (presumably) not installed EN(or US) input method shows up after ExplorerPatcher is installed'.

1) as per my experience, removing the EN one and retesting thoroughly is required to confirm if that is the case.
2) if that isn't the case, my comment above can be considered a minor but separate issue.
