### ISSUE TITLE
SearchIndexer.exe -> critical events

### ISSUE THREAD

**Issue by adylyn** [valinet/ExplorerPatcher#517]
![Zwischenablage01](https://user-images.githubusercontent.com/95639665/144877618-22fc7724-e956-45f9-b6cb-9b2c6517d6c7.jpg)
![Zwischenablage02](https://user-images.githubusercontent.com/95639665/144877630-d931bca7-a0f3-42e6-bff7-fd4265a0633d.jpg)
![Zwischenablage03](https://user-images.githubusercontent.com/95639665/144877773-77bd6e98-5167-4c46-a0b2-30042847cdaa.jpg)
etc.

**Comment by valinet** [comment]
Pffff

There is already a thread about this… #416

I said a million times by now not to open duplicate threads. But why bother?

How can I solve this if everyone just likes to complain and does not provide any useful information? I ask there how can I reproduce this, no one cares, they just dump whatever they have and disappear. It happens because you use EP aa shell extension. That injects a DLL in all applications, it’s clearly stated in the documentation. There is an issue with it being injected in SearchIndexer.exe apparently and not working right. I don’t know how to reproduce, I don’t use that option and no one wants to really work with me on this.

Your screenshots are in German. Idk how to get to those locations, I have to Google and spend time with translations because providing all the useful info from the start is too big of an expectation indeed.

Move the talk to the other thread. No need to have another one.

**Comment by valinet** [comment]
Continue the thread in #416
