### ISSUE TITLE
Modifying StuckRectsLegacy is overwritten by Explorer saving its internal state when it is restarted

### ISSUE THREAD

**Issue by vandelli-smeup** [valinet/ExplorerPatcher#523]
Hello,
with new release can't use taskbar at top anymore. 
I tried some different configurations on StuckRects3 and StuckRectsLegacy, changing value like here
![Senza titolo](https://user-images.githubusercontent.com/55136273/145003579-33a30069-99d8-4dec-98ef-341b8beb4fae.png)
from 03 to 01.
when explorer is restarted, changing on StuckRectsLegacy dosent have effect and value come back to 03.

**Comment by Anixx** [comment]
Is there a reason why you want to do it via registry instead of moving it with mouse?

**Comment by vandelli-smeup** [comment]
dosen't working for me. i can't drag it to the top.
this proprty come back to bottom after explorer restart

![Senza titolo](https://user-images.githubusercontent.com/55136273/145009910-88a11739-5c7b-4005-b975-e2a2f864310d.png)

**Comment by Anixx** [comment]
If you can't drag it to the top, this means you are using the Windows 11 taskbar. The drag option is there since Windows 95.

**Comment by vandelli-smeup** [comment]
now work... i've changed taskbar style property to 11 and then to 10 again.

Thanks.

**Comment by valinet** [comment]
So I implemented those much requested options to be able to configure where the taskbar sits, because dragging it such a big mystery for a lot of people. All that those options do is change that byte in StuckRects3 programatically. Indeed, I saw this thing where the option for the primary one, you set it from bottom to top, it sets the registry correctly, if you restart Explorer right away it’s fine, if you wait 30 seconds or so, there is some other thread in Explorer that resets it back to bottom or something like that, idk, something else resets it back, so this would have to be investigated. Maybe it is some protector for its location, idk. Another wonderful functionality that requires extensive testing for the tiniest outcome ever.

Also, if you prefer messing with the registry, at least mess with it right and logically:
* StuckRectsLegacy is the location where the positioning settings for the Windows 10 taskbar are kept so that we avoid people setting the taskbar to left, uninstall EP and then the whole desktop is glitched out because the 11 taskbar is incapable of displaying at the side of the screen
* StuckRects3 is the default location where it would write those settings, currently used only by the Windows 11 taskbar

**Comment by valinet** [comment]
A fix will be provided for Explorer saving its internal state and overriding the modifications we do in StuckRectsLegacy.

**Comment by MauroPerri** [comment]
Hi, I have the exact same problem. I just upgraded from win10 to 11 and the taskbar is fixed on bottom. No options in the GUI, all the menus I see in the above pictures are different from what I see now. The only solution I found is to manually modify the registry. No problems, I did it but it reverses the changes automatically when I restart explorer. 
How can I keep the changes? Thanks in advance for your help.
