### ISSUE TITLE
Legacy status bar showed up

### ISSUE THREAD

**Issue by realies** [valinet/ExplorerPatcher#583]
![image](https://user-images.githubusercontent.com/5107843/146732267-fe795a03-a8b2-4362-bd44-bdabf2fccaf1.png)

I used a few software packages that modify windows 11's explorer layout and very recently noticed that I have this legacy status bar at the bottom of explorer windows. Any clue how to get rid of it (presume registry flag), or if it may be related to ExplorerPatcher?

**Comment by Anixx** [comment]
This is nt related to Explorer Patcher, it is OpenShell.

**Comment by Anixx** [comment]
A lot of people already asked this question: https://github.com/valinet/ExplorerPatcher/discussions/519
This has nothin g to do with Explorer Patcher.

**Comment by realies** [comment]
@Anixx, thanks a lot, and sorry for the spam, could not find it using the issues search.

**Comment by valinet** [comment]
Because it is likely not in issues. This clearly exists: https://github.com/valinet/ExplorerPatcher/issues/56. Non-issues, which this is, should be posted in [Discussions](https://github.com/valinet/ExplorerPatcher/discussions).

**Comment by realies** [comment]
Have never used discussions before and frankly did not know about it until now :)

**Comment by valinet** [comment]
GitHub is a site for developers, but since a lot of people were interested in getting in touch with the developers, they specifically made that so that issues include only items related to the development of the actual software.

**Comment by realies** [comment]
Issues and discussions are both related to the development of the actual software. Issues seem more sensible to be used when someone is having an issue, and discussions when someone is having ideas for bringing in new features or modifying old ones with the feedback of the owner/community. I think using issues for this particular case is the best choice.

**Comment by chip33** [comment]
Hi realies, the way it works here is to post potential issues in Discussions and then if they are confirmed they get moved to Issues, they still get checked in discussions but that means only the confirmed ones are kept in Issues.

**Comment by valinet** [comment]
@realies I think the decision how to run things around here belongs primarily to the developers of the project. It's neither a matter of popular vote, nor a matter of catering in any particular way to potential issue reporters. The things here are organized so that it's easy for the developers to sort through relevant stuff vs support questions. Under regular circumstances, support questions have nothing to do with a Git issue tracker. GitHub tries to cater to both the worlds and provides this "Discussion" section which is equivalent to a support forum.

> Issues seem more sensible to be used when someone is having an issue, and discussions when someone is having ideas for bringing in new features or modifying old ones with the feedback of the owner/community.

So, no, I don't see it like that. A Git tracker for a project needs a place where developers (and since it's public, other interested users) can track issues with the product. That alone. Not issues related to Windows 11 in general, Windows Update, ClassicShell/OpenShell, StartIsBack/StartAllBack, Start11 etc. That's what "Issues" is designed for, writing down ideas and tracking identified problems with the software. What you suggest is basically users discussing stuff in both issues and discussions, depending on whether they *feel* the thing's an issue or not, and then me and whoever is interested in actual development of this software, which, I emphasize again, GitHub is designed for that, not as a software store etc, have to find some external place, Trello, things like that, where we can track the development, because everything here is hijacked by support threads.

That this site is used in a bad way across most repositories can be easily seen by the number of open issues in most programs; a lot of developers kind of give up managing this space, as actual, *interesting* content is 10% or less it seems. Take any project you want with reach similar to EP and you'll see how bad their issue trackers look; they're basically useless and unmanageable without a big army of moderators. I don't have that here.

The idea is simple. Post in "Discussions". If you feel like it's a problem, an actual issue, post there still. People come, I come from time to time, we read, some folks if they know something can help out, and only after we test and confirm it's an actual problem, a ticket is created here, thus the discussion is promoted as an issue and someone (me) gets to fixing it. That way, I can open "Issues" and see something useful for me, like things to do, to fix, it helps me remember what I have to do, not random support stuff. Not reading this rule is bad enough, disregarding that on purpose so that it is "more seen" is rude. GitHub does not yet offer the possibility of restricting issue creation. Once they do, I will be among the early adopters. "Issues" have to be actual stuff that help developers do work, not largely a support forum.

> I think using issues for this particular case is the best choice.

No, it's not. It's not an issue as in a problem with ExplorerPatcher. As @Anixx mentioned and as many knowledgeable users already know, it's easy to spot that's the status bar added by OpenShell. So yeah, not caused by EP, not related to EP, not even "caused" by OpenShell, as it's intended functionality the OP simply does not know about, he/she skipped that part of the manual (we all sometimes do) and didn't know about that. 100% a support question (and not even support for this app in particular), which is uninteresting for the developers. Even if it were, it's poorly written anyway, providing none of the traits that can lead to successfully determining and providing a fix, if the case. 

> I used a few software packages that modify windows 11's explorer layout and very recently noticed that I have this legacy status bar at the bottom of explorer windows.

Rule number 1 when considering whether something belongs in Issues is to isolate the problem, and get rid of additional variables. Ofc things are prone to happening when you modify everything with "a few software packages". To determine if a behavior is specific to EP, first recommendation is to try to reproduce it on a clean slate, fresh Windows install, in a VM, for example. If it does not happen there, step 2 is to do some investigative work as to gather some clues. I am neither a wizard, I cannot magically guess conditions on everyone's computer, nor have absolute knowledge, I myself can miss some points. And I also do not have time to do myself the investigation for each and every quirk. Users have to be willing to put up a bit of work if they want to help, throwing generic stuff on a table full of staging documents is not much help at all.

> Any clue how to get rid of it (presume registry flag), or if it may be related to ExplorerPatcher?

As you see, even the OP *feels* like this might have nothing to do with EP. So unless he missed the single rule that's written in capital letters when you land on the "Issues" page, he has no excuse for posting this here, if you ask me. It's simply not interesting at all from a developer's perspective. Ofc, as a support ticket, others and even me try to answer those and help whenever we can.

I partly agree with @chip33 as well. Or rather, I'd modify his reply. It's not about "the way it works here", but rather more like the way it ought to work everywhere. That the system we currently have is dysfunctional in general on GitHub is a known fact, there are a lot of developers complaining of the same things I complain here, for example https://github.com/dear-github/dear-github/issues/293. The site is not working for us at all. This is also not a social network. I don't care for tons of content, I rather fancy quality content. It also doesn't help that communicating with GitHub is difficult, because they do not have a public repo to discuss this. Guess why.

**Comment by chip33** [comment]
Hi, I deleted my reply to @realies saying the way it works here is to post it in Discussions and then it would be moved to Issues if confirmed. Just mentioning it here again for context.

**Comment by valinet** [comment]
@chip33 Not really needed to delete, I hope I didn't imply that. We may have different opinions, but anyone is generally welcome here. I also encourage discussing opinions, despite sometimes not agreeing with some people over here on particular matters, I NEVER delete any comment, be it negative or positive or whatever.

**Comment by chip33** [comment]
Hi, yes, no worries, I just deleted it as I wasn't sure it needed me to say it.
