### ISSUE TITLE
Dual monitor autohide support for Windows 11 style taskbar

### ISSUE THREAD

**Issue by rbreaves** [valinet/ExplorerPatcher#589]
It appears this does not, although it did not work before with the normal taskbar under Windows 11 either. The Windows 10 taskbar though does indeed support autohide properly on dual monitors at least.

Aka placing your mouse over the taskbar on a secondary monitor does not work.

**Comment by valinet** [comment]
I have fixed this in the latest version (.17). It's a bug with Microsoft's Windows 11 taskbar. One more thing this utility has to fix. Too bad I don't have access to the same tools that they do in-house... Btw, since this is not an issue with EP per se, it would have been better if this was opened in "Discussions".

Merry Christmas and a happy new year!
