### ISSUE TITLE
How to hide labels on taskbar?

### ISSUE THREAD

**Issue by chloelemaire** [valinet/ExplorerPatcher#612]
I update recently version, 

Labels that were not previously displayed began to be displayed. I looked up the settings, but I couldn't find anything related. What should I do?

**Comment by CyborgArmGon** [comment]
Same, I never touched this setting, and they showed up on update.

**Comment by chloelemaire** [comment]
> 

thx problem solved

**Comment by CyborgArmGon** [comment]
Glad that fixed it for you too

**Comment by valinet** [comment]
It’s not an odd default. A lot of people installing this do it so they can get that back. Plus, the Windows 11 already offers that, the 10 one is mostly similar without that. That should have been the default since v1 but only now it has been properly implemented. The reason it seemed to reset during this upgrade is because when using the 10 taskbar, settings for that are now stored separately because it caused problems for the 11 taskbar. So Explorer looked for the settings in the new location which was empty and, as I said, it assumes “show labels” by default due to the reasons I mentioned above. It’s an option anyway, so no big deal, you can get whatever behavior you like, and it happens only during this update, subsequent ones will preserve your settings just fine. I could have introduced a migration tool in the backend for this configuration as well (there are a number of migrators for other features), but honestly, I did not think about this case, it hasn’t crossed my mind and no one pointed it out. Anyway, not a big deal, I believe, and the option and behaviors from previous versions are still there. 

Hope you enjoy the update and all of you have a great new year!

**Comment by valinet** [comment]
I have issued a hotfix update that addresses this (migrates the previous setting correctly) in the latest release (40.21), so at least users that haven't upgraded yet do not face this anymore. Thanks for the feedback, this release (40.21) contains just that, and it doesn't affect users who have already upgraded (to 40.20, for example), change their settings etc. Again, this happened because I simply haven't thought of this scenario during the time this update was in testing.

Thanks again for the feedback and wish you a great new year!
