### ISSUE TITLE
It doesn't support 22499 preview on arm64

### ISSUE THREAD

**Issue by LoveJessyChen** [valinet/ExplorerPatcher#617]
It doesn't support 22499 preview on arm64

**Comment by valinet** [comment]
Not an issue. Have you read #56?

Duplicate. I have clearly asked to search for previous threads before opening a new one on a similar topic: #138.

EP works as-is on Insider Preview builds because things there change too often for a patch to be worth developing. I don’t actively develop or test against those.

EP doesn’t work on ARM64. I do not own (or need) an ARM64 based machine, so I cannot test against that. It cannot run as-is, care has to be taken to natively compile and test it against that architecture. Emulation doesn’t cut it, in this case. If someone’s willing to pick up the port for the architecture, they have my support and maybe something comes out of it. But personally, at the moment, I have no plans of working on that.

**Comment by LoveJessyChen** [comment]
I want to help you develop a arm64 version for every who owns an arm64-based pc. 
I can test the ep on win11 arm64 and x64.

**Comment by valinet** [comment]
Okay, well, the source is all available, try compiling it and see what fails (for e.g., use Detours for hooking instead of funchook which is amd64 only, only required change is to modify a define), then see what works, propose some patches for what does not and we can review them and go from there.

**Comment by Amrsatrio** [comment]
Check https://github.com/valinet/ExplorerPatcher/discussions/138 again. I'm making progress on it.
