### ISSUE TITLE
enable navigation through the app's settings window properties by keyboard 

### ISSUE THREAD

**Issue by fernando-jose-silva** [valinet/ExplorerPatcher#627]
I hope everything is fine with everyone.
First I would like to apologize, this text is translated, I am Brazilian and I speak only Portuguese.
I am visually impaired and I use this application, as well as all windows applications using a screen reader, in this case the screen reader
novda
www.nvaccess.org
I met explorer patcher and from the beginning I liked it a lot, my big congratulations.
With this software I can modify my windows and I feel the difference when navigating using the keyboard, other customization tools are bad, many times they only modify the appearance, but those who use the computer don't use a keyboard and don't notice any difference.
Sorry to elaborate, but I would like to give an example of how useful your work is.
I installed the explorer patcher for my blind students, to recapture points in windows 11 that they really liked, like showing the desktop button when tabbing the desktop, always showing all items in the toolbar, always showing all the programs in the start menu., and everyone is very grateful.
Now comes my request if possible.
When I go to configure the app explorer patcher I enter into properties, I can't navigate with tab and arrows in the window.
So I'm almost unable to customize the explorer patcher, which is a very big deficiency.
To customize the software I have to use the character recognition ocr tool of the screen reader nvda, as well as the mouse click simulation, which for someone who is blind and uses only the keyboard is a very bad experience.
I would like to ask you please if possible to implement a graphical interface that allows configuring the explorer patcher app using the keyboard, and implementing accessibility tools so that it is accessible to screen readers.
Sorry, I can't help anymore, I'm not a programmer, I'm a basic computer teacher for visually impaired students.
I also recommend the github
from the nvda screen reader project
https://github.com/nvaccess/nvda/
I believe that there you can learn more about the screen reader and find out more information on how to make the explorer patcher more accessible to screen readers, so you would talk among programmers, laugh.
Also your knowledge I'm sure would make the screen reader nvda evolve and help more visually impaired in the world.
Sorry for the big message, congratulations on the work, and you are helping with accessibility and ease of use for the visually impaired, congratulations.

**Comment by valinet** [comment]
Hi

You can actually navigate the Properties window using the keyboard alone even with your current version. Furthermore, I have made some improvements in the latest pre-release (41.1). Thus, the interface can be navigated now as follows: the `Tab` key or the `Down` arrow highlights the next item in the current page, while `Shift`+`Tab` or the `Up` arrow the previous one. Pressing the `Space` key or the `Return` key interacts with the selected item (which may be a check box, list, link, or button). To switch to another page, press any of the numbers `1` to `9` corresponding to the index of the section (so, `1` for "Taskbar", `2` for "System tray", up to `9` for "About") or use the `Left` or `Right` arrow keys. To exit the window, press the `Esc` key.

Most of the Properties UI was an afterthought, it was never intended as actual functionality. It's implemented by hand, manually, without any UI toolkit or framework. That's why supporting translations, or screen readers, features requested by some users, takes a while to implement, besides the actual work of maintaining such features (most problematic with translations).

Anyway, I have implemented basic support for screen readers in the latest pre-release (41.1). The window will read the selected items and read its status in response to user actions performed with the keyboard. I tested it with the software you mentioned (NVDA), as well as Microsoft Narrator.

When you open the window, instructions about how to navigate the interface will be read aloud. To hear those instructions again, press the `F1` key or the `H` key.

That being said, I hope that this basic support will do for now. I reckon the interface is usable now in a scenario similar to the one mentioned by you above. I will close this issue for now, and hopefully more work in this area might take place in the future, as required.

Thanks

**Comment by fernando-jose-silva** [comment]
thank you very much for the wonderful work, version 41.1 works as desired, me and many visually impaired people would appreciate it.  Happy birthday.
