### ISSUE TITLE
Win + x hotkey no longer works

### ISSUE THREAD

**Issue by srwhaley** [valinet/ExplorerPatcher#63]
I installed the dll file to my C:\Windows directory and restarted file explorer + my PC. Now, the win+x hotkey does not register. Windows key by itself works, and I can right click the start button to bring up the window, but the actual shortcut does not work. Any reason why that would break?

I am currently on v23. Originally installed 24, the hotkey didn't work, so I tried to downgrade, and the hotkey still does not work.

**Comment by valinet** [comment]
Hmmm... I don't know. For me it works, just tested now... so you say right clicking on the Start button opens the power user menu, but pressing `Win`+`X` does not?

**Comment by srwhaley** [comment]
It seems that having auto-hide on was the reason it wasn't working, setting the taskbar to always show allows me to use win+x. @Gaurav-Original-ClassicShellTester Win+C also does not work when I have auto-hide on.

**Comment by valinet** [comment]
@srwhaley @Gaurav-Original-ClassicShellTester It is fixed, 22000.194.0..25 is a new release which contains this fix. Thanks for reporting. Finally implemented properly as specified in #3.

**Comment by valinet** [comment]
> 
> 
> No issues for me with Win+X whether Taskbar is on auto-hide or not.
> 
> I am on Windows 11 22471.1000 and running ExplorerPatcher 22000.194.0.24 built on Oct 10.
> 
> @srwhaley, do other hotkeys work like Win+C for Calendar? Or does it bring up that awful Windows 11 Chat app?

To iterate on that, no shortcuts that in the backend involved programmatically clicking on some button from the taskbar work when the taskbar is hidden, for obvious reasons (the buttons are not on screen anymore). The correct way to toggle these menus, flyouts etc is to inspect the disassembly of shell components and see whether there is an interface that provides access to that functionality. The Start button disassembly from explorer (specifically `CPearl::_GetLauncherTipContextMenu`) had a good example on how to trigger the `Win`+`X` menu, and it just worked if implemented properly, as we already knew it worked as right clicking the Start menu triggers `Win`+`X` just fine.

Regarding `Win`+`C`, that also works in the "classic" way of clicking the clock in the taskbar via code. I will check at some point, maybe there is an interface for the date time flyout as well that we could call so that this functionality could be implemented in a proper way, as well.

**Comment by valinet** [comment]
My pleasure. It was quick because I learned quite a few things since 2 months ago approximately when I started working on this ;)
