### ISSUE TITLE
Disable grouping

### ISSUE THREAD

**Issue by ErickWei** [valinet/ExplorerPatcher#7]
Can we disable grouping function on taskbar?

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Yes. To disable grouping, merge this into the Registry after enabling Classic Taskbar:

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer]
"NoTaskGrouping"=dword:00000001

This returns text labels as well as restores "Never combine" behavior.

**Comment by ErickWei** [comment]
> Yes. To disable grouping, merge this into the Registry after enabling Classic Taskbar:
> 
> Windows Registry Editor Version 5.00
> 
> [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer]
> "NoTaskGrouping"=dword:00000001
> 
> This returns text labels as well as restores "Never combine" behavior. Will need to log out or refresh Group Policy and restart Explorer of course.

Thanks Bro,It's  work

**Comment by valinet** [comment]
Besides closing this issue, I will pin it to the top, as I believe it is a "good first issue" for new users.

Just for the sake of completeness, here is the setting in HKCU that achieves what the policy above does (which is similar and works fine, no issue with it):

* For the taskbar on the main monitor:
```
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"TaskbarGlomLevel"=dword:00000002
```

* For the taskbars on other monitors:
```
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"MMTaskbarGlomLevel"=dword:00000002
```

) = Always combine, 1 = Combine when taskbar is full, 2 = Never combine

Maybe I can also write an issue where I mention common settings for the taskbar, or maybe a small GUI in the app where you can set these now that the settings app does not give you the option anymore...

(Just a small mention as well: if you are running 22000.1, you can set `UndockingDisabled` to 1 (`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell\Update\Packages`, DWORD), open Settings, then revert back to 0 but keep the Settings app open and go to "Taskbar settings" and all the old configuration options are there and you can edit whatever you want and will take effect immediately on the taskbar. You need 22000.1 because that has the old Settings app.)

Thanks for help @Gaurav-Original-ClassicShellTester.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Ah yes the non-policy settings are important if you don't wish to lock it down. As well as the multi-monitor setting.😊

**Comment by Hunanbean-Collective** [comment]
I was unable to find information on this.   Can you Never Combine, but still do Not show labels?

**Comment by pyrates999** [comment]
> How do we 'Never Group' with the 'new' "Windows 10 (ExplorerPatcher)" taskbar style?
> 
> This is a workflow killer for me. I really need my tasks ungrouped, uncombined.

Please discuss here: https://github.com/valinet/ExplorerPatcher/issues/3769

**Comment by jerry-monitor** [comment]
Is it possible to do Hide Labels + Never Group?

**Comment by pyrates999** [comment]
This was closed 1 and a half years ago.  You can open up a new discussion.  But the windows 10 EP implemented taskbar, for customizations, uses windhawk mods.  You should ask over there in their github: https://github.com/ramensoftware/windhawk/discussions

**Comment by jerry-monitor** [comment]
We're not allowed to use windhawk at the office (and at home I am on Linux) so it would not work for me, but thanks.

**Comment by pyrates999** [comment]
Then how are you allowed to install EP?  Please see this warning about using the EP implemented windows 10 taskbar, it is not recommended for work pc's: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation#%EF%B8%8F-warning---read-thoroughly-before-using

**Comment by jerry-monitor** [comment]
I've been trying so many different tools that I might have confused some. I am pretty sure I have used EP in the past. Sorry for the confusion.

**Comment by pyrates999** [comment]
You can find out if you have EP installed by opening up the EP properties application, it is named **Properties (ExplorerPatcher)**.  Click on about on the left side, and you should see the version number you have installed.
