### ISSUE TITLE
Built-in update triggers anti-virus (Bitdefender) to delete all EP files automatically

### ISSUE THREAD

**Issue by ecsedya** [valinet/ExplorerPatcher#744]
The recent update caused Bitdefender to identify the behaviour as malicous and start continously blocking and quarantining files associated with Explorer Patcher, then deleting them after reset.

No such behaviour when the installer is downloaded manually from GitHub (although at download Chrome flags the file as potentially malicious and blocks it, which you have to bypass and Win11 SmartScreen pops up at the installation because of the unsigned installer which you also need to bypass).

**Comment by valinet** [comment]
I understand, but this is not an issue with EP. This is already documented here: https://github.com/valinet/ExplorerPatcher/wiki/Antivirus-false-positives

I'd say this is a bug in Bitdefender. Or rather, as they call it, "false positive".

The updates are downloaded to `%APPDATA%\ExplorerPatcher`. You can compare the hashes of the files there to the hashes of the files downloaded from GitHub. If they match, than the update is identical. It is by the nature of this software that some "antivirus" products will flag it in various ways.

**Comment by pentium10** [comment]
I got this issue today as well 

![image](https://github.com/valinet/ExplorerPatcher/assets/465691/597618ff-d2b1-4da3-8468-6edcd84fe18d)

**Comment by pentium10** [comment]
I reached out to Bit Defender but they are clanky to take action, are you able to supply the below information? @valinet 

Thank you for contacting the Bitdefender Enterprise Support team.

Unfortunately, we can't proceed to investigate the false positive report based on information provided on third party forums, blogs, threads etc.
In order to escalate the false positive detection reported to our Antimalware team, please provide the following information from your end:
A CSV export of both a Malware Status and a Security Audit report generated for the affected endpoints and for a period that includes the detection event;
Screenshots of the detections done by the security agent. Please make sure these screenshots have all the necessary information (detection name, file name, file path). They can be from the GUI console of the security agent, or from various areas in the GravityZone Control Center that are logging detections (Threats Xplorer, Incidents, Security Audit report, etc.)
A BDSyslog gathered from one of the endpoints affected (where the detection occurred).

We are looking forward to hearing from you.

**Comment by pentium10** [comment]
I mitigated this issue with the Bit Defender team, and the issue has been fixed, I personally confirm.

Update time: Wed May 24 07:50:30 2023
Version: 7.94659

@valinet you can remove the issue from the Pinned area.
