### ISSUE TITLE
Windows 11 Start menu still opens in the center, could it respect Windows setting?

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [valinet/ExplorerPatcher#8]
Although personally I use third party Start menus with the Classic Taskbar, with ExplorerPatcher 22000.168.0.10, the Windows 11 Start menu or its search still opens in the center even if before or after switching to the classic Taskbar, the alignment is set to Left from Settings.

**Comment by valinet** [comment]
Yeah, I know, it is the latest thing on my mind, I wanted to work on it but the other stuff I thought was more important on the priorities list. It bothers me a bit because I personally don't use a Start menu replacement as the way I use Start is anyway just for searching or hitting the few shortcuts I pin there, and getting to the menu after clicking the Start button is a bit hard on the big monitors I have at my desk.

I wonder where the behavior of ignoring the "Left/Center" setting is coming from. The way I imagine it, as the setting is actually called "Taskbar alignment", that just sets where the taskbar will align its icons, and then the menu just looks for the Start button I think and kind of adjusts to that. Or something like that, I don't think the Start menu reads this setting directly, I think it looks for something in the new taskbar to determine where to position itself, and since the new taskbar is not running, it just defaults to center.

Also, I wonder if it is tied to search. Like, if I manage to make Start open on the left, will search follow it naturally there? Also, I wonder whether it is possible to achieve this from Explorer, because the menu is hosted by `StartMenuExperienceHost.exe` but the way it seems to me, clearly communicates with Explorer somehow and gets some data from it, because otherwise it would just respect the registry setting.

I will investigate this, hopefully I also find something meaningful along the way. First thing is to determine when `TaskbarAl` is queried and by who, and go from there, I guess (ProcessMonitor to the rescue).

**Comment by Gaurav-Original-ClassicShellTester** [comment]
The funny thing is I was playing around with Winaero Tweaker and I set Taskbar to the top. Then the floating Windows 11 menu opens to the left (from the bottom) 😂 But if I type something, the search opens in the middle.

**Comment by valinet** [comment]
@Gaurav-Original-ClassicShellTester Yeah, for me, when I set taskbar to top, Start menu will open on the top left, while search indeed gets on top but it remains centered. There is no registry access for `StuckRects3`, so it seems that the Start menu and Explorer communicate somehow in some other way...

**Comment by valinet** [comment]
So yeah, after much trial and error, I managed to pull it off: now the Start menu and search appear to the left, I added support for that in the latest release (22000.168.0.14). I am glad we made it to this point, I can now take it slowly and polish things here and there and hopefully refactor some of the code a bit, I feel like it deserves that. I also updated the [README](https://github.com/valinet/ExplorerPatcher/blob/master/README.md) with information about these latest changes, and I hope that this version works well, I consider it fairly mature and worth using on a daily basis.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Ohh! Love your analysis and explanation on how things work.

This works fantastic!

I found that even though it works with StartIsBack++ installed to skin and fix the Taskbar, while it downloading symbols and determining offsets to patch, StartIsBack needs to be disabled. Once full functionality is enabled, it can be enabled. Otherwise it fails to patch Explorer due to StartIsBack interfering with it.

**Comment by valinet** [comment]
Yeah, good point. I will add this mention to the README at some point. 

Also, idk, maybe using the pregenerated files should be preffered first for new users, and then the automatic symbol download? Idk, I will think about it…

I wonder why StartIsBack interferes with its patching though. I mean, probably it restarts Explorer as well and multiple instances spawn and the offset to patch cannot b determined correctly because a race condition naturally appears… just a guess. Yeah, advice is, during the initial analysis, temporarily disable any stuff that gets in Explorer, afterwards it should work just fine, indeed.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
For now until you figure out the race condition, I have put the 22000.168.0.12 version of the DLL in C:\Windows and 22000.168.0.14 in Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy and MicrosoftWindows.Client.CBS_cw5n1h2txyewy.

Otherwise it was causing slow logon again with StartIsBack++ installed. But worse, with Open Shell also installed, Shift+Win key wasn't opening the Windows 11 Start menu until I exited Open Shell's menu, press Win key once and again started Open Shell's menu in which case it would begin functioning normally.

But with the above setup, everything works. No slow logon, no compatibility issues with any Start menus with 22000.168.0.12 in C:\Windows and the 22000.168.0.14 DLL makes sure it appears on the left.

**Comment by valinet** [comment]
Can you retest 22000.168.0.14 in `C:\Windows`, please? I have uploaded a new version in-place in Releases that restores the original fix for logon delay. Can you check if it works like 22000.168.0.12? Thanks.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
FIXED! :D Now no issues with the latest DLL in C:\Windows and in other locations too. Updated everywhere. 

Slow logon is fixed. Open Shell Win key compatibility issues also gone.

So far so good. If I discover any issues, I will of course let you know.

**Comment by valinet** [comment]
Yeah, the interference with OpenShell and Win key is related to the fact that I also hook the `ProgMan` window and intercept the `SC_TASKLIST` message which means Start is about to be opened. I do that since I also implement that feature which OpenShell already has where it opens the Start menu on the monitor with the mouse. But since I am not aware of OpenShell in my code, I always display the Start menu. If my hook runs before OpenShell's, that's what probably breaks it. But I only when the following registry key is set to 0: `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StartPage\MonitorOverride`. Do you have that set to 0? If you delete it, then the problem should not happen anymore. Can you check, please?

**Comment by valinet** [comment]
Also, the delay at logon is tricky. The correct way I think is to wait for the Start button to be created, wait a bit more (300ms) and then dismiss the logon screen. That's what I had in 22000.168.0.14. But you said it causes problems. The behavior in 22000.168.0.12 which I have restored is to wait 2 seconds... I don't know, maybe wait for Start to be created and then wait some more (like 1s)... for me, it works, that's the thing... Or have it as a setting...? Maybe that would be the best idea.

**Comment by valinet** [comment]
Yeah, so redownload the DLL from Releases, add `ExplorerReadyDelay=2000` in the `[General]` section in `settings.ini` and that should restore the behavior in 22000.168.0.12 pretty much, which is to wait 2 seconds at logon and then signal shell ready. Default is to look for the Start button, wait 600ms, and then signal shell ready. Idk, makes sense to me like this at the moment...

**Comment by Gaurav-Original-ClassicShellTester** [comment]
MonitorOverride is not present at HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\StartPage. However I did experiment with it, setting it to 1. But it didn't work for me to open the Windows 11 menu with the Win key on the active monitor. So I deleted the value. I use Open Shell's Setting anyway which I had requested Ivo to add :D, "Open Windows Start menu on monitor with the mouse" since it works reliably for all menus - the Open Shell menu, and the Windows 10/11 menus.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
OK I figured MonitorOverride=0 makes it work. Yes that's working. But it override Open Shell's Win key to open its menu completely to I will keep it at 1 or deleted :)

**Comment by valinet** [comment]
> 
> 
> OK I figured MonitorOverride=0 makes it work. Yes that's working. But it overrides Open Shell's Win key to open its menu completely to I will keep it at 1 or deleted :)

Okay, that happens for me as well, it is probably because my hook gets executed first and I always open the Windows 11 Start menu, as I don't know about OpenShell in my code. Makes sense. Yeah, just disable the feature in ExplorerPatcher and use OpenShell's, the code is identical as I took it from in there =)))

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Right now with the latest DLL you updated, there are no issues.

**Comment by valinet** [comment]
The DLL right now on GitHub releases is the same as the one from 6 hours ago, only thing is I added an option to manually specify the time after which the `Explorer ready` signal should be fired, which has the effect of dismissing the login screen. If you say it works with the built-in method, which is look for Start button, wait 600ms and then fire the event, then all good. Idk, see how it goes further on and report back, it is hard to test this kind of stuff on a sample size of 1 computer on which I also develop. If the feedback now is good, I am happy :D
