### ISSUE TITLE
Unable to load weather

### ISSUE THREAD

**Issue by bonxz** [valinet/ExplorerPatcher#836]
Hello, I have a problem with the weather widget. Whenever there are additional warnings like storm or hail you can click on the text with "more". When I press there, the page loads for a moment. So you can see it but after that it immediately changes to Unable to load.

![image](https://user-images.githubusercontent.com/61289944/153625255-a4b4516c-74b1-4556-b791-d14306aaa316.png)

I use the latest Prerelease. My Windows Version is 
![image](https://user-images.githubusercontent.com/61289944/153625572-b497a22f-3cdc-4eea-9e55-130a860a6cc3.png)

**Comment by bonxz** [comment]
https://user-images.githubusercontent.com/61289944/153626975-247be4de-5688-4466-9c57-6895fe141565.mp4

**Comment by bonxz** [comment]
https://user-images.githubusercontent.com/61289944/153627081-33b94759-b6d4-45de-aaf3-ba1d787b42af.mp4

**Comment by valinet** [comment]
What happens if you visit the same address using Google search? If what you type as location is not correctly identified by Google, the widget won’t display any data and show that error, as it simply cannot, the widget is not shown.

Also, check Reporting problems in the wiki, I don’t understand why A LOT of people skip that.
