### ISSUE TITLE
Taskbar not immediately available after login

### ISSUE THREAD

**Issue by udobehm** [valinet/ExplorerPatcher#852]
Hi, when I log into Windows I need to wait for about 10 - 15 seconds until my Windows 10 taskbar has loaded under Win 11.

Can you somehow make the taskbar be accessible and useable immediately when it appears first??

**Comment by valinet** [comment]
I don’t understand exactly. For me, it works fine. In Properties - Advanced there is a setting called “Supplimentary delay at logon”. You can use that to increase the time until the login screen is dismissed.

By default, it waits until the taskbar is created. If it takes too long for it to be actually useful, that could be due to a couple of things, like too slow backing storage, maybe slow extensions that have to load etc. On a regular config, it works just fine.
