### ISSUE TITLE
Clock TaskBar is missing

### ISSUE THREAD

**Issue by fabicurti** [valinet/ExplorerPatcher#88]
Can't say if the problem is with the dll, but after the oct/12 win update, the clock is missing from taskbar
Also the network..

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Which Windows build are you on and updated to what build? Have you managed to get the classic Taskbar working again by putting the most up-to-date dxgi.dll in C:\Windows? You see, whenever Windows build upgrade occurs, new debug symbols may need to be downloaded sometimes by the dxgi.dll. Until then full classic Taskbar functionality is not available and the new Taskbar loads again sometimes.

Also, during Windows Setup, it turns on Focus assist mode and does not turn it off after the upgrade is complete. So turn off Focus assist so you will get notifications from ExplorerPatcher.

Download the latest ExplorerPatcher DLL and copy it to C:\Windows. After that, restart Explorer.exe or kill sihost.exe to restart Explorer.exe and let it download the debug symbols again. If you turned off Focus Assist, it will start giving notifications and tell you after some time that it is done.

Once the classic Taskbar (the one with text labels etc) is loaded, that means you got ExplorerPatcher installed correctly. Then right click the Start button -> Properties. Click the first option Enable missing system tray icons

This only has to be done if the new taskbar loads after a Windows upgrade because it resets some taskbar settings (including system tray icons).

**Comment by valinet** [comment]
Each update resets the icons in the system tray. You can enable them by running: `%windir%\explorer.exe shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9}\SystemIcons` or Properties - Enable missing system tray icons as @Gaurav-Original-ClassicShellTester said. It's stated clearly in the README as well. This is not a problem with this software, it just that Windows decides to reset those.
