### ISSUE TITLE
Context menu icons are missing

### ISSUE THREAD

**Issue by Shaughn-david** [valinet/ExplorerPatcher#958]
When I am using the Windows 10 start menu some of the context menu icons are missing
Explorer Patcher 22000.493.42.24
Windows 11 Build 22000.527
![Screenshot 2022-03-01 132014](https://user-images.githubusercontent.com/76626288/156226211-61c57d39-75f1-4554-b40b-11bdea98b7be.png)
.

**Comment by valinet** [comment]
#56

Idk exactly why it happens, there could be a lot of causes, but since it doesn't get in the way functionally, and is also very rarely seen, I will let this slide. Ofc, if someone or myself make a discovery regarding why this happens, I will fix it. But I won't be actively looking into it, at least for the time being.
